/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { RemoteAgentPresetCatalog, RemoteAgentPresetDocument, RemoteAgentPresetOpenTarget } from '@deepseek-ai/dsh-agent-presets/types'
import type { SessionId } from '@deepseek-ai/dsh-session/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6167656e74507265736574 {
    copy: (from: string, agentPreset: string, name?: string) => Promise<RemoteResult<{ agentPreset: string; }>>
    list: () => Promise<RemoteResult<RemoteAgentPresetCatalog>>
    openDocument: (agentPreset: string) => Promise<RemoteResult<RemoteAgentPresetOpenTarget>>
    read: (agentPreset: string) => Promise<RemoteResult<RemoteAgentPresetDocument>>
    remove: (agentPreset: string) => Promise<RemoteResult<Record<never, never>>>
    select: (agentId: SessionId, agentPreset: string) => Promise<RemoteResult<{ agentPreset: string; }>>
  }
  interface TypertRemoteMap {
    'agentPreset/copy': (from: string, agentPreset: string, name?: string) => Promise<RemoteResult<{ agentPreset: string; }>>
    'agentPreset/list': () => Promise<RemoteResult<RemoteAgentPresetCatalog>>
    'agentPreset/openDocument': (agentPreset: string) => Promise<RemoteResult<RemoteAgentPresetOpenTarget>>
    'agentPreset/read': (agentPreset: string) => Promise<RemoteResult<RemoteAgentPresetDocument>>
    'agentPreset/remove': (agentPreset: string) => Promise<RemoteResult<Record<never, never>>>
    'agentPreset/select': (agentId: SessionId, agentPreset: string) => Promise<RemoteResult<{ agentPreset: string; }>>
  }
  interface TypertRemoteNamespaceMap {
    'agentPreset': TypertRemoteNamespace$6167656e74507265736574
  }
  interface TypertRemoteScopeMap {
    'agent:agentPreset/select': (agentPreset: string) => Promise<RemoteResult<{ agentPreset: string; }>>
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
