/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { AgentPresetDocument, AgentPresetDocumentOpen, AgentPresetRemoved, AgentPresetRoster, AgentPresetSelection } from '@deepseek-ai/dsh-agent-presets/types'
import type { SessionId } from '@deepseek-ai/dsh-session/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6167656e74507265736574 {
    copy: (from: string, agentPreset: string, name?: string) => Promise<RemoteResult<AgentPresetSelection>>
    list: () => Promise<RemoteResult<AgentPresetRoster>>
    openDocument: (agentPreset: string, signal?: AbortSignal) => Promise<RemoteResult<AgentPresetDocumentOpen>>
    read: (agentPreset: string) => Promise<RemoteResult<AgentPresetDocument>>
    remove: (agentPreset: string) => Promise<RemoteResult<AgentPresetRemoved>>
    select: (agentId: SessionId, agentPreset: string) => Promise<RemoteResult<AgentPresetSelection>>
  }
  interface TypertRemoteMap {
    'agentPreset/copy': (from: string, agentPreset: string, name?: string) => Promise<RemoteResult<AgentPresetSelection>>
    'agentPreset/list': () => Promise<RemoteResult<AgentPresetRoster>>
    'agentPreset/openDocument': (agentPreset: string, signal?: AbortSignal) => Promise<RemoteResult<AgentPresetDocumentOpen>>
    'agentPreset/read': (agentPreset: string) => Promise<RemoteResult<AgentPresetDocument>>
    'agentPreset/remove': (agentPreset: string) => Promise<RemoteResult<AgentPresetRemoved>>
    'agentPreset/select': (agentId: SessionId, agentPreset: string) => Promise<RemoteResult<AgentPresetSelection>>
  }
  interface TypertRemoteNamespaceMap {
    'agentPreset': TypertRemoteNamespace$6167656e74507265736574
  }
  interface TypertRemoteScopeMap {
    'agent:agentPreset/select': (agentPreset: string) => Promise<RemoteResult<AgentPresetSelection>>
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
