/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { SessionRemoteAcceptedValue, SessionRemoteAttachmentRequest, SessionRemoteAttachmentValue, SessionRemoteCancelRequest, SessionRemoteCreateRequest, SessionRemoteCreateValue, SessionRemoteForkRequest, SessionRemoteForkValue, SessionRemoteHistoryRequest, SessionRemoteHistoryValue, SessionRemoteListRequest, SessionRemoteListValue, SessionRemoteModels, SessionRemoteModelsRequest, SessionRemotePromptRequest, SessionRemotePromptValue, SessionRemoteRenameRequest, SessionRemoteRenameValue, SessionRemoteResult, SessionRemoteSearchRequest, SessionRemoteSearchValue, SessionRemoteSelectModelRequest, SessionRemoteSelectModelValue, SessionRemoteUpdateQueueRequest } from '@deepseek-ai/dsh-session/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$73657373696f6e {
    attachment: (request: SessionRemoteAttachmentRequest, signal?: AbortSignal) => Promise<RemoteResult<SessionRemoteResult<SessionRemoteAttachmentValue>>>
    cancel: (request: SessionRemoteCancelRequest, signal?: AbortSignal) => Promise<RemoteResult<SessionRemoteResult<SessionRemoteAcceptedValue>>>
    create: (request: SessionRemoteCreateRequest, signal?: AbortSignal) => Promise<RemoteResult<SessionRemoteResult<SessionRemoteCreateValue>>>
    fork: (request: SessionRemoteForkRequest, signal?: AbortSignal) => Promise<RemoteResult<SessionRemoteResult<SessionRemoteForkValue>>>
    history: (request: SessionRemoteHistoryRequest, signal?: AbortSignal) => Promise<RemoteResult<SessionRemoteResult<SessionRemoteHistoryValue>>>
    list: (request: SessionRemoteListRequest, signal?: AbortSignal) => Promise<RemoteResult<SessionRemoteResult<SessionRemoteListValue>>>
    models: (request: SessionRemoteModelsRequest, signal?: AbortSignal) => Promise<RemoteResult<SessionRemoteResult<SessionRemoteModels>>>
    prompt: (request: SessionRemotePromptRequest, signal?: AbortSignal) => Promise<RemoteResult<SessionRemoteResult<SessionRemotePromptValue>>>
    rename: (request: SessionRemoteRenameRequest, signal?: AbortSignal) => Promise<RemoteResult<SessionRemoteResult<SessionRemoteRenameValue>>>
    search: (request: SessionRemoteSearchRequest, signal?: AbortSignal) => Promise<RemoteResult<SessionRemoteResult<SessionRemoteSearchValue>>>
    selectModel: (request: SessionRemoteSelectModelRequest, signal?: AbortSignal) => Promise<RemoteResult<SessionRemoteResult<SessionRemoteSelectModelValue>>>
    updateQueue: (request: SessionRemoteUpdateQueueRequest, signal?: AbortSignal) => Promise<RemoteResult<SessionRemoteResult<SessionRemoteAcceptedValue>>>
  }
  interface TypertRemoteMap {
    'session/attachment': (request: SessionRemoteAttachmentRequest, signal?: AbortSignal) => Promise<RemoteResult<SessionRemoteResult<SessionRemoteAttachmentValue>>>
    'session/cancel': (request: SessionRemoteCancelRequest, signal?: AbortSignal) => Promise<RemoteResult<SessionRemoteResult<SessionRemoteAcceptedValue>>>
    'session/create': (request: SessionRemoteCreateRequest, signal?: AbortSignal) => Promise<RemoteResult<SessionRemoteResult<SessionRemoteCreateValue>>>
    'session/fork': (request: SessionRemoteForkRequest, signal?: AbortSignal) => Promise<RemoteResult<SessionRemoteResult<SessionRemoteForkValue>>>
    'session/history': (request: SessionRemoteHistoryRequest, signal?: AbortSignal) => Promise<RemoteResult<SessionRemoteResult<SessionRemoteHistoryValue>>>
    'session/list': (request: SessionRemoteListRequest, signal?: AbortSignal) => Promise<RemoteResult<SessionRemoteResult<SessionRemoteListValue>>>
    'session/models': (request: SessionRemoteModelsRequest, signal?: AbortSignal) => Promise<RemoteResult<SessionRemoteResult<SessionRemoteModels>>>
    'session/prompt': (request: SessionRemotePromptRequest, signal?: AbortSignal) => Promise<RemoteResult<SessionRemoteResult<SessionRemotePromptValue>>>
    'session/rename': (request: SessionRemoteRenameRequest, signal?: AbortSignal) => Promise<RemoteResult<SessionRemoteResult<SessionRemoteRenameValue>>>
    'session/search': (request: SessionRemoteSearchRequest, signal?: AbortSignal) => Promise<RemoteResult<SessionRemoteResult<SessionRemoteSearchValue>>>
    'session/selectModel': (request: SessionRemoteSelectModelRequest, signal?: AbortSignal) => Promise<RemoteResult<SessionRemoteResult<SessionRemoteSelectModelValue>>>
    'session/updateQueue': (request: SessionRemoteUpdateQueueRequest, signal?: AbortSignal) => Promise<RemoteResult<SessionRemoteResult<SessionRemoteAcceptedValue>>>
  }
  interface TypertRemoteNamespaceMap {
    'session': TypertRemoteNamespace$73657373696f6e
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
