/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const WikiFileEntryRemoteCodec$schema = z.object({
  'name': z.string().readonly(),
  'path': z.string().readonly(),
  'isDir': z.boolean().readonly(),
  'size': z.union([z.literal(null), z.number()]).readonly().optional(),
  'children': z.union([z.literal(null), z.array(z.lazy(() => WikiFileEntryRemoteCodec$schema))]).readonly().optional(),
})
const _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_createPage_parameter_0$schema = z.object({
  'title': z.string(),
  'content': z.string().optional(),
})
const _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_createPage_result$schema = z.object({
  'path': z.string().readonly(),
  'ok': z.boolean().readonly(),
  'error': z.string().readonly().optional(),
  'conflict': z.boolean().readonly().optional(),
})
const _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_createProject_parameter_0$schema = z.object({
  'name': z.string(),
  'path': z.string(),
})
const _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_createProject_result$schema = z.object({
  'path': z.string(),
  'error': z.string().optional(),
})
const _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_deepResearch_parameter_0$schema = z.object({
  'topic': z.string(),
})
const _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_deepResearch_result$schema = z.object({
  'findings': z.array(z.object({
  'title': z.string(),
  'path': z.string(),
})),
  'warnings': z.array(z.string()),
  'degraded': z.boolean(),
  'errorCode': z.union([z.literal("stage-executor-unavailable"), z.literal("research-failed")]).optional(),
})
const _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_exportProject_result$schema = z.object({
  'path': z.string(),
  'error': z.string().optional(),
})
const _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_fullGraph_result$schema = z.object({
  'nodes': z.array(z.object({
  'id': z.string().readonly(),
  'label': z.string().readonly(),
  'type': z.string().readonly(),
  'path': z.string().readonly(),
  'linkCount': z.number().readonly(),
  'community': z.number().readonly(),
})).readonly(),
  'edges': z.array(z.object({
  'source': z.string().readonly(),
  'target': z.string().readonly(),
  'weight': z.number().readonly(),
})).readonly(),
  'communities': z.array(z.object({
  'id': z.number().readonly(),
  'nodeCount': z.number().readonly(),
  'cohesion': z.number().readonly(),
  'topNodes': z.array(z.string()).readonly(),
})).readonly(),
})
const _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_graph_result$schema = z.object({
  'nodes': z.array(z.object({
  'id': z.string().readonly(),
  'label': z.string().readonly(),
  'type': z.string().readonly(),
  'path': z.string().readonly(),
  'linkCount': z.number().readonly(),
  'community': z.number().readonly(),
})).readonly(),
  'edges': z.array(z.object({
  'source': z.string().readonly(),
  'target': z.string().readonly(),
  'weight': z.number().readonly(),
})).readonly(),
  'communities': z.array(z.object({
  'id': z.number().readonly(),
  'nodeCount': z.number().readonly(),
  'cohesion': z.number().readonly(),
  'topNodes': z.array(z.string()).readonly(),
})).readonly(),
})
const _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_graphInsights_result$schema = z.object({
  'isolated': z.array(z.object({
  'id': z.string(),
  'label': z.string(),
  'path': z.string(),
})),
  'bridges': z.array(z.object({
  'id': z.string(),
  'label': z.string(),
  'path': z.string(),
  'communities': z.number(),
})),
  'sparseCommunities': z.array(z.object({
  'id': z.number(),
  'nodeCount': z.number(),
  'topNodes': z.array(z.string()),
})),
})
const _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_importProject_parameter_0$schema = z.object({
  'path': z.string(),
})
const _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_importProject_result$schema = z.object({
  'ok': z.boolean(),
  'error': z.string().optional(),
  'entries': z.array(z.string()).optional(),
})
const _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_ingestQueueAdd_parameter_0$schema = z.object({
  'inputs': z.array(z.string()),
})
const _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_ingestQueueAdd_result$schema = z.object({
  'tasks': z.array(z.object({
  'id': z.number().readonly(),
  'input': z.string().readonly(),
  'projectRoot': z.string().readonly(),
  'wikiRoot': z.string().readonly(),
  'projectGeneration': z.number().readonly(),
  'createdAt': z.number().readonly(),
  'status': z.union([z.literal("error"), z.literal("pending"), z.literal("cancelled"), z.literal("running"), z.literal("done")]).readonly(),
  'runId': z.string().readonly().optional(),
  'leaseStartedAt': z.number().readonly().optional(),
  'cancelRequestedAt': z.number().readonly().optional(),
  'completedAt': z.number().readonly().optional(),
  'written': z.array(z.string()).readonly().optional(),
  'ingestedHash': z.string().readonly().optional(),
  'error': z.string().readonly().optional(),
  'failedAt': z.number().readonly().optional(),
  'warnings': z.array(z.string()).readonly().optional(),
})).readonly(),
  'running': z.boolean().readonly(),
  'cancelled': z.boolean().readonly(),
})
const _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_ingestQueueCancel_result$schema = z.object({
  'tasks': z.array(z.object({
  'id': z.number().readonly(),
  'input': z.string().readonly(),
  'projectRoot': z.string().readonly(),
  'wikiRoot': z.string().readonly(),
  'projectGeneration': z.number().readonly(),
  'createdAt': z.number().readonly(),
  'status': z.union([z.literal("error"), z.literal("pending"), z.literal("cancelled"), z.literal("running"), z.literal("done")]).readonly(),
  'runId': z.string().readonly().optional(),
  'leaseStartedAt': z.number().readonly().optional(),
  'cancelRequestedAt': z.number().readonly().optional(),
  'completedAt': z.number().readonly().optional(),
  'written': z.array(z.string()).readonly().optional(),
  'ingestedHash': z.string().readonly().optional(),
  'error': z.string().readonly().optional(),
  'failedAt': z.number().readonly().optional(),
  'warnings': z.array(z.string()).readonly().optional(),
})).readonly(),
  'running': z.boolean().readonly(),
  'cancelled': z.boolean().readonly(),
})
const _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_ingestQueueStatus_result$schema = z.object({
  'tasks': z.array(z.object({
  'id': z.number().readonly(),
  'input': z.string().readonly(),
  'projectRoot': z.string().readonly(),
  'wikiRoot': z.string().readonly(),
  'projectGeneration': z.number().readonly(),
  'createdAt': z.number().readonly(),
  'status': z.union([z.literal("error"), z.literal("pending"), z.literal("cancelled"), z.literal("running"), z.literal("done")]).readonly(),
  'runId': z.string().readonly().optional(),
  'leaseStartedAt': z.number().readonly().optional(),
  'cancelRequestedAt': z.number().readonly().optional(),
  'completedAt': z.number().readonly().optional(),
  'written': z.array(z.string()).readonly().optional(),
  'ingestedHash': z.string().readonly().optional(),
  'error': z.string().readonly().optional(),
  'failedAt': z.number().readonly().optional(),
  'warnings': z.array(z.string()).readonly().optional(),
})).readonly(),
  'running': z.boolean().readonly(),
  'cancelled': z.boolean().readonly(),
})
const _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_ingestSource_parameter_0$schema = z.object({
  'path': z.string(),
})
const _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_ingestSource_result$schema = z.object({
  'written': z.array(z.string()).readonly(),
  'warnings': z.array(z.string()).readonly(),
  'status': z.union([z.literal("error"), z.literal("ok"), z.literal("degraded")]).readonly().optional(),
  'errorCode': z.union([z.literal("invalid-input"), z.literal("timeout"), z.literal("cancelled"), z.literal("ingest-failed")]).readonly().optional(),
})
const _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_ingestUrl_parameter_0$schema = z.object({
  'url': z.string(),
})
const _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_ingestUrl_result$schema = z.object({
  'written': z.array(z.string()).readonly(),
  'warnings': z.array(z.string()).readonly(),
  'status': z.union([z.literal("error"), z.literal("ok"), z.literal("degraded")]).readonly().optional(),
  'errorCode': z.union([z.literal("invalid-input"), z.literal("timeout"), z.literal("cancelled"), z.literal("ingest-failed")]).readonly().optional(),
})
const _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_knowledgeUtility_result$schema = z.array(z.object({
  'path': z.string().readonly(),
  'retrievalHits': z.number().readonly(),
  'successfulUses': z.number().readonly(),
  'userCorrections': z.number().readonly(),
  'utilityScore': z.number().readonly(),
  'lastRetrievedAt': z.string().readonly().optional(),
  'lastOutcomeAt': z.string().readonly().optional(),
}))
const _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_lint_result$schema = z.object({
  'brokenLinks': z.array(z.object({
  'from': z.string(),
  'target': z.string(),
})),
  'emptyPages': z.array(z.string()),
  'totalPages': z.number(),
})
const _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_list_result$schema = z.array(z.object({
  'name': z.string().readonly(),
  'path': z.string().readonly(),
  'isDir': z.boolean().readonly(),
  'size': z.union([z.literal(null), z.number()]).readonly().optional(),
  'children': z.union([z.literal(null), z.array(z.lazy(() => WikiFileEntryRemoteCodec$schema))]).readonly().optional(),
}))
const _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_listProjects_result$schema = z.object({
  'projects': z.array(z.object({
  'path': z.string(),
  'name': z.string(),
  'main': z.boolean().optional(),
})),
  'current': z.string(),
})
const _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_pageContent_parameter_0$schema = z.object({
  'path': z.string(),
})
const _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_pageContent_result$schema = z.object({
  'path': z.string().readonly(),
  'content': z.string().readonly(),
})
const _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_recordKnowledgeOutcome_parameter_0$schema = z.object({
  'paths': z.array(z.string()),
  'outcome': z.union([z.literal("successful"), z.literal("corrected"), z.literal("neutral")]),
})
const _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_recordKnowledgeOutcome_result$schema = z.number()
const _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_removeProject_parameter_0$schema = z.object({
  'path': z.string(),
})
const _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_removeProject_result$schema = z.object({
  'projects': z.array(z.object({
  'path': z.string(),
  'name': z.string(),
  'main': z.boolean().optional(),
})),
  'current': z.string(),
})
const _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_resolveReview_parameter_0$schema = z.object({
  'reviewId': z.string(),
  'action': z.string().optional(),
})
const _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_resolveReview_result$schema = z.boolean()
const _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_resolveReviews_parameter_0$schema = z.object({
  'ids': z.array(z.string()),
  'action': z.string().optional(),
})
const _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_resolveReviews_result$schema = z.number()
const _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_reviews_parameter_0$schema = z.object({
  'status': z.string().optional(),
  'limit': z.number().optional(),
})
const _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_reviews_result$schema = z.array(z.object({
  'id': z.string().readonly(),
  'title': z.string().readonly(),
  'type': z.string().readonly(),
  'description': z.string().readonly().optional(),
  'sourcePath': z.string().readonly().optional(),
  'affectedPages': z.array(z.string()).readonly().optional(),
  'options': z.array(z.object({
  'action': z.string().readonly(),
  'label': z.string().readonly(),
})).readonly().optional(),
  'resolved': z.boolean().readonly(),
  'resolvedAction': z.string().readonly().optional(),
  'createdAt': z.number().readonly().optional(),
  'searchQueries': z.array(z.string()).readonly().optional(),
  'reviewKind': z.union([z.literal("advisory"), z.literal("candidate")]).readonly().optional(),
  'candidatePath': z.string().readonly().optional(),
  'candidateHash': z.string().readonly().optional(),
  'verification': z.object({
  'status': z.union([z.literal("pending"), z.literal("failed"), z.literal("passed")]).readonly(),
  'candidateHash': z.string().readonly(),
  'action': z.union([z.literal("Promote"), z.literal("Merge"), z.literal("Replace"), z.literal("Deduplicate"), z.literal("Archive")]).readonly().optional(),
  'reviewHash': z.string().readonly().optional(),
  'sourceIdentity': z.object({
  'commit': z.string().readonly(),
  'sourceDigest': z.string().readonly(),
  'dirty': z.boolean().readonly(),
  'dirtyDigest': z.string().readonly(),
  'buildDigest': z.string().readonly(),
}).readonly().optional(),
  'authorityId': z.string().readonly().optional(),
  'methods': z.array(z.union([z.literal("unit_test"), z.literal("integration_test"), z.literal("production_observation"), z.literal("manual_review")])).readonly(),
  'evidence': z.array(z.string()).readonly(),
  'receipts': z.array(z.object({
  'id': z.string().readonly(),
  'path': z.string().readonly(),
  'receiptHash': z.string().readonly(),
  'environmentHash': z.string().readonly(),
  'result': z.union([z.literal("pass"), z.literal("fail")]).readonly(),
  'gitCommit': z.string().readonly(),
})).readonly(),
  'confidence': z.number().readonly(),
  'successCount': z.number().readonly(),
  'failureCount': z.number().readonly(),
  'verifiedBy': z.union([z.literal("human"), z.literal("deterministic-executor")]).readonly().optional(),
  'lastVerifiedAt': z.string().readonly().optional(),
}).readonly().optional(),
  'targetPath': z.string().readonly().optional(),
  'appliedPath': z.string().readonly().optional(),
  'resolvedAt': z.number().readonly().optional(),
}))
const _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_search_parameter_0$schema = z.object({
  'query': z.string(),
  'topK': z.number().optional(),
})
const _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_search_result$schema = z.array(z.object({
  'path': z.string().readonly(),
  'score': z.number().readonly(),
}))
const _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_setProject_parameter_0$schema = z.object({
  'path': z.string(),
})
const _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_setProject_result$schema = z.object({
  'current': z.string(),
})
const _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_verifyCandidate_parameter_0$schema = z.object({
  'reviewId': z.string(),
  'action': z.union([z.literal("Promote"), z.literal("Merge"), z.literal("Replace"), z.literal("Deduplicate"), z.literal("Archive")]),
})
const _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_verifyCandidate_result$schema = z.object({
  'ok': z.boolean().readonly(),
  'receiptId': z.string().readonly().optional(),
  'result': z.union([z.literal("pass"), z.literal("fail")]).readonly().optional(),
  'evidence': z.array(z.string()).readonly(),
  'errorCode': z.union([z.literal("review-not-found"), z.literal("candidate-invalid"), z.literal("verifier-authority-unavailable"), z.literal("source-identity-invalid"), z.literal("verification-failed")]).readonly().optional(),
})
const _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_writePage_parameter_0$schema = z.object({
  'path': z.string(),
  'content': z.string(),
  'expectedContent': z.string().optional(),
})
const _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_writePage_result$schema = z.object({
  'path': z.string().readonly(),
  'ok': z.boolean().readonly(),
  'error': z.string().readonly().optional(),
  'conflict': z.boolean().readonly().optional(),
})

export const TYPERT = {
  package: '@deepseek-ai/dsh-knowledge-wiki',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/createPage',
      service: 'knowledgeWiki',
      namespace: 'knowledgeWiki',
      method: 'createPage',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/createPage:request',
            schema: _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_createPage_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-knowledge-wiki/types#WikiWriteResult',
        schema: _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_createPage_result$schema,
      },
      sourceLocation: {"file":"packages/host/knowledge-wiki/src/index.ts","line":770,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/createProject',
      service: 'knowledgeWiki',
      namespace: 'knowledgeWiki',
      method: 'createProject',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/createProject:request',
            schema: _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_createProject_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/createProject:result',
        schema: _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_createProject_result$schema,
      },
      sourceLocation: {"file":"packages/host/knowledge-wiki/src/index.ts","line":1343,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/deepResearch',
      service: 'knowledgeWiki',
      namespace: 'knowledgeWiki',
      method: 'deepResearch',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/deepResearch:request',
            schema: _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_deepResearch_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/deepResearch:result',
        schema: _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_deepResearch_result$schema,
      },
      sourceLocation: {"file":"packages/host/knowledge-wiki/src/index.ts","line":1108,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/exportProject',
      service: 'knowledgeWiki',
      namespace: 'knowledgeWiki',
      method: 'exportProject',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/exportProject:result',
        schema: _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_exportProject_result$schema,
      },
      sourceLocation: {"file":"packages/host/knowledge-wiki/src/index.ts","line":1500,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/fullGraph',
      service: 'knowledgeWiki',
      namespace: 'knowledgeWiki',
      method: 'fullGraph',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-knowledge-wiki/types#WikiGraphResult',
        schema: _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_fullGraph_result$schema,
      },
      sourceLocation: {"file":"packages/host/knowledge-wiki/src/index.ts","line":617,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/graph',
      service: 'knowledgeWiki',
      namespace: 'knowledgeWiki',
      method: 'graph',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-knowledge-wiki/types#WikiGraphResult',
        schema: _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_graph_result$schema,
      },
      sourceLocation: {"file":"packages/host/knowledge-wiki/src/index.ts","line":608,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/graphInsights',
      service: 'knowledgeWiki',
      namespace: 'knowledgeWiki',
      method: 'graphInsights',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/graphInsights:result',
        schema: _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_graphInsights_result$schema,
      },
      sourceLocation: {"file":"packages/host/knowledge-wiki/src/index.ts","line":1426,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/importProject',
      service: 'knowledgeWiki',
      namespace: 'knowledgeWiki',
      method: 'importProject',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/importProject:request',
            schema: _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_importProject_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/importProject:result',
        schema: _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_importProject_result$schema,
      },
      sourceLocation: {"file":"packages/host/knowledge-wiki/src/index.ts","line":1521,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/ingestQueueAdd',
      service: 'knowledgeWiki',
      namespace: 'knowledgeWiki',
      method: 'ingestQueueAdd',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/ingestQueueAdd:request',
            schema: _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_ingestQueueAdd_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-knowledge-wiki/types#IngestQueueSnapshot',
        schema: _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_ingestQueueAdd_result$schema,
      },
      sourceLocation: {"file":"packages/host/knowledge-wiki/src/index.ts","line":907,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/ingestQueueCancel',
      service: 'knowledgeWiki',
      namespace: 'knowledgeWiki',
      method: 'ingestQueueCancel',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-knowledge-wiki/types#IngestQueueSnapshot',
        schema: _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_ingestQueueCancel_result$schema,
      },
      sourceLocation: {"file":"packages/host/knowledge-wiki/src/index.ts","line":933,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/ingestQueueStatus',
      service: 'knowledgeWiki',
      namespace: 'knowledgeWiki',
      method: 'ingestQueueStatus',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-knowledge-wiki/types#IngestQueueSnapshot',
        schema: _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_ingestQueueStatus_result$schema,
      },
      sourceLocation: {"file":"packages/host/knowledge-wiki/src/index.ts","line":924,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/ingestSource',
      service: 'knowledgeWiki',
      namespace: 'knowledgeWiki',
      method: 'ingestSource',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/ingestSource:request',
            schema: _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_ingestSource_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-knowledge-wiki/types#IngestOutcome',
        schema: _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_ingestSource_result$schema,
      },
      sourceLocation: {"file":"packages/host/knowledge-wiki/src/index.ts","line":794,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/ingestUrl',
      service: 'knowledgeWiki',
      namespace: 'knowledgeWiki',
      method: 'ingestUrl',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/ingestUrl:request',
            schema: _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_ingestUrl_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-knowledge-wiki/types#IngestOutcome',
        schema: _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_ingestUrl_result$schema,
      },
      sourceLocation: {"file":"packages/host/knowledge-wiki/src/index.ts","line":875,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/knowledgeUtility',
      service: 'knowledgeWiki',
      namespace: 'knowledgeWiki',
      method: 'knowledgeUtility',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/knowledgeUtility:result',
        schema: _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_knowledgeUtility_result$schema,
      },
      sourceLocation: {"file":"packages/host/knowledge-wiki/src/index.ts","line":652,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/lint',
      service: 'knowledgeWiki',
      namespace: 'knowledgeWiki',
      method: 'lint',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/lint:result',
        schema: _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_lint_result$schema,
      },
      sourceLocation: {"file":"packages/host/knowledge-wiki/src/index.ts","line":1473,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/list',
      service: 'knowledgeWiki',
      namespace: 'knowledgeWiki',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/list:result',
        schema: _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_list_result$schema,
      },
      sourceLocation: {"file":"packages/host/knowledge-wiki/src/index.ts","line":626,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/listProjects',
      service: 'knowledgeWiki',
      namespace: 'knowledgeWiki',
      method: 'listProjects',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/listProjects:result',
        schema: _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_listProjects_result$schema,
      },
      sourceLocation: {"file":"packages/host/knowledge-wiki/src/index.ts","line":1303,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/pageContent',
      service: 'knowledgeWiki',
      namespace: 'knowledgeWiki',
      method: 'pageContent',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/pageContent:request',
            schema: _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_pageContent_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-knowledge-wiki/types#WikiPageContent',
        schema: _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_pageContent_result$schema,
      },
      sourceLocation: {"file":"packages/host/knowledge-wiki/src/index.ts","line":706,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/recordKnowledgeOutcome',
      service: 'knowledgeWiki',
      namespace: 'knowledgeWiki',
      method: 'recordKnowledgeOutcome',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/recordKnowledgeOutcome:request',
            schema: _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_recordKnowledgeOutcome_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/recordKnowledgeOutcome:result',
        schema: _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_recordKnowledgeOutcome_result$schema,
      },
      sourceLocation: {"file":"packages/host/knowledge-wiki/src/index.ts","line":663,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/removeProject',
      service: 'knowledgeWiki',
      namespace: 'knowledgeWiki',
      method: 'removeProject',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/removeProject:request',
            schema: _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_removeProject_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/removeProject:result',
        schema: _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_removeProject_result$schema,
      },
      sourceLocation: {"file":"packages/host/knowledge-wiki/src/index.ts","line":1385,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/resolveReview',
      service: 'knowledgeWiki',
      namespace: 'knowledgeWiki',
      method: 'resolveReview',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/resolveReview:request',
            schema: _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_resolveReview_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/resolveReview:result',
        schema: _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_resolveReview_result$schema,
      },
      sourceLocation: {"file":"packages/host/knowledge-wiki/src/index.ts","line":1214,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/resolveReviews',
      service: 'knowledgeWiki',
      namespace: 'knowledgeWiki',
      method: 'resolveReviews',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/resolveReviews:request',
            schema: _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_resolveReviews_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/resolveReviews:result',
        schema: _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_resolveReviews_result$schema,
      },
      sourceLocation: {"file":"packages/host/knowledge-wiki/src/index.ts","line":1242,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/reviews',
      service: 'knowledgeWiki',
      namespace: 'knowledgeWiki',
      method: 'reviews',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/reviews:request',
            schema: _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_reviews_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/reviews:result',
        schema: _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_reviews_result$schema,
      },
      sourceLocation: {"file":"packages/host/knowledge-wiki/src/index.ts","line":1156,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/search',
      service: 'knowledgeWiki',
      namespace: 'knowledgeWiki',
      method: 'search',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/search:request',
            schema: _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_search_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/search:result',
        schema: _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_search_result$schema,
      },
      sourceLocation: {"file":"packages/host/knowledge-wiki/src/index.ts","line":638,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/setProject',
      service: 'knowledgeWiki',
      namespace: 'knowledgeWiki',
      method: 'setProject',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/setProject:request',
            schema: _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_setProject_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/setProject:result',
        schema: _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_setProject_result$schema,
      },
      sourceLocation: {"file":"packages/host/knowledge-wiki/src/index.ts","line":1316,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/verifyCandidate',
      service: 'knowledgeWiki',
      namespace: 'knowledgeWiki',
      method: 'verifyCandidate',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/verifyCandidate:request',
            schema: _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_verifyCandidate_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-knowledge-wiki/types#CandidateVerificationResult',
        schema: _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_verifyCandidate_result$schema,
      },
      sourceLocation: {"file":"packages/host/knowledge-wiki/src/index.ts","line":1175,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/writePage',
      service: 'knowledgeWiki',
      namespace: 'knowledgeWiki',
      method: 'writePage',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-knowledge-wiki#knowledgeWiki/writePage:request',
            schema: _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_writePage_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-knowledge-wiki/types#WikiWriteResult',
        schema: _deepseek_ai_dsh_knowledge_wiki_knowledgeWiki_writePage_result$schema,
      },
      sourceLocation: {"file":"packages/host/knowledge-wiki/src/index.ts","line":729,"column":3},
    },
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
