/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { CandidateVerificationResult, IngestOutcome, IngestQueueSnapshot, KnowledgeUtilityRecord, WikiFileEntry, WikiGraphResult, WikiPageContent, WikiReviewItem, WikiSearchHit, WikiWriteResult } from '@deepseek-ai/dsh-knowledge-wiki/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6b6e6f776c6564676557696b69 {
    createPage: (request: { title: string; content?: string; }) => Promise<RemoteResult<WikiWriteResult>>
    createProject: (request: { name: string; path: string; }) => Promise<RemoteResult<{ path: string; error?: string; }>>
    deepResearch: (request: { topic: string; }, signal?: AbortSignal) => Promise<RemoteResult<{ findings: Array<{ title: string; path: string; }>; warnings: string[]; degraded: boolean; errorCode?: 'stage-executor-unavailable' | 'research-failed'; }>>
    exportProject: () => Promise<RemoteResult<{ path: string; error?: string; }>>
    fullGraph: () => Promise<RemoteResult<WikiGraphResult>>
    graph: () => Promise<RemoteResult<WikiGraphResult>>
    graphInsights: () => Promise<RemoteResult<{ isolated: Array<{ id: string; label: string; path: string; }>; bridges: Array<{ id: string; label: string; path: string; communities: number; }>; sparseCommunities: Array<{ id: number; nodeCount: number; topNodes: string[]; }>; }>>
    importProject: (request: { path: string; }) => Promise<RemoteResult<{ ok: boolean; error?: string; entries?: string[]; }>>
    ingestQueueAdd: (request: { inputs: string[]; }) => Promise<RemoteResult<IngestQueueSnapshot>>
    ingestQueueCancel: () => Promise<RemoteResult<IngestQueueSnapshot>>
    ingestQueueStatus: () => Promise<RemoteResult<IngestQueueSnapshot>>
    ingestSource: (request: { path: string; }) => Promise<RemoteResult<IngestOutcome>>
    ingestUrl: (request: { url: string; }) => Promise<RemoteResult<IngestOutcome>>
    knowledgeUtility: () => Promise<RemoteResult<KnowledgeUtilityRecord[]>>
    lint: () => Promise<RemoteResult<{ brokenLinks: Array<{ from: string; target: string; }>; emptyPages: string[]; totalPages: number; }>>
    list: () => Promise<RemoteResult<WikiFileEntry[]>>
    listProjects: () => Promise<RemoteResult<{ projects: Array<{ path: string; name: string; main?: boolean; }>; current: string; }>>
    pageContent: (request: { path: string; }) => Promise<RemoteResult<WikiPageContent>>
    recordKnowledgeOutcome: (request: { paths: string[]; outcome: 'successful' | 'corrected' | 'neutral'; }) => Promise<RemoteResult<number>>
    removeProject: (request: { path: string; }) => Promise<RemoteResult<{ projects: Array<{ path: string; name: string; main?: boolean; }>; current: string; }>>
    resolveReview: (request: { reviewId: string; action?: string; }) => Promise<RemoteResult<boolean>>
    resolveReviews: (request: { ids: string[]; action?: string; }) => Promise<RemoteResult<number>>
    reviews: (request: { status?: string; limit?: number; }) => Promise<RemoteResult<WikiReviewItem[]>>
    search: (request: { query: string; topK?: number; }) => Promise<RemoteResult<WikiSearchHit[]>>
    setProject: (request: { path: string; }) => Promise<RemoteResult<{ current: string; }>>
    verifyCandidate: (request: { reviewId: string; action: 'Promote' | 'Merge' | 'Replace' | 'Deduplicate' | 'Archive'; }, signal?: AbortSignal) => Promise<RemoteResult<CandidateVerificationResult>>
    writePage: (request: { path: string; content: string; expectedContent?: string; }) => Promise<RemoteResult<WikiWriteResult>>
  }
  interface TypertRemoteMap {
    'knowledgeWiki/createPage': (request: { title: string; content?: string; }) => Promise<RemoteResult<WikiWriteResult>>
    'knowledgeWiki/createProject': (request: { name: string; path: string; }) => Promise<RemoteResult<{ path: string; error?: string; }>>
    'knowledgeWiki/deepResearch': (request: { topic: string; }, signal?: AbortSignal) => Promise<RemoteResult<{ findings: Array<{ title: string; path: string; }>; warnings: string[]; degraded: boolean; errorCode?: 'stage-executor-unavailable' | 'research-failed'; }>>
    'knowledgeWiki/exportProject': () => Promise<RemoteResult<{ path: string; error?: string; }>>
    'knowledgeWiki/fullGraph': () => Promise<RemoteResult<WikiGraphResult>>
    'knowledgeWiki/graph': () => Promise<RemoteResult<WikiGraphResult>>
    'knowledgeWiki/graphInsights': () => Promise<RemoteResult<{ isolated: Array<{ id: string; label: string; path: string; }>; bridges: Array<{ id: string; label: string; path: string; communities: number; }>; sparseCommunities: Array<{ id: number; nodeCount: number; topNodes: string[]; }>; }>>
    'knowledgeWiki/importProject': (request: { path: string; }) => Promise<RemoteResult<{ ok: boolean; error?: string; entries?: string[]; }>>
    'knowledgeWiki/ingestQueueAdd': (request: { inputs: string[]; }) => Promise<RemoteResult<IngestQueueSnapshot>>
    'knowledgeWiki/ingestQueueCancel': () => Promise<RemoteResult<IngestQueueSnapshot>>
    'knowledgeWiki/ingestQueueStatus': () => Promise<RemoteResult<IngestQueueSnapshot>>
    'knowledgeWiki/ingestSource': (request: { path: string; }) => Promise<RemoteResult<IngestOutcome>>
    'knowledgeWiki/ingestUrl': (request: { url: string; }) => Promise<RemoteResult<IngestOutcome>>
    'knowledgeWiki/knowledgeUtility': () => Promise<RemoteResult<KnowledgeUtilityRecord[]>>
    'knowledgeWiki/lint': () => Promise<RemoteResult<{ brokenLinks: Array<{ from: string; target: string; }>; emptyPages: string[]; totalPages: number; }>>
    'knowledgeWiki/list': () => Promise<RemoteResult<WikiFileEntry[]>>
    'knowledgeWiki/listProjects': () => Promise<RemoteResult<{ projects: Array<{ path: string; name: string; main?: boolean; }>; current: string; }>>
    'knowledgeWiki/pageContent': (request: { path: string; }) => Promise<RemoteResult<WikiPageContent>>
    'knowledgeWiki/recordKnowledgeOutcome': (request: { paths: string[]; outcome: 'successful' | 'corrected' | 'neutral'; }) => Promise<RemoteResult<number>>
    'knowledgeWiki/removeProject': (request: { path: string; }) => Promise<RemoteResult<{ projects: Array<{ path: string; name: string; main?: boolean; }>; current: string; }>>
    'knowledgeWiki/resolveReview': (request: { reviewId: string; action?: string; }) => Promise<RemoteResult<boolean>>
    'knowledgeWiki/resolveReviews': (request: { ids: string[]; action?: string; }) => Promise<RemoteResult<number>>
    'knowledgeWiki/reviews': (request: { status?: string; limit?: number; }) => Promise<RemoteResult<WikiReviewItem[]>>
    'knowledgeWiki/search': (request: { query: string; topK?: number; }) => Promise<RemoteResult<WikiSearchHit[]>>
    'knowledgeWiki/setProject': (request: { path: string; }) => Promise<RemoteResult<{ current: string; }>>
    'knowledgeWiki/verifyCandidate': (request: { reviewId: string; action: 'Promote' | 'Merge' | 'Replace' | 'Deduplicate' | 'Archive'; }, signal?: AbortSignal) => Promise<RemoteResult<CandidateVerificationResult>>
    'knowledgeWiki/writePage': (request: { path: string; content: string; expectedContent?: string; }) => Promise<RemoteResult<WikiWriteResult>>
  }
  interface TypertRemoteNamespaceMap {
    'knowledgeWiki': TypertRemoteNamespace$6b6e6f776c6564676557696b69
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
