/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { RemoteSettingsDescription, RemoteSettingsDocumentOpenResult, RemoteSettingsJsonObject, RemoteSettingsNamespaceView, RemoteSettingsPathOp } from '@deepseek-ai/dsh-settings/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$73657474696e6773 {
    describe: () => Promise<RemoteResult<RemoteSettingsDescription>>
    mutate: (ns: string, ops: readonly RemoteSettingsPathOp[], expectedRevision?: number) => Promise<RemoteResult<RemoteSettingsNamespaceView>>
    openDocument: (signal?: AbortSignal) => Promise<RemoteResult<RemoteSettingsDocumentOpenResult>>
    replace: (ns: string, section: RemoteSettingsJsonObject, expectedRevision?: number) => Promise<RemoteResult<RemoteSettingsNamespaceView>>
    update: (ns: string, patch: RemoteSettingsJsonObject, expectedRevision?: number) => Promise<RemoteResult<RemoteSettingsNamespaceView>>
  }
  interface TypertRemoteMap {
    'settings/describe': () => Promise<RemoteResult<RemoteSettingsDescription>>
    'settings/mutate': (ns: string, ops: readonly RemoteSettingsPathOp[], expectedRevision?: number) => Promise<RemoteResult<RemoteSettingsNamespaceView>>
    'settings/openDocument': (signal?: AbortSignal) => Promise<RemoteResult<RemoteSettingsDocumentOpenResult>>
    'settings/replace': (ns: string, section: RemoteSettingsJsonObject, expectedRevision?: number) => Promise<RemoteResult<RemoteSettingsNamespaceView>>
    'settings/update': (ns: string, patch: RemoteSettingsJsonObject, expectedRevision?: number) => Promise<RemoteResult<RemoteSettingsNamespaceView>>
  }
  interface TypertRemoteNamespaceMap {
    'settings': TypertRemoteNamespace$73657474696e6773
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
