/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const RemoteSettingsJsonValueRemoteCodec$schema = z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema)), z.record(z.string(), z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema))])
const RemoteSettingsJsonValueRemoteCodec$schema2 = z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema2)), z.record(z.string(), z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema2))])
const RemoteSettingsJsonValueRemoteCodec$schema3 = z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema3)), z.record(z.string(), z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema3))])
const RemoteSettingsJsonValueRemoteCodec$schema4 = z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema4)), z.record(z.string(), z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema4))])
const RemoteSettingsJsonValueRemoteCodec$schema5 = z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema5)), z.record(z.string(), z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema5))])
const RemoteSettingsJsonValueRemoteCodec$schema6 = z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema6)), z.record(z.string(), z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema6))])
const RemoteSettingsJsonValueRemoteCodec$schema7 = z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema7)), z.record(z.string(), z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema7))])
const _deepseek_ai_dsh_settings_settings_describe_result$schema = z.object({
  'writable': z.boolean().readonly(),
  'hasDocument': z.boolean().readonly(),
  'namespaces': z.array(z.object({
  'ns': z.string().readonly(),
  'schema': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema)), z.record(z.string(), z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema))]).readonly(),
  'value': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema)), z.record(z.string(), z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema))]).readonly(),
  'base': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema)), z.record(z.string(), z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema))]).readonly().optional(),
  'user': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema)), z.record(z.string(), z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema))]).readonly().optional(),
  'applies': z.union([z.literal("live"), z.literal("restart")]).readonly(),
  'secrets': z.array(z.object({
  'path': z.array(z.string()).readonly(),
  'set': z.boolean().readonly(),
})).readonly(),
  'revision': z.number().readonly(),
})).readonly(),
})
const _deepseek_ai_dsh_settings_settings_mutate_parameter_0$schema = z.string()
const _deepseek_ai_dsh_settings_settings_mutate_parameter_1$schema = z.array(z.union([z.object({
  'op': z.literal("set").readonly(),
  'path': z.array(z.string()).readonly(),
  'value': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema7)), z.record(z.string(), z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema7))]).readonly(),
}), z.object({
  'op': z.literal("unset").readonly(),
  'path': z.array(z.string()).readonly(),
})]))
const _deepseek_ai_dsh_settings_settings_mutate_parameter_2$schema = z.union([z.undefined(), z.number()])
const _deepseek_ai_dsh_settings_settings_mutate_result$schema = z.object({
  'ns': z.string().readonly(),
  'schema': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema6)), z.record(z.string(), z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema6))]).readonly(),
  'value': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema6)), z.record(z.string(), z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema6))]).readonly(),
  'base': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema6)), z.record(z.string(), z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema6))]).readonly().optional(),
  'user': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema6)), z.record(z.string(), z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema6))]).readonly().optional(),
  'applies': z.union([z.literal("live"), z.literal("restart")]).readonly(),
  'secrets': z.array(z.object({
  'path': z.array(z.string()).readonly(),
  'set': z.boolean().readonly(),
})).readonly(),
  'revision': z.number().readonly(),
})
const _deepseek_ai_dsh_settings_settings_openDocument_result$schema = z.object({
  'opened': z.literal(true).readonly(),
})
const _deepseek_ai_dsh_settings_settings_replace_parameter_0$schema = z.string()
const _deepseek_ai_dsh_settings_settings_replace_parameter_1$schema = z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema5)), z.record(z.string(), z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema5))]))
const _deepseek_ai_dsh_settings_settings_replace_parameter_2$schema = z.union([z.undefined(), z.number()])
const _deepseek_ai_dsh_settings_settings_replace_result$schema = z.object({
  'ns': z.string().readonly(),
  'schema': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema4)), z.record(z.string(), z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema4))]).readonly(),
  'value': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema4)), z.record(z.string(), z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema4))]).readonly(),
  'base': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema4)), z.record(z.string(), z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema4))]).readonly().optional(),
  'user': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema4)), z.record(z.string(), z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema4))]).readonly().optional(),
  'applies': z.union([z.literal("live"), z.literal("restart")]).readonly(),
  'secrets': z.array(z.object({
  'path': z.array(z.string()).readonly(),
  'set': z.boolean().readonly(),
})).readonly(),
  'revision': z.number().readonly(),
})
const _deepseek_ai_dsh_settings_settings_update_parameter_0$schema = z.string()
const _deepseek_ai_dsh_settings_settings_update_parameter_1$schema = z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema2)), z.record(z.string(), z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema2))]))
const _deepseek_ai_dsh_settings_settings_update_parameter_2$schema = z.union([z.undefined(), z.number()])
const _deepseek_ai_dsh_settings_settings_update_result$schema = z.object({
  'ns': z.string().readonly(),
  'schema': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema3)), z.record(z.string(), z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema3))]).readonly(),
  'value': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema3)), z.record(z.string(), z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema3))]).readonly(),
  'base': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema3)), z.record(z.string(), z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema3))]).readonly().optional(),
  'user': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema3)), z.record(z.string(), z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema3))]).readonly().optional(),
  'applies': z.union([z.literal("live"), z.literal("restart")]).readonly(),
  'secrets': z.array(z.object({
  'path': z.array(z.string()).readonly(),
  'set': z.boolean().readonly(),
})).readonly(),
  'revision': z.number().readonly(),
})

export const TYPERT = {
  package: '@deepseek-ai/dsh-settings',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-settings#settings/describe',
      service: 'settings',
      namespace: 'settings',
      method: 'describe',
      implementation: 'remoteDescribe',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-settings/types#RemoteSettingsDescription',
        schema: _deepseek_ai_dsh_settings_settings_describe_result$schema,
      },
      sourceLocation: {"file":"packages/settings/settings/src/index.ts","line":632,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-settings#settings/mutate',
      service: 'settings',
      namespace: 'settings',
      method: 'mutate',
      implementation: 'remoteMutate',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'ns',
          wire: 'ns',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-settings#settings/mutate:ns',
            schema: _deepseek_ai_dsh_settings_settings_mutate_parameter_0$schema,
          },
        },
        {
          name: 'ops',
          wire: 'ops',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-settings#settings/mutate:ops',
            schema: _deepseek_ai_dsh_settings_settings_mutate_parameter_1$schema,
          },
        },
        {
          name: 'expectedRevision',
          wire: 'expectedRevision',
          source: 'json',
          acceptsUndefined: true,
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-settings#settings/mutate:expectedRevision',
            schema: _deepseek_ai_dsh_settings_settings_mutate_parameter_2$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-settings/types#RemoteSettingsNamespaceView',
        schema: _deepseek_ai_dsh_settings_settings_mutate_result$schema,
      },
      sourceLocation: {"file":"packages/settings/settings/src/index.ts","line":711,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-settings#settings/openDocument',
      service: 'settings',
      namespace: 'settings',
      method: 'openDocument',
      implementation: 'remoteOpenDocument',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-settings/types#RemoteSettingsDocumentOpenResult',
        schema: _deepseek_ai_dsh_settings_settings_openDocument_result$schema,
      },
      sourceLocation: {"file":"packages/settings/settings/src/index.ts","line":646,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-settings#settings/replace',
      service: 'settings',
      namespace: 'settings',
      method: 'replace',
      implementation: 'remoteReplace',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'ns',
          wire: 'ns',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-settings#settings/replace:ns',
            schema: _deepseek_ai_dsh_settings_settings_replace_parameter_0$schema,
          },
        },
        {
          name: 'section',
          wire: 'section',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-settings/types#RemoteSettingsJsonObject',
            schema: _deepseek_ai_dsh_settings_settings_replace_parameter_1$schema,
          },
        },
        {
          name: 'expectedRevision',
          wire: 'expectedRevision',
          source: 'json',
          acceptsUndefined: true,
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-settings#settings/replace:expectedRevision',
            schema: _deepseek_ai_dsh_settings_settings_replace_parameter_2$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-settings/types#RemoteSettingsNamespaceView',
        schema: _deepseek_ai_dsh_settings_settings_replace_result$schema,
      },
      sourceLocation: {"file":"packages/settings/settings/src/index.ts","line":699,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-settings#settings/update',
      service: 'settings',
      namespace: 'settings',
      method: 'update',
      implementation: 'remoteUpdate',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'ns',
          wire: 'ns',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-settings#settings/update:ns',
            schema: _deepseek_ai_dsh_settings_settings_update_parameter_0$schema,
          },
        },
        {
          name: 'patch',
          wire: 'patch',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-settings/types#RemoteSettingsJsonObject',
            schema: _deepseek_ai_dsh_settings_settings_update_parameter_1$schema,
          },
        },
        {
          name: 'expectedRevision',
          wire: 'expectedRevision',
          source: 'json',
          acceptsUndefined: true,
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-settings#settings/update:expectedRevision',
            schema: _deepseek_ai_dsh_settings_settings_update_parameter_2$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-settings/types#RemoteSettingsNamespaceView',
        schema: _deepseek_ai_dsh_settings_settings_update_result$schema,
      },
      sourceLocation: {"file":"packages/settings/settings/src/index.ts","line":687,"column":3},
    },
  ],
  model: {
    "services": [
      {
        "description": "Abstract settings service. Providers implement raw-document storage (`load`/`persist`) and push external changes through {@link Settings.publish}; the base class owns namespace registration, resolution, validation, change detection, and the `settings/updated` commit event.",
        "summary": "Abstract settings service.",
        "tags": [],
        "jsDoc": "/**\n * Abstract settings service. Providers implement raw-document storage\n * (`load`/`persist`) and push external changes through {@link Settings.publish};\n * the base class owns namespace registration, resolution, validation, change\n * detection, and the `settings/updated` commit event.\n */",
        "key": "settings",
        "exportName": "SettingsProvider",
        "members": [
          {
            "kind": "method",
            "name": "[Service.init]",
            "signature": "async* [Service.init](): AsyncGenerator<() => Promise<void> | void, void, void>",
            "summary": "Load the provider's document once and publish it before the service becomes injectable, and register the write-drain teardown.",
            "jsDoc": "/**\n * Load the provider's document once and publish it before the service\n * becomes injectable, and register the write-drain teardown. Providers with\n * their own init (watchers, connections) delegate here first via\n * `yield* super[Service.init]()`; their disposers then run before the drain.\n */"
          },
          {
            "kind": "property",
            "name": "writable",
            "signature": "abstract readonly writable: boolean",
            "summary": "Whether {@link update} may persist through this provider.",
            "jsDoc": "/** Whether {@link update} may persist through this provider. */"
          },
          {
            "kind": "getter",
            "name": "documentPath",
            "signature": "get documentPath(): string | undefined",
            "summary": "Absolute path of the provider's user-editable document, when its storage is one local file.",
            "jsDoc": "/**\n * Absolute path of the provider's user-editable document, when its storage\n * is one local file. Configuration surfaces use this only as availability\n * metadata; the guarded open operation resolves the path again Host-side.\n * Non-file providers leave it undefined and expose no open-document affordance.\n * @returns the absolute local document path, or undefined for non-file storage.\n */"
          },
          {
            "kind": "method",
            "name": "prepareDocument",
            "signature": "prepareDocument(): Promise<string | undefined>",
            "summary": "Prepare the provider's user-editable document for a native editor.",
            "jsDoc": "/**\n * Prepare the provider's user-editable document for a native editor. File\n * providers may materialize an absent document before returning its path;\n * non-file providers return undefined.\n * @returns the absolute local document path, or undefined for non-file storage.\n */"
          },
          {
            "kind": "method",
            "name": "register",
            "signature": "register<T>(ns: SettingsNamespace, schema: z<T>, options?: SettingsRegisterOptions<T>): SettingsScope<T>",
            "summary": "Register a namespace schema and receive its owner scope.",
            "jsDoc": "/**\n * Register a namespace schema and receive its owner scope. The registration\n * is an effect on the calling plugin's fiber: disposing that fiber removes\n * the namespace and its observers. An invalid stored section fails the\n * registration itself — the earliest point where the schema can judge it.\n * @param ns - unique namespace; duplicate registration fails loud.\n * @param schema - schemastery schema resolving this namespace's value.\n * @param options - composition `base` layer and effect timing.\n * @returns the owner scope for reads, observation, and updates.\n */"
          },
          {
            "kind": "method",
            "name": "describe",
            "signature": "describe(options?: SettingsDescribeOptions): SettingsDescriptor[]",
            "summary": "Describe every registered namespace for configuration surfaces, including the composition `base` and raw user layers so a form can mark which fields the user overrode (presence in `user`) and what a reset returns to.",
            "jsDoc": "/**\n * Describe every registered namespace for configuration surfaces, including\n * the composition `base` and raw user layers so a form can mark which fields\n * the user overrode (presence in `user`) and what a reset returns to.\n * @param options - redaction switch; wire surfaces must redact.\n * @returns one descriptor per registered namespace, in registration order.\n */"
          },
          {
            "kind": "method",
            "name": "remoteDescribe",
            "signature": "@Remote('describe') remoteDescribe(): RemoteSettingsDescription",
            "summary": "Read redacted settings and deployment facts without revealing a local path.",
            "jsDoc": "/**\n * Read redacted settings and deployment facts without revealing a local path.\n * @returns every registered namespace in registration order.\n */"
          },
          {
            "kind": "method",
            "name": "remoteOpenDocument",
            "signature": "@Remote('openDocument') async remoteOpenDocument(signal: AbortSignal): Promise<RemoteSettingsDocumentOpenResult>",
            "summary": "Prepare and open only the document owned by this provider.",
            "jsDoc": "/**\n * Prepare and open only the document owned by this provider.\n * @param signal - transport cancellation, including the native command.\n * @returns confirmation of the editor handoff; cancellation rejects.\n */"
          },
          {
            "kind": "method",
            "name": "remoteUpdate",
            "signature": "@Remote('update') remoteUpdate(ns: string, patch: RemoteSettingsJsonObject, expectedRevision?: number): Promise<RemoteSettingsNamespaceView>",
            "summary": "Merge fields without reconstructing a redacted section.",
            "jsDoc": "/**\n * Merge fields without reconstructing a redacted section.\n * @param ns - namespace to update.\n * @param patch - JSON fields to merge.\n * @param expectedRevision - revision read by the caller.\n * @returns the updated redacted namespace.\n */"
          },
          {
            "kind": "method",
            "name": "remoteReplace",
            "signature": "@Remote('replace') remoteReplace(ns: string, section: RemoteSettingsJsonObject, expectedRevision?: number): Promise<RemoteSettingsNamespaceView>",
            "summary": "Replace the whole user layer, removing omitted overrides.",
            "jsDoc": "/**\n * Replace the whole user layer, removing omitted overrides.\n * @param ns - namespace to replace.\n * @param section - complete new user layer, not a redacted readback.\n * @param expectedRevision - revision read by the caller.\n * @returns the updated redacted namespace.\n */"
          },
          {
            "kind": "method",
            "name": "remoteMutate",
            "signature": "@Remote('mutate') remoteMutate(ns: string, ops: readonly RemoteSettingsPathOp[], expectedRevision?: number): Promise<RemoteSettingsNamespaceView>",
            "summary": "Apply ordered edits while preserving untouched hidden fields.",
            "jsDoc": "/**\n * Apply ordered edits while preserving untouched hidden fields.\n * @param ns - namespace to mutate.\n * @param ops - path-addressed JSON edits.\n * @param expectedRevision - revision read by the caller.\n * @returns the updated redacted namespace.\n */"
          },
          {
            "kind": "method",
            "name": "setRemoteProtectedNamespaces",
            "signature": "setRemoteProtectedNamespaces(namespaces: readonly SettingsNamespace[]): void",
            "summary": "Reserve generic Remote writes for namespaces with a domain transaction owner.",
            "jsDoc": "/**\n * Reserve generic Remote writes for namespaces with a domain transaction owner.\n * @param namespaces - this calling fiber's complete protected set; other owners retain their reservations.\n */"
          },
          {
            "kind": "method",
            "name": "settle",
            "signature": "async settle(ns: SettingsNamespace, revision: number): Promise<boolean>",
            "summary": "Wait for the owner's callbacks for an exact persisted revision.",
            "jsDoc": "/**\n * Wait for the owner's callbacks for an exact persisted revision.\n * @param ns - registered namespace.\n * @param revision - exact revision to observe; superseded revisions reject.\n * @returns whether every owner callback accepted the revision, not merely whether it persisted.\n */"
          },
          {
            "kind": "method",
            "name": "get",
            "signature": "get(ns: SettingsNamespace): unknown",
            "summary": "Read one registered namespace's resolved value.",
            "jsDoc": "/**\n * Read one registered namespace's resolved value.\n * @param ns - the namespace to read.\n * @returns the resolved value, or `undefined` while unregistered.\n */"
          },
          {
            "kind": "method",
            "name": "update",
            "signature": "async update(ns: SettingsNamespace, patch: object, expectedRevision?: number): Promise<void>",
            "summary": "Merge a patch into one registered namespace's user layer, validate the resolved candidate, persist through the provider, then commit and emit.",
            "jsDoc": "/**\n * Merge a patch into one registered namespace's user layer, validate the\n * resolved candidate, persist through the provider, then commit and emit.\n * A validation failure rejects before anything is persisted. Writes to one\n * namespace are serialized: concurrent updates apply in call order, each\n * merging over the previous write's committed section.\n * @param ns - the registered namespace to update.\n * @param patch - plain-object patch over the user section.\n * @param expectedRevision - the descriptor `revision` the caller read; a\n *   namespace that moved past it rejects with {@link SettingsConflictError}.\n */"
          },
          {
            "kind": "method",
            "name": "replace",
            "signature": "async replace(ns: SettingsNamespace, section: object, expectedRevision?: number): Promise<void>",
            "summary": "Replace one registered namespace's user section wholesale, validate, persist, then commit and emit.",
            "jsDoc": "/**\n * Replace one registered namespace's user section wholesale, validate,\n * persist, then commit and emit. Keys absent from `section` fall back to the\n * composition `base` and schema defaults — this is the removal/reset path a\n * merge-only patch cannot express (`replace({})` re-inherits everything).\n * @param ns - the registered namespace to replace.\n * @param section - the complete next user section.\n * @param expectedRevision - the descriptor `revision` the caller read; a\n *   namespace that moved past it rejects with {@link SettingsConflictError}.\n */"
          },
          {
            "kind": "method",
            "name": "mutate",
            "signature": "async mutate(ns: SettingsNamespace, ops: readonly SettingsPathOp[], expectedRevision?: number): Promise<void>",
            "summary": "Apply path-addressed edits to one registered namespace's user section, validate, persist, then commit and emit.",
            "jsDoc": "/**\n * Apply path-addressed edits to one registered namespace's user section,\n * validate, persist, then commit and emit. The ops are applied to the\n * section as it stands when the write reaches the front of the queue, so a\n * caller never has to restate fields it did not touch — and, crucially,\n * cannot delete fields it never saw. This is the write path for any caller\n * holding a redacted view; `replace` remains the wholesale reset.\n * @param ns - the registered namespace to edit.\n * @param ops - ordered path edits; later ops observe earlier ones.\n * @param expectedRevision - the descriptor `revision` the caller read; a\n *   namespace that moved past it rejects with {@link SettingsConflictError}.\n */"
          },
          {
            "kind": "method",
            "name": "previewMutation",
            "signature": "previewMutation(ns: SettingsNamespace, ops: readonly SettingsPathOp[]): { secrets: RedactedSecret[] }",
            "summary": "Validate a mutation and locate its secrets before a domain owner journals it.",
            "jsDoc": "/**\n * Validate a mutation and locate its secrets before a domain owner journals it.\n * @param ns - registered namespace.\n * @param ops - proposed ordered edits; nothing is persisted.\n * @returns secret positions in the resolved candidate.\n */"
          }
        ],
        "types": [
          {
            "name": "Branded",
            "declaration": "export type Branded<B extends string> = string & { readonly [BRAND]: B; };"
          },
          {
            "name": "RedactedSecret",
            "declaration": "export interface RedactedSecret {\n    path: string[];\n    set: boolean;\n}"
          },
          {
            "name": "RedactedValue",
            "declaration": "export interface RedactedValue {\n    value: unknown;\n    secrets: RedactedSecret[];\n}"
          },
          {
            "name": "RemoteSettingsDescription",
            "declaration": "export interface RemoteSettingsDescription {\n    readonly writable: boolean;\n    readonly hasDocument: boolean;\n    readonly namespaces: readonly RemoteSettingsNamespaceView[];\n}"
          },
          {
            "name": "RemoteSettingsDocumentOpenResult",
            "declaration": "export interface RemoteSettingsDocumentOpenResult {\n    readonly opened: true;\n}"
          },
          {
            "name": "RemoteSettingsJsonObject",
            "declaration": "export interface RemoteSettingsJsonObject {\n    [key: string]: RemoteSettingsJsonValue;\n}"
          },
          {
            "name": "RemoteSettingsJsonValue",
            "declaration": "export type RemoteSettingsJsonValue = null | boolean | number | string | RemoteSettingsJsonValue[] | { [key: string]: RemoteSettingsJsonValue; };"
          },
          {
            "name": "RemoteSettingsNamespaceView",
            "declaration": "export interface RemoteSettingsNamespaceView {\n    readonly ns: string;\n    readonly schema: RemoteSettingsJsonValue;\n    readonly value: RemoteSettingsJsonValue;\n    readonly base?: RemoteSettingsJsonValue;\n    readonly user?: RemoteSettingsJsonValue;\n    readonly applies: 'live' | 'restart';\n    readonly secrets: readonly RemoteSettingsSecretView[];\n    readonly revision: number;\n}"
          },
          {
            "name": "RemoteSettingsPathOp",
            "declaration": "export type RemoteSettingsPathOp = { readonly op: 'set'; readonly path: readonly string[]; readonly value: RemoteSettingsJsonValue; } | { readonly op: 'unset'; readonly path: readonly string[]; };"
          },
          {
            "name": "RemoteSettingsSecretView",
            "declaration": "export interface RemoteSettingsSecretView {\n    readonly path: readonly string[];\n    readonly set: boolean;\n}"
          },
          {
            "name": "SettingsApplies",
            "declaration": "export type SettingsApplies = 'live' | 'restart';"
          },
          {
            "name": "SettingsDescribeOptions",
            "declaration": "export interface SettingsDescribeOptions {\n    redactSecrets?: boolean;\n}"
          },
          {
            "name": "SettingsDescriptor",
            "declaration": "export interface SettingsDescriptor {\n    ns: SettingsNamespace;\n    schema: unknown;\n    value: unknown;\n    revision: number;\n    base?: unknown;\n    user?: unknown;\n    applies: SettingsApplies;\n    secrets?: RedactedSecret[];\n}"
          },
          {
            "name": "SettingsNamespace",
            "declaration": "export type SettingsNamespace = Branded<'SettingsNamespace'>;"
          },
          {
            "name": "SettingsPathOp",
            "declaration": "export type SettingsPathOp = { op: 'set'; path: readonly string[]; value: unknown; } | { op: 'unset'; path: readonly string[]; };"
          },
          {
            "name": "SettingsRegisterOptions",
            "declaration": "export interface SettingsRegisterOptions<T> {\n    base?: Partial<T>;\n    applies?: SettingsApplies;\n    validate?: (value: T) => void;\n    validateWrite?: (value: T) => void;\n    redact?: (value: unknown) => RedactedValue;\n}"
          },
          {
            "name": "SettingsScope",
            "declaration": "export interface SettingsScope<T> {\n    get(): T;\n    watch(callback: (next: T, prev: T) => void | Promise<void>): () => void;\n    update(patch: object): Promise<void>;\n    replace(section: object): Promise<void>;\n}"
          }
        ]
      }
    ],
    "events": [
      {
        "description": "One registered namespace's RAW user section changed, whether or not the resolved value did. `settings/updated` is the consumer-facing event and stays deep-equal-gated; this one exists for configuration surfaces, which must learn that a field went from inherited to overridden (same resolved value, different meaning) and that their held revision is stale. Exact-revision settlement is bound before notification; persistence does not imply activation. Reentrant publication stops superseded revision delivery. Listener containment matches `settings/updated`.",
        "summary": "One registered namespace's RAW user section changed, whether or not the resolved value did.",
        "tags": [
          {
            "name": "param",
            "argument": "ns",
            "comment": "- the namespace whose stored section changed.",
            "text": "@param ns - the namespace whose stored section changed.\n     *"
          },
          {
            "name": "param",
            "argument": "revision",
            "comment": "- the namespace's new revision.",
            "text": "@param revision - the namespace's new revision.\n     *"
          },
          {
            "name": "mode",
            "comment": "emit",
            "text": "@mode emit"
          }
        ],
        "jsDoc": "/**\n * One registered namespace's RAW user section changed, whether or not the\n * resolved value did. `settings/updated` is the consumer-facing event and\n * stays deep-equal-gated; this one exists for configuration surfaces,\n * which must learn that a field went from inherited to overridden (same\n * resolved value, different meaning) and that their held revision is\n * stale. Exact-revision settlement is bound before notification; persistence\n * does not imply activation. Reentrant publication stops superseded revision\n * delivery. Listener containment matches `settings/updated`.\n * @param ns - the namespace whose stored section changed.\n * @param revision - the namespace's new revision.\n * @mode emit\n */",
        "name": "settings/document-updated",
        "mode": "emit",
        "signature": "'settings/document-updated'(ns: SettingsNamespace, revision: number): void"
      },
      {
        "description": "Committed change to one registered namespace's resolved value. Emitted after the provider persisted (for `update`) or published (`provider`) the change; never emitted when the resolved value is deep-equal. Listener failures are contained and logged — a sync throw and an async rejection alike — except `INVARIANT`-coded failures, which rethrow after fan-out; reentrant publication stops delivery of superseded values. That rethrow reaches the emitter only from synchronous listeners, so invariant checks on this event must not be async functions.",
        "summary": "Committed change to one registered namespace's resolved value.",
        "tags": [
          {
            "name": "param",
            "argument": "ns",
            "comment": "- the namespace whose resolved value changed.",
            "text": "@param ns - the namespace whose resolved value changed.\n     *"
          },
          {
            "name": "param",
            "argument": "next",
            "comment": "- the new resolved value.",
            "text": "@param next - the new resolved value.\n     *"
          },
          {
            "name": "param",
            "argument": "prev",
            "comment": "- the previous resolved value.",
            "text": "@param prev - the previous resolved value.\n     *"
          },
          {
            "name": "param",
            "argument": "source",
            "comment": "- whether the change entered through `update()` or the provider.",
            "text": "@param source - whether the change entered through `update()` or the provider.\n     *"
          },
          {
            "name": "mode",
            "comment": "emit",
            "text": "@mode emit"
          }
        ],
        "jsDoc": "/**\n * Committed change to one registered namespace's resolved value. Emitted\n * after the provider persisted (for `update`) or published (`provider`)\n * the change; never emitted when the resolved value is deep-equal.\n * Listener failures are contained and logged — a sync throw and an async\n * rejection alike — except `INVARIANT`-coded failures, which rethrow\n * after fan-out; reentrant publication stops delivery of superseded values.\n * That rethrow reaches the emitter only from\n * synchronous listeners, so invariant checks on this event must not be\n * async functions.\n * @param ns - the namespace whose resolved value changed.\n * @param next - the new resolved value.\n * @param prev - the previous resolved value.\n * @param source - whether the change entered through `update()` or the provider.\n * @mode emit\n */",
        "name": "settings/updated",
        "mode": "emit",
        "signature": "'settings/updated'(ns: SettingsNamespace, next: unknown, prev: unknown, source: SettingsUpdateSource): void"
      }
    ],
    "objects": []
  },
}
