/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { WorkspaceRemoteArchivedValue, WorkspaceRemoteArchiveRequest, WorkspaceRemoteCreateRequest, WorkspaceRemoteCreateValue, WorkspaceRemoteDeleteArchivedRequest, WorkspaceRemoteDeleteArchivedValue, WorkspaceRemoteDeletedValue, WorkspaceRemoteDeleteRequest, WorkspaceRemoteInsertBeforeRequest, WorkspaceRemoteInsertSessionBeforeRequest, WorkspaceRemoteListValue, WorkspaceRemoteOrderValue, WorkspaceRemoteRenameRequest, WorkspaceRemoteResult, WorkspaceRemoteWorkspaceValue } from '@deepseek-ai/dsh-workspace/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$776f726b7370616365 {
    archiveSession: (request: WorkspaceRemoteArchiveRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkspaceRemoteResult<WorkspaceRemoteArchivedValue>>>
    create: (request: WorkspaceRemoteCreateRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkspaceRemoteResult<WorkspaceRemoteCreateValue>>>
    delete: (request: WorkspaceRemoteDeleteRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkspaceRemoteResult<WorkspaceRemoteDeletedValue>>>
    deleteArchivedSession: (request: WorkspaceRemoteDeleteArchivedRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkspaceRemoteResult<WorkspaceRemoteDeleteArchivedValue>>>
    insertBefore: (request: WorkspaceRemoteInsertBeforeRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkspaceRemoteResult<WorkspaceRemoteOrderValue>>>
    insertSessionBefore: (request: WorkspaceRemoteInsertSessionBeforeRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkspaceRemoteResult<WorkspaceRemoteWorkspaceValue>>>
    list: (signal?: AbortSignal) => Promise<RemoteResult<WorkspaceRemoteResult<WorkspaceRemoteListValue>>>
    rename: (request: WorkspaceRemoteRenameRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkspaceRemoteResult<WorkspaceRemoteWorkspaceValue>>>
    unarchiveSession: (request: WorkspaceRemoteArchiveRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkspaceRemoteResult<WorkspaceRemoteArchivedValue>>>
  }
  interface TypertRemoteMap {
    'workspace/archiveSession': (request: WorkspaceRemoteArchiveRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkspaceRemoteResult<WorkspaceRemoteArchivedValue>>>
    'workspace/create': (request: WorkspaceRemoteCreateRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkspaceRemoteResult<WorkspaceRemoteCreateValue>>>
    'workspace/delete': (request: WorkspaceRemoteDeleteRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkspaceRemoteResult<WorkspaceRemoteDeletedValue>>>
    'workspace/deleteArchivedSession': (request: WorkspaceRemoteDeleteArchivedRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkspaceRemoteResult<WorkspaceRemoteDeleteArchivedValue>>>
    'workspace/insertBefore': (request: WorkspaceRemoteInsertBeforeRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkspaceRemoteResult<WorkspaceRemoteOrderValue>>>
    'workspace/insertSessionBefore': (request: WorkspaceRemoteInsertSessionBeforeRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkspaceRemoteResult<WorkspaceRemoteWorkspaceValue>>>
    'workspace/list': (signal?: AbortSignal) => Promise<RemoteResult<WorkspaceRemoteResult<WorkspaceRemoteListValue>>>
    'workspace/rename': (request: WorkspaceRemoteRenameRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkspaceRemoteResult<WorkspaceRemoteWorkspaceValue>>>
    'workspace/unarchiveSession': (request: WorkspaceRemoteArchiveRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkspaceRemoteResult<WorkspaceRemoteArchivedValue>>>
  }
  interface TypertRemoteNamespaceMap {
    'workspace': TypertRemoteNamespace$776f726b7370616365
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
