/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_workspace_workspace_archiveSession_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_workspace_workspace_archiveSession_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.string().readonly(),
  'message': z.string().readonly(),
  'details': z.record(z.string(), z.string()).readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'archivedSessionIds': z.array(z.intersection(z.string(), z.unknown())).readonly(),
}).readonly(),
})])
const _deepseek_ai_dsh_workspace_workspace_create_parameter_0$schema = z.object({
  'path': z.string().readonly(),
})
const _deepseek_ai_dsh_workspace_workspace_create_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.string().readonly(),
  'message': z.string().readonly(),
  'details': z.record(z.string(), z.string()).readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'workspace': z.object({
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
  'path': z.string().readonly(),
  'title': z.string().readonly(),
  'sessionIds': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
}).readonly(),
  'created': z.boolean().readonly(),
}).readonly(),
})])
const _deepseek_ai_dsh_workspace_workspace_delete_parameter_0$schema = z.object({
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_workspace_workspace_delete_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.string().readonly(),
  'message': z.string().readonly(),
  'details': z.record(z.string(), z.string()).readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'deleted': z.literal(true).readonly(),
}).readonly(),
})])
const _deepseek_ai_dsh_workspace_workspace_deleteArchivedSession_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_workspace_workspace_deleteArchivedSession_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.string().readonly(),
  'message': z.string().readonly(),
  'details': z.record(z.string(), z.string()).readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'deleted': z.literal(true).readonly(),
  'archivedSessionIds': z.array(z.intersection(z.string(), z.unknown())).readonly(),
}).readonly(),
})])
const _deepseek_ai_dsh_workspace_workspace_insertBefore_parameter_0$schema = z.object({
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
  'beforeWorkspaceId': z.intersection(z.string(), z.unknown()).readonly().optional(),
})
const _deepseek_ai_dsh_workspace_workspace_insertBefore_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.string().readonly(),
  'message': z.string().readonly(),
  'details': z.record(z.string(), z.string()).readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'workspaceIds': z.array(z.intersection(z.string(), z.unknown())).readonly(),
}).readonly(),
})])
const _deepseek_ai_dsh_workspace_workspace_insertSessionBefore_parameter_0$schema = z.object({
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'beforeSessionId': z.intersection(z.string(), z.unknown()).readonly().optional(),
})
const _deepseek_ai_dsh_workspace_workspace_insertSessionBefore_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.string().readonly(),
  'message': z.string().readonly(),
  'details': z.record(z.string(), z.string()).readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'workspace': z.object({
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
  'path': z.string().readonly(),
  'title': z.string().readonly(),
  'sessionIds': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
}).readonly(),
}).readonly(),
})])
const _deepseek_ai_dsh_workspace_workspace_list_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.string().readonly(),
  'message': z.string().readonly(),
  'details': z.record(z.string(), z.string()).readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'items': z.array(z.object({
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
  'path': z.string().readonly(),
  'title': z.string().readonly(),
  'sessionIds': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
})).readonly(),
  'archivedSessionIds': z.array(z.intersection(z.string(), z.unknown())).readonly(),
}).readonly(),
})])
const _deepseek_ai_dsh_workspace_workspace_rename_parameter_0$schema = z.object({
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
})
const _deepseek_ai_dsh_workspace_workspace_rename_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.string().readonly(),
  'message': z.string().readonly(),
  'details': z.record(z.string(), z.string()).readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'workspace': z.object({
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
  'path': z.string().readonly(),
  'title': z.string().readonly(),
  'sessionIds': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
}).readonly(),
}).readonly(),
})])
const _deepseek_ai_dsh_workspace_workspace_unarchiveSession_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_workspace_workspace_unarchiveSession_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.string().readonly(),
  'message': z.string().readonly(),
  'details': z.record(z.string(), z.string()).readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'archivedSessionIds': z.array(z.intersection(z.string(), z.unknown())).readonly(),
}).readonly(),
})])

export const TYPERT = {
  package: '@deepseek-ai/dsh-workspace',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-workspace#workspace/archiveSession',
      service: 'workspaceRegistry',
      namespace: 'workspace',
      method: 'archiveSession',
      implementation: 'remoteExportArchiveSession',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-workspace/types#WorkspaceRemoteArchiveRequest',
            schema: _deepseek_ai_dsh_workspace_workspace_archiveSession_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-workspace/types#WorkspaceRemoteResult',
        schema: _deepseek_ai_dsh_workspace_workspace_archiveSession_result$schema,
      },
      sourceLocation: {"file":"packages/workspace/workspace/src/index.ts","line":432,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-workspace#workspace/create',
      service: 'workspaceRegistry',
      namespace: 'workspace',
      method: 'create',
      implementation: 'remoteExportCreate',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-workspace/types#WorkspaceRemoteCreateRequest',
            schema: _deepseek_ai_dsh_workspace_workspace_create_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-workspace/types#WorkspaceRemoteResult',
        schema: _deepseek_ai_dsh_workspace_workspace_create_result$schema,
      },
      sourceLocation: {"file":"packages/workspace/workspace/src/index.ts","line":345,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-workspace#workspace/delete',
      service: 'workspaceRegistry',
      namespace: 'workspace',
      method: 'delete',
      implementation: 'remoteExportDelete',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-workspace/types#WorkspaceRemoteDeleteRequest',
            schema: _deepseek_ai_dsh_workspace_workspace_delete_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-workspace/types#WorkspaceRemoteResult',
        schema: _deepseek_ai_dsh_workspace_workspace_delete_result$schema,
      },
      sourceLocation: {"file":"packages/workspace/workspace/src/index.ts","line":383,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-workspace#workspace/deleteArchivedSession',
      service: 'workspaceRegistry',
      namespace: 'workspace',
      method: 'deleteArchivedSession',
      implementation: 'remoteExportDeleteArchivedSession',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-workspace/types#WorkspaceRemoteDeleteArchivedRequest',
            schema: _deepseek_ai_dsh_workspace_workspace_deleteArchivedSession_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-workspace/types#WorkspaceRemoteResult',
        schema: _deepseek_ai_dsh_workspace_workspace_deleteArchivedSession_result$schema,
      },
      sourceLocation: {"file":"packages/workspace/workspace/src/index.ts","line":464,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-workspace#workspace/insertBefore',
      service: 'workspaceRegistry',
      namespace: 'workspace',
      method: 'insertBefore',
      implementation: 'remoteExportInsertBefore',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-workspace/types#WorkspaceRemoteInsertBeforeRequest',
            schema: _deepseek_ai_dsh_workspace_workspace_insertBefore_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-workspace/types#WorkspaceRemoteResult',
        schema: _deepseek_ai_dsh_workspace_workspace_insertBefore_result$schema,
      },
      sourceLocation: {"file":"packages/workspace/workspace/src/index.ts","line":399,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-workspace#workspace/insertSessionBefore',
      service: 'workspaceRegistry',
      namespace: 'workspace',
      method: 'insertSessionBefore',
      implementation: 'remoteExportInsertSessionBefore',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-workspace/types#WorkspaceRemoteInsertSessionBeforeRequest',
            schema: _deepseek_ai_dsh_workspace_workspace_insertSessionBefore_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-workspace/types#WorkspaceRemoteResult',
        schema: _deepseek_ai_dsh_workspace_workspace_insertSessionBefore_result$schema,
      },
      sourceLocation: {"file":"packages/workspace/workspace/src/index.ts","line":414,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-workspace#workspace/list',
      service: 'workspaceRegistry',
      namespace: 'workspace',
      method: 'list',
      implementation: 'remoteExportList',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-workspace/types#WorkspaceRemoteResult',
        schema: _deepseek_ai_dsh_workspace_workspace_list_result$schema,
      },
      sourceLocation: {"file":"packages/workspace/workspace/src/index.ts","line":333,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-workspace#workspace/rename',
      service: 'workspaceRegistry',
      namespace: 'workspace',
      method: 'rename',
      implementation: 'remoteExportRename',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-workspace/types#WorkspaceRemoteRenameRequest',
            schema: _deepseek_ai_dsh_workspace_workspace_rename_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-workspace/types#WorkspaceRemoteResult',
        schema: _deepseek_ai_dsh_workspace_workspace_rename_result$schema,
      },
      sourceLocation: {"file":"packages/workspace/workspace/src/index.ts","line":368,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-workspace#workspace/unarchiveSession',
      service: 'workspaceRegistry',
      namespace: 'workspace',
      method: 'unarchiveSession',
      implementation: 'remoteExportUnarchiveSession',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-workspace/types#WorkspaceRemoteArchiveRequest',
            schema: _deepseek_ai_dsh_workspace_workspace_unarchiveSession_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-workspace/types#WorkspaceRemoteResult',
        schema: _deepseek_ai_dsh_workspace_workspace_unarchiveSession_result$schema,
      },
      sourceLocation: {"file":"packages/workspace/workspace/src/index.ts","line":448,"column":3},
    },
  ],
  model: {
    "services": [
      {
        "description": "Durable workspace registry. Startup waits for `sessionPersistence`, builds one canonical-cwd header index, and completes the one-time history bootstrap before the service becomes active. The persistence dependency is mandatory so an unavailable peer can never be mistaken for an empty history and commit the initialized marker.",
        "summary": "Durable workspace registry.",
        "tags": [],
        "jsDoc": "/**\n * Durable workspace registry. Startup waits for `sessionPersistence`, builds\n * one canonical-cwd header index, and completes the one-time history\n * bootstrap before the service becomes active. The persistence dependency is\n * mandatory so an unavailable peer can never be mistaken for an empty\n * history and commit the initialized marker.\n */",
        "key": "workspaceRegistry",
        "exportName": "WorkspaceRegistry",
        "members": [
          {
            "kind": "method",
            "name": "create",
            "signature": "async create(path: string, title?: string): Promise<Workspace>",
            "summary": "Create or reuse a workspace for an existing directory.",
            "jsDoc": "/**\n * Create or reuse a workspace for an existing directory. The path is\n * canonicalized through `fs.realpath`; a nonexistent path rejects with the\n * original error and a non-directory rejects. Repeated calls for the same\n * canonical path return the existing entity without changing its title.\n * A newly created workspace is prepended to the durable registry order.\n * Different canonical paths may share a display title.\n * @param path - Existing directory to own, in any path spelling.\n * @param title - Display title used only when a new record is created.\n * @returns the existing or newly durable workspace.\n */"
          },
          {
            "kind": "method",
            "name": "createOrResolve",
            "signature": "async createOrResolve(path: string, title?: string): Promise<{ workspace: Workspace; created: boolean }>",
            "summary": "Resolve canonical ownership and creation status in the same serialized operation.",
            "jsDoc": "/**\n * Resolve canonical ownership and creation status in the same serialized operation.\n * @param path - existing directory.\n * @param title - initial title when a record is created.\n * @returns workspace and whether this operation created it.\n */"
          },
          {
            "kind": "method",
            "name": "get",
            "signature": "get(id: WorkspaceId): Workspace | undefined",
            "summary": "Look up a workspace by id.",
            "jsDoc": "/**\n * Look up a workspace by id.\n * @param id - Workspace id.\n * @returns the workspace, or `undefined` when unknown.\n */"
          },
          {
            "kind": "method",
            "name": "list",
            "signature": "list(): Workspace[]",
            "summary": "Synchronous workspace projection in durable registry order.",
            "jsDoc": "/**\n * Synchronous workspace projection in durable registry order. Every\n * entity's `sessionIds` getter is already filtered by the startup/live\n * canonical-cwd header index; this method performs no persistence reads.\n * @returns a fresh ordered array of workspace entities.\n */"
          },
          {
            "kind": "method",
            "name": "remoteExportList",
            "signature": "@Remote('list') remoteExportList(signal: AbortSignal): WorkspaceRemoteResult<WorkspaceRemoteListValue>",
            "summary": "Project the native workspace list without persistence reads.",
            "jsDoc": "/**\n * Project the native workspace list without persistence reads.\n * @param signal - request cancellation.\n * @returns durable rows and archive overlay.\n */"
          },
          {
            "kind": "method",
            "name": "remoteExportCreate",
            "signature": "@Remote('create') async remoteExportCreate( request: WorkspaceRemoteCreateRequest, signal: AbortSignal, ): Promise<WorkspaceRemoteResult<WorkspaceRemoteCreateValue>>",
            "summary": "Create or resolve a workspace registration through the native API.",
            "jsDoc": "/**\n * Create or resolve a workspace registration through the native API.\n * @param request - existing directory to own.\n * @param signal - cancellation.\n * @returns row and atomic creation flag.\n */"
          },
          {
            "kind": "method",
            "name": "remoteExportRename",
            "signature": "@Remote('rename') remoteExportRename( request: WorkspaceRemoteRenameRequest, signal: AbortSignal, ): Promise<WorkspaceRemoteResult<WorkspaceRemoteWorkspaceValue>>",
            "summary": "Rename a registered workspace through the native API.",
            "jsDoc": "/**\n * Rename a registered workspace through the native API.\n * @param request - workspace and replacement title.\n * @param signal - cancellation.\n * @returns renamed row.\n */"
          },
          {
            "kind": "method",
            "name": "remoteExportDelete",
            "signature": "@Remote('delete') remoteExportDelete( request: WorkspaceRemoteDeleteRequest, signal: AbortSignal, ): Promise<WorkspaceRemoteResult<WorkspaceRemoteDeletedValue>>",
            "summary": "Remove a workspace registration without deleting files or session logs.",
            "jsDoc": "/**\n * Remove a workspace registration without deleting files or session logs.\n * @param request - registration to remove.\n * @param signal - cancellation.\n * @returns confirmation; files and logs remain.\n */"
          },
          {
            "kind": "method",
            "name": "remoteExportInsertBefore",
            "signature": "@Remote('insertBefore') remoteExportInsertBefore( request: WorkspaceRemoteInsertBeforeRequest, signal: AbortSignal, ): Promise<WorkspaceRemoteResult<WorkspaceRemoteOrderValue>>",
            "summary": "Reorder a workspace through the native API.",
            "jsDoc": "/**\n * Reorder a workspace through the native API.\n * @param request - workspace and optional anchor.\n * @param signal - cancellation.\n * @returns durable order.\n */"
          },
          {
            "kind": "method",
            "name": "remoteExportInsertSessionBefore",
            "signature": "@Remote('insertSessionBefore') remoteExportInsertSessionBefore( request: WorkspaceRemoteInsertSessionBeforeRequest, signal: AbortSignal, ): Promise<WorkspaceRemoteResult<WorkspaceRemoteWorkspaceValue>>",
            "summary": "Reorder a session within its workspace account.",
            "jsDoc": "/**\n * Reorder a session within its workspace account.\n * @param request - workspace, session and optional anchor.\n * @param signal - cancellation.\n * @returns updated account.\n */"
          },
          {
            "kind": "method",
            "name": "remoteExportArchiveSession",
            "signature": "@Remote('archiveSession') remoteExportArchiveSession( request: WorkspaceRemoteArchiveRequest, signal: AbortSignal, ): Promise<WorkspaceRemoteResult<WorkspaceRemoteArchivedValue>>",
            "summary": "Archive a session through the native API while retaining its log.",
            "jsDoc": "/**\n * Archive a session through the native API while retaining its log.\n * @param request - session to archive.\n * @param signal - cancellation.\n * @returns committed archive overlay.\n */"
          },
          {
            "kind": "method",
            "name": "remoteExportUnarchiveSession",
            "signature": "@Remote('unarchiveSession') remoteExportUnarchiveSession( request: WorkspaceRemoteArchiveRequest, signal: AbortSignal, ): Promise<WorkspaceRemoteResult<WorkspaceRemoteArchivedValue>>",
            "summary": "Restore an archived session to the visible workspace projection.",
            "jsDoc": "/**\n * Restore an archived session to the visible workspace projection.\n * @param request - archived session to restore.\n * @param signal - cancellation.\n * @returns committed archive overlay.\n */"
          },
          {
            "kind": "method",
            "name": "remoteExportDeleteArchivedSession",
            "signature": "@Remote('deleteArchivedSession') remoteExportDeleteArchivedSession( request: WorkspaceRemoteDeleteArchivedRequest, signal: AbortSignal, ): Promise<WorkspaceRemoteResult<WorkspaceRemoteDeleteArchivedValue>>",
            "summary": "Permanently delete an archived root through its existing lifecycle owners.",
            "jsDoc": "/**\n * Permanently delete an archived root through its existing lifecycle owners.\n * @param request - archived root to delete.\n * @param signal - cancellation.\n * @returns deletion and archive state.\n */"
          },
          {
            "kind": "method",
            "name": "rename",
            "signature": "rename(id: WorkspaceId, title: string): Promise<Workspace>",
            "summary": "Persist a non-empty, unique workspace title before publishing it.",
            "jsDoc": "/**\n * Persist a non-empty, unique workspace title before publishing it.\n * @param id - registered workspace.\n * @param title - visible replacement title.\n * @returns renamed workspace after durability.\n */"
          },
          {
            "kind": "method",
            "name": "delete",
            "signature": "delete(id: WorkspaceId): Promise<boolean>",
            "summary": "Delete one workspace registration while retaining its directory and every session log.",
            "jsDoc": "/**\n * Delete one workspace registration while retaining its directory and every\n * session log. The durable order is updated before the table deletion; a\n * failed table write restores the prior order and keeps the entity\n * published. Unknown ids are an idempotent no-op for domain callers.\n * @param id - Workspace registration to remove.\n * @returns `true` when a record was deleted, `false` when it was unknown.\n */"
          },
          {
            "kind": "method",
            "name": "insertBefore",
            "signature": "insertBefore(id: WorkspaceId, beforeId?: WorkspaceId): Promise<readonly WorkspaceId[]>",
            "summary": "Move one workspace within the durable display order, DOM-insertBefore-like.",
            "jsDoc": "/**\n * Move one workspace within the durable display order, DOM-insertBefore-like.\n * With an anchor it lands before that workspace; without one it appends.\n * @param id - Workspace to move.\n * @param beforeId - Workspace anchor; omitted appends.\n * @returns the complete committed workspace order.\n */"
          },
          {
            "kind": "getter",
            "name": "archivedSessionIds",
            "signature": "get archivedSessionIds(): readonly SessionId[]",
            "summary": "The registry-global archive set: sessions hidden from every grouping surface.",
            "jsDoc": "/**\n * The registry-global archive set: sessions hidden from every grouping\n * surface. Archiving never touches workspace accounting — an archived\n * session keeps its `sessionIds` slot so unarchiving restores its position.\n * @returns the archived session ids in archive order.\n */"
          },
          {
            "kind": "method",
            "name": "sessionAdmissionRevision",
            "signature": "sessionAdmissionRevision(sessionId: SessionId): number",
            "summary": "Capture the deletion generation before asynchronously loading a session.",
            "jsDoc": "/**\n * Capture the deletion generation before asynchronously loading a session.\n * @param sessionId - identity to observe.\n * @returns its in-process permanent-deletion generation.\n */"
          },
          {
            "kind": "method",
            "name": "assertSessionAdmission",
            "signature": "assertSessionAdmission(sessionId: SessionId, revision: number): void",
            "summary": "Reject publication while a session is archived or its deletion raced the load.",
            "jsDoc": "/**\n * Reject publication while a session is archived or its deletion raced the load.\n * @param sessionId - identity being published.\n * @param revision - generation captured before asynchronous work.\n */"
          },
          {
            "kind": "method",
            "name": "archiveSession",
            "signature": "archiveSession(sessionId: SessionId): Promise<void>",
            "summary": "Archive one session durably.",
            "jsDoc": "/**\n * Archive one session durably. The session must exist (live or in session\n * persistence); its workspace accounting — or lack of one — is irrelevant.\n * An already archived id resolves without writing.\n * @param sessionId - The session to archive.\n * @returns resolution after durability.\n */"
          },
          {
            "kind": "method",
            "name": "unarchiveSession",
            "signature": "unarchiveSession(sessionId: SessionId): Promise<void>",
            "summary": "Remove a known session from the durable archive overlay.",
            "jsDoc": "/**\n * Remove a known session from the durable archive overlay.\n * @param sessionId - archived identity to restore.\n * @returns settlement after durable archive removal.\n */"
          },
          {
            "kind": "method",
            "name": "deleteArchivedSession",
            "signature": "deleteArchivedSession(sessionId: SessionId, retireResident?: (residentSessionId: SessionId) => Promise<void>): Promise<void>",
            "summary": "Delete an archived root and retained descendants before committing account and archive removal.",
            "jsDoc": "/**\n * Delete an archived root and retained descendants before committing account and archive removal.\n * @param sessionId - archived root identity.\n * @param retireResident - exact lifecycle owner used to retire resident sessions.\n * @returns settlement after logs, derived cleanup, accounts and archive state commit.\n */"
          },
          {
            "kind": "method",
            "name": "resolveByPath",
            "signature": "async resolveByPath(path: string): Promise<Workspace | undefined>",
            "summary": "Resolve by canonical directory path without creating or mutating a workspace.",
            "jsDoc": "/**\n * Resolve by canonical directory path without creating or mutating a\n * workspace. A missing path rejects during `realpath`; an existing unowned\n * directory returns `undefined`.\n * @param path - Existing directory path in any spelling.\n * @returns the workspace owning the canonical path, when one exists.\n */"
          }
        ],
        "types": [
          {
            "name": "Branded",
            "declaration": "export type Branded<B extends string> = string & { readonly [BRAND]: B; };"
          },
          {
            "name": "SessionId",
            "declaration": "export type SessionId = Branded<'SessionId'>;"
          },
          {
            "name": "Workspace",
            "declaration": "export interface Workspace {\n    readonly id: WorkspaceId;\n    readonly path: string;\n    readonly title: string;\n    readonly createdAt: string;\n    readonly updatedAt: string;\n    readonly sessionIds: readonly SessionId[];\n    setTitle(title: string): Promise<void>;\n    attachSession(sessionId: SessionId): Promise<void>;\n    insertSessionBefore(sessionId: SessionId, beforeSessionId?: SessionId): Promise<void>;\n    detachSession(sessionId: SessionId): Promise<void>;\n    status(): Promise<'ok' | 'missing-dir'>;\n}"
          },
          {
            "name": "WorkspaceId",
            "declaration": "export type WorkspaceId = WorkspaceIdBrand;"
          },
          {
            "name": "WorkspaceId",
            "declaration": "export type WorkspaceId = Branded<'WorkspaceId'>;"
          },
          {
            "name": "WorkspaceRemoteArchivedValue",
            "declaration": "export interface WorkspaceRemoteArchivedValue {\n    readonly archivedSessionIds: readonly SessionId[];\n}"
          },
          {
            "name": "WorkspaceRemoteArchiveRequest",
            "declaration": "export interface WorkspaceRemoteArchiveRequest {\n    readonly sessionId: SessionId;\n}"
          },
          {
            "name": "WorkspaceRemoteCreateRequest",
            "declaration": "export interface WorkspaceRemoteCreateRequest {\n    readonly path: string;\n}"
          },
          {
            "name": "WorkspaceRemoteCreateValue",
            "declaration": "export interface WorkspaceRemoteCreateValue {\n    readonly workspace: WorkspaceRemoteView;\n    readonly created: boolean;\n}"
          },
          {
            "name": "WorkspaceRemoteDeleteArchivedRequest",
            "declaration": "export interface WorkspaceRemoteDeleteArchivedRequest {\n    readonly sessionId: SessionId;\n}"
          },
          {
            "name": "WorkspaceRemoteDeleteArchivedValue",
            "declaration": "export interface WorkspaceRemoteDeleteArchivedValue {\n    readonly deleted: true;\n    readonly archivedSessionIds: readonly SessionId[];\n}"
          },
          {
            "name": "WorkspaceRemoteDeletedValue",
            "declaration": "export interface WorkspaceRemoteDeletedValue {\n    readonly deleted: true;\n}"
          },
          {
            "name": "WorkspaceRemoteDeleteRequest",
            "declaration": "export interface WorkspaceRemoteDeleteRequest {\n    readonly workspaceId: WorkspaceId;\n}"
          },
          {
            "name": "WorkspaceRemoteFailure",
            "declaration": "export interface WorkspaceRemoteFailure {\n    readonly ok: false;\n    readonly error: { readonly code: string; readonly message: string; readonly details: Record<string, string>; };\n}"
          },
          {
            "name": "WorkspaceRemoteInsertBeforeRequest",
            "declaration": "export interface WorkspaceRemoteInsertBeforeRequest {\n    readonly workspaceId: WorkspaceId;\n    readonly beforeWorkspaceId?: WorkspaceId;\n}"
          },
          {
            "name": "WorkspaceRemoteInsertSessionBeforeRequest",
            "declaration": "export interface WorkspaceRemoteInsertSessionBeforeRequest {\n    readonly workspaceId: WorkspaceId;\n    readonly sessionId: SessionId;\n    readonly beforeSessionId?: SessionId;\n}"
          },
          {
            "name": "WorkspaceRemoteListValue",
            "declaration": "export interface WorkspaceRemoteListValue {\n    readonly items: readonly WorkspaceRemoteView[];\n    readonly archivedSessionIds: readonly SessionId[];\n}"
          },
          {
            "name": "WorkspaceRemoteOrderValue",
            "declaration": "export interface WorkspaceRemoteOrderValue {\n    readonly workspaceIds: readonly WorkspaceId[];\n}"
          },
          {
            "name": "WorkspaceRemoteRenameRequest",
            "declaration": "export interface WorkspaceRemoteRenameRequest {\n    readonly workspaceId: WorkspaceId;\n    readonly title: string;\n}"
          },
          {
            "name": "WorkspaceRemoteResult",
            "declaration": "export type WorkspaceRemoteResult<Value> = WorkspaceRemoteSuccess<Value> | WorkspaceRemoteFailure;"
          },
          {
            "name": "WorkspaceRemoteSuccess",
            "declaration": "export interface WorkspaceRemoteSuccess<Value> {\n    readonly ok: true;\n    readonly value: Value;\n}"
          },
          {
            "name": "WorkspaceRemoteView",
            "declaration": "export interface WorkspaceRemoteView {\n    readonly workspaceId: WorkspaceId;\n    readonly path: string;\n    readonly title: string;\n    readonly sessionIds: readonly SessionId[];\n    readonly createdAt: string;\n    readonly updatedAt: string;\n}"
          },
          {
            "name": "WorkspaceRemoteWorkspaceValue",
            "declaration": "export interface WorkspaceRemoteWorkspaceValue {\n    readonly workspace: WorkspaceRemoteView;\n}"
          }
        ]
      }
    ],
    "events": [
      {
        "description": "Committed archive overlay after a non-delete mutation.",
        "summary": "Committed archive overlay after a non-delete mutation.",
        "tags": [
          {
            "name": "param",
            "argument": "archivedSessionIds",
            "comment": "- current archive identities in durable order.",
            "text": "@param archivedSessionIds - current archive identities in durable order.\n     *"
          },
          {
            "name": "mode",
            "comment": "emit",
            "text": "@mode emit"
          }
        ],
        "jsDoc": "/**\n * Committed archive overlay after a non-delete mutation.\n * @param archivedSessionIds - current archive identities in durable order.\n * @mode emit\n */",
        "name": "workspace/archived-sessions-changed",
        "mode": "emit",
        "signature": "'workspace/archived-sessions-changed'(archivedSessionIds: readonly SessionId[]): void"
      },
      {
        "description": "Permanently removed identity after log, account and archive commits.",
        "summary": "Permanently removed identity after log, account and archive commits.",
        "tags": [
          {
            "name": "param",
            "argument": "sessionId",
            "comment": "- deleted identity.",
            "text": "@param sessionId - deleted identity.\n     *"
          },
          {
            "name": "param",
            "argument": "archivedSessionIds",
            "comment": "- remaining archive overlay.",
            "text": "@param archivedSessionIds - remaining archive overlay.\n     *"
          },
          {
            "name": "mode",
            "comment": "emit",
            "text": "@mode emit"
          }
        ],
        "jsDoc": "/**\n * Permanently removed identity after log, account and archive commits.\n * @param sessionId - deleted identity.\n * @param archivedSessionIds - remaining archive overlay.\n * @mode emit\n */",
        "name": "workspace/session-deleted",
        "mode": "emit",
        "signature": "'workspace/session-deleted'(sessionId: SessionId, archivedSessionIds: readonly SessionId[]): void"
      }
    ],
    "objects": []
  },
}
