/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_workspace_workspace_archiveSession_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_workspace_workspace_archiveSession_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.string().readonly(),
  'message': z.string().readonly(),
  'details': z.record(z.string(), z.string()).readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'archivedSessionIds': z.array(z.intersection(z.string(), z.unknown())).readonly(),
}).readonly(),
})])
const _deepseek_ai_dsh_workspace_workspace_create_parameter_0$schema = z.object({
  'path': z.string().readonly(),
})
const _deepseek_ai_dsh_workspace_workspace_create_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.string().readonly(),
  'message': z.string().readonly(),
  'details': z.record(z.string(), z.string()).readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'workspace': z.object({
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
  'path': z.string().readonly(),
  'title': z.string().readonly(),
  'sessionIds': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
}).readonly(),
  'created': z.boolean().readonly(),
}).readonly(),
})])
const _deepseek_ai_dsh_workspace_workspace_delete_parameter_0$schema = z.object({
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_workspace_workspace_delete_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.string().readonly(),
  'message': z.string().readonly(),
  'details': z.record(z.string(), z.string()).readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'deleted': z.literal(true).readonly(),
}).readonly(),
})])
const _deepseek_ai_dsh_workspace_workspace_deleteArchivedSession_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_workspace_workspace_deleteArchivedSession_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.string().readonly(),
  'message': z.string().readonly(),
  'details': z.record(z.string(), z.string()).readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'deleted': z.literal(true).readonly(),
  'archivedSessionIds': z.array(z.intersection(z.string(), z.unknown())).readonly(),
}).readonly(),
})])
const _deepseek_ai_dsh_workspace_workspace_insertBefore_parameter_0$schema = z.object({
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
  'beforeWorkspaceId': z.intersection(z.string(), z.unknown()).readonly().optional(),
})
const _deepseek_ai_dsh_workspace_workspace_insertBefore_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.string().readonly(),
  'message': z.string().readonly(),
  'details': z.record(z.string(), z.string()).readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'workspaceIds': z.array(z.intersection(z.string(), z.unknown())).readonly(),
}).readonly(),
})])
const _deepseek_ai_dsh_workspace_workspace_insertSessionBefore_parameter_0$schema = z.object({
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'beforeSessionId': z.intersection(z.string(), z.unknown()).readonly().optional(),
})
const _deepseek_ai_dsh_workspace_workspace_insertSessionBefore_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.string().readonly(),
  'message': z.string().readonly(),
  'details': z.record(z.string(), z.string()).readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'workspace': z.object({
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
  'path': z.string().readonly(),
  'title': z.string().readonly(),
  'sessionIds': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
}).readonly(),
}).readonly(),
})])
const _deepseek_ai_dsh_workspace_workspace_list_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.string().readonly(),
  'message': z.string().readonly(),
  'details': z.record(z.string(), z.string()).readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'items': z.array(z.object({
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
  'path': z.string().readonly(),
  'title': z.string().readonly(),
  'sessionIds': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
})).readonly(),
  'archivedSessionIds': z.array(z.intersection(z.string(), z.unknown())).readonly(),
}).readonly(),
})])
const _deepseek_ai_dsh_workspace_workspace_rename_parameter_0$schema = z.object({
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
})
const _deepseek_ai_dsh_workspace_workspace_rename_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.string().readonly(),
  'message': z.string().readonly(),
  'details': z.record(z.string(), z.string()).readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'workspace': z.object({
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
  'path': z.string().readonly(),
  'title': z.string().readonly(),
  'sessionIds': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
}).readonly(),
}).readonly(),
})])
const _deepseek_ai_dsh_workspace_workspace_unarchiveSession_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_workspace_workspace_unarchiveSession_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.string().readonly(),
  'message': z.string().readonly(),
  'details': z.record(z.string(), z.string()).readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'archivedSessionIds': z.array(z.intersection(z.string(), z.unknown())).readonly(),
}).readonly(),
})])

export const TYPERT = {
  package: '@deepseek-ai/dsh-workspace',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-workspace#workspace/archiveSession',
      service: 'workspaceRegistry',
      namespace: 'workspace',
      method: 'archiveSession',
      implementation: 'remoteExportArchiveSession',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-workspace/types#WorkspaceRemoteArchiveRequest',
            schema: _deepseek_ai_dsh_workspace_workspace_archiveSession_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-workspace/types#WorkspaceRemoteResult',
        schema: _deepseek_ai_dsh_workspace_workspace_archiveSession_result$schema,
      },
      sourceLocation: {"file":"packages/workspace/workspace/src/index.ts","line":503,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-workspace#workspace/create',
      service: 'workspaceRegistry',
      namespace: 'workspace',
      method: 'create',
      implementation: 'remoteExportCreate',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-workspace/types#WorkspaceRemoteCreateRequest',
            schema: _deepseek_ai_dsh_workspace_workspace_create_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-workspace/types#WorkspaceRemoteResult',
        schema: _deepseek_ai_dsh_workspace_workspace_create_result$schema,
      },
      sourceLocation: {"file":"packages/workspace/workspace/src/index.ts","line":409,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-workspace#workspace/delete',
      service: 'workspaceRegistry',
      namespace: 'workspace',
      method: 'delete',
      implementation: 'remoteExportDelete',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-workspace/types#WorkspaceRemoteDeleteRequest',
            schema: _deepseek_ai_dsh_workspace_workspace_delete_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-workspace/types#WorkspaceRemoteResult',
        schema: _deepseek_ai_dsh_workspace_workspace_delete_result$schema,
      },
      sourceLocation: {"file":"packages/workspace/workspace/src/index.ts","line":451,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-workspace#workspace/deleteArchivedSession',
      service: 'workspaceRegistry',
      namespace: 'workspace',
      method: 'deleteArchivedSession',
      implementation: 'remoteExportDeleteArchivedSession',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-workspace/types#WorkspaceRemoteDeleteArchivedRequest',
            schema: _deepseek_ai_dsh_workspace_workspace_deleteArchivedSession_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-workspace/types#WorkspaceRemoteResult',
        schema: _deepseek_ai_dsh_workspace_workspace_deleteArchivedSession_result$schema,
      },
      sourceLocation: {"file":"packages/workspace/workspace/src/index.ts","line":537,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-workspace#workspace/insertBefore',
      service: 'workspaceRegistry',
      namespace: 'workspace',
      method: 'insertBefore',
      implementation: 'remoteExportInsertBefore',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-workspace/types#WorkspaceRemoteInsertBeforeRequest',
            schema: _deepseek_ai_dsh_workspace_workspace_insertBefore_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-workspace/types#WorkspaceRemoteResult',
        schema: _deepseek_ai_dsh_workspace_workspace_insertBefore_result$schema,
      },
      sourceLocation: {"file":"packages/workspace/workspace/src/index.ts","line":468,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-workspace#workspace/insertSessionBefore',
      service: 'workspaceRegistry',
      namespace: 'workspace',
      method: 'insertSessionBefore',
      implementation: 'remoteExportInsertSessionBefore',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-workspace/types#WorkspaceRemoteInsertSessionBeforeRequest',
            schema: _deepseek_ai_dsh_workspace_workspace_insertSessionBefore_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-workspace/types#WorkspaceRemoteResult',
        schema: _deepseek_ai_dsh_workspace_workspace_insertSessionBefore_result$schema,
      },
      sourceLocation: {"file":"packages/workspace/workspace/src/index.ts","line":484,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-workspace#workspace/list',
      service: 'workspaceRegistry',
      namespace: 'workspace',
      method: 'list',
      implementation: 'remoteExportList',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-workspace/types#WorkspaceRemoteResult',
        schema: _deepseek_ai_dsh_workspace_workspace_list_result$schema,
      },
      sourceLocation: {"file":"packages/workspace/workspace/src/index.ts","line":391,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-workspace#workspace/rename',
      service: 'workspaceRegistry',
      namespace: 'workspace',
      method: 'rename',
      implementation: 'remoteExportRename',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-workspace/types#WorkspaceRemoteRenameRequest',
            schema: _deepseek_ai_dsh_workspace_workspace_rename_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-workspace/types#WorkspaceRemoteResult',
        schema: _deepseek_ai_dsh_workspace_workspace_rename_result$schema,
      },
      sourceLocation: {"file":"packages/workspace/workspace/src/index.ts","line":435,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-workspace#workspace/unarchiveSession',
      service: 'workspaceRegistry',
      namespace: 'workspace',
      method: 'unarchiveSession',
      implementation: 'remoteExportUnarchiveSession',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-workspace/types#WorkspaceRemoteArchiveRequest',
            schema: _deepseek_ai_dsh_workspace_workspace_unarchiveSession_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-workspace/types#WorkspaceRemoteResult',
        schema: _deepseek_ai_dsh_workspace_workspace_unarchiveSession_result$schema,
      },
      sourceLocation: {"file":"packages/workspace/workspace/src/index.ts","line":520,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "Durable workspace registry. Startup waits for `sessionPersistence`, builds one canonical-cwd header index, and completes the one-time history bootstrap before the service becomes active. The persistence dependency is mandatory so an unavailable peer can never be mistaken for an empty history and commit the initialized marker.",
        "summary": "Durable workspace registry.",
        "tags": [],
        "jsDoc": "/**\n * Durable workspace registry. Startup waits for `sessionPersistence`, builds\n * one canonical-cwd header index, and completes the one-time history\n * bootstrap before the service becomes active. The persistence dependency is\n * mandatory so an unavailable peer can never be mistaken for an empty\n * history and commit the initialized marker.\n */",
        "key": "workspaceRegistry",
        "exportName": "WorkspaceRegistry",
        "members": [
          {
            "kind": "method",
            "name": "create",
            "signature": "async create(path: string, title?: string): Promise<Workspace>",
            "summary": "Create or reuse a workspace for an existing directory.",
            "jsDoc": "/**\n * Create or reuse a workspace for an existing directory. The path is\n * canonicalized through `fs.realpath`; a nonexistent path rejects with the\n * original error and a non-directory rejects. Repeated calls for the same\n * canonical path return the existing entity without changing its title.\n * A newly created workspace is prepended to the durable registry order.\n * Different canonical paths may share a display title.\n * @param path - Existing directory to own, in any path spelling.\n * @param title - Display title used only when a new record is created.\n * @returns the existing or newly durable workspace.\n */"
          },
          {
            "kind": "method",
            "name": "createOrResolve",
            "signature": "async createOrResolve(path: string, title?: string): Promise<{ workspace: Workspace; created: boolean }>",
            "summary": "Create one Workspace or resolve the existing canonical path in the same registry serialization slot.",
            "jsDoc": "/**\n * Create one Workspace or resolve the existing canonical path in the same\n * registry serialization slot.  The `created` bit is therefore not guessed\n * from a stale preflight lookup.\n * @param path - Existing directory to own, in any path spelling.\n * @param title - Display title used only when a new record is created.\n * @returns the workspace and whether a new record was created.\n */"
          },
          {
            "kind": "method",
            "name": "get",
            "signature": "get(id: WorkspaceId): Workspace | undefined",
            "summary": "Look up a workspace by id.",
            "jsDoc": "/**\n * Look up a workspace by id.\n * @param id - Workspace id.\n * @returns the workspace, or `undefined` when unknown.\n */"
          },
          {
            "kind": "method",
            "name": "list",
            "signature": "list(): Workspace[]",
            "summary": "Synchronous workspace projection in durable registry order.",
            "jsDoc": "/**\n * Synchronous workspace projection in durable registry order. Every\n * entity's `sessionIds` getter is already filtered by the startup/live\n * canonical-cwd header index; this method performs no persistence reads.\n * @returns a fresh ordered array of workspace entities.\n */"
          },
          {
            "kind": "method",
            "name": "remoteExportList",
            "signature": "@Remote('list') remoteExportList(signal: AbortSignal): WorkspaceRemoteResult<WorkspaceRemoteListValue>",
            "summary": "List durable Workspaces and the archive overlay through the generated Remote boundary.",
            "jsDoc": "/**\n * List durable Workspaces and the archive overlay through the generated Remote boundary.\n * @param signal - caller-owned cancellation signal.\n * @returns the workspace list and archived-session overlay.\n */"
          },
          {
            "kind": "method",
            "name": "remoteExportCreate",
            "signature": "@Remote('create') async remoteExportCreate( request: WorkspaceRemoteCreateRequest, signal: AbortSignal, ): Promise<WorkspaceRemoteResult<WorkspaceRemoteCreateValue>>",
            "summary": "Create or resolve one canonical existing directory through the generated Remote boundary.",
            "jsDoc": "/**\n * Create or resolve one canonical existing directory through the generated Remote boundary.\n * @param request - directory path to create or resolve.\n * @param signal - caller-owned cancellation signal.\n * @returns the workspace result and creation flag.\n */"
          },
          {
            "kind": "method",
            "name": "remoteExportRename",
            "signature": "@Remote('rename') async remoteExportRename( request: WorkspaceRemoteRenameRequest, signal: AbortSignal, ): Promise<WorkspaceRemoteResult<WorkspaceRemoteWorkspaceValue>>",
            "summary": "Rename one Workspace without exposing the registry's write chain to transport code.",
            "jsDoc": "/**\n * Rename one Workspace without exposing the registry's write chain to transport code.\n * @param request - workspace id and replacement title.\n * @param signal - caller-owned cancellation signal.\n * @returns the renamed workspace result.\n */"
          },
          {
            "kind": "method",
            "name": "remoteExportDelete",
            "signature": "@Remote('delete') async remoteExportDelete( request: WorkspaceRemoteDeleteRequest, signal: AbortSignal, ): Promise<WorkspaceRemoteResult<WorkspaceRemoteDeletedValue>>",
            "summary": "Remove only a Workspace registration; neither files nor session logs are touched.",
            "jsDoc": "/**\n * Remove only a Workspace registration; neither files nor session logs are touched.\n * @param request - workspace id to remove.\n * @param signal - caller-owned cancellation signal.\n * @returns confirmation of the registration removal.\n */"
          },
          {
            "kind": "method",
            "name": "remoteExportInsertBefore",
            "signature": "@Remote('insertBefore') async remoteExportInsertBefore( request: WorkspaceRemoteInsertBeforeRequest, signal: AbortSignal, ): Promise<WorkspaceRemoteResult<WorkspaceRemoteOrderValue>>",
            "summary": "Reorder Workspace rows using DOM-insertBefore semantics.",
            "jsDoc": "/**\n * Reorder Workspace rows using DOM-insertBefore semantics.\n * @param request - workspace and optional anchor ids.\n * @param signal - caller-owned cancellation signal.\n * @returns the resulting workspace order.\n */"
          },
          {
            "kind": "method",
            "name": "remoteExportInsertSessionBefore",
            "signature": "@Remote('insertSessionBefore') async remoteExportInsertSessionBefore( request: WorkspaceRemoteInsertSessionBeforeRequest, signal: AbortSignal, ): Promise<WorkspaceRemoteResult<WorkspaceRemoteWorkspaceValue>>",
            "summary": "Reorder an accounted Session inside one Workspace.",
            "jsDoc": "/**\n * Reorder an accounted Session inside one Workspace.\n * @param request - workspace, session, and optional anchor ids.\n * @param signal - caller-owned cancellation signal.\n * @returns the updated workspace result.\n */"
          },
          {
            "kind": "method",
            "name": "remoteExportArchiveSession",
            "signature": "@Remote('archiveSession') async remoteExportArchiveSession( request: WorkspaceRemoteArchiveRequest, signal: AbortSignal, ): Promise<WorkspaceRemoteResult<WorkspaceRemoteArchivedValue>>",
            "summary": "Archive one Session without changing its Workspace account or log.",
            "jsDoc": "/**\n * Archive one Session without changing its Workspace account or log.\n * @param request - session id to archive.\n * @param signal - caller-owned cancellation signal.\n * @returns the archived-session ids after the operation.\n */"
          },
          {
            "kind": "method",
            "name": "remoteExportUnarchiveSession",
            "signature": "@Remote('unarchiveSession') async remoteExportUnarchiveSession( request: WorkspaceRemoteArchiveRequest, signal: AbortSignal, ): Promise<WorkspaceRemoteResult<WorkspaceRemoteArchivedValue>>",
            "summary": "Restore one archived Session without changing its retained Workspace position.",
            "jsDoc": "/**\n * Restore one archived Session without changing its retained Workspace position.\n * @param request - archived session id to restore.\n * @param signal - caller-owned cancellation signal.\n * @returns the archived-session ids after the operation.\n */"
          },
          {
            "kind": "method",
            "name": "remoteExportDeleteArchivedSession",
            "signature": "@Remote('deleteArchivedSession') async remoteExportDeleteArchivedSession( request: WorkspaceRemoteDeleteArchivedRequest, signal: AbortSignal, ): Promise<WorkspaceRemoteResult<WorkspaceRemoteDeleteArchivedValue>>",
            "summary": "Permanently delete an archived Session only through the exact lifecycle-retirement capability.",
            "jsDoc": "/**\n * Permanently delete an archived Session only through the exact lifecycle-retirement capability.\n * @param request - archived session id to delete.\n * @param signal - caller-owned cancellation signal.\n * @returns deletion confirmation and remaining archived-session ids.\n */"
          },
          {
            "kind": "method",
            "name": "delete",
            "signature": "delete(id: WorkspaceId): Promise<boolean>",
            "summary": "Delete one workspace registration while retaining its directory and every session log.",
            "jsDoc": "/**\n * Delete one workspace registration while retaining its directory and every\n * session log. The durable order is updated before the table deletion; a\n * failed table write restores the prior order and keeps the entity\n * published. Unknown ids are an idempotent no-op for domain callers.\n * @param id - Workspace registration to remove.\n * @returns `true` when a record was deleted, `false` when it was unknown.\n */"
          },
          {
            "kind": "method",
            "name": "rename",
            "signature": "rename(id: WorkspaceId, title: string): Promise<Workspace>",
            "summary": "Rename one Workspace through the same serialization chain as all registry writes.",
            "jsDoc": "/**\n * Rename one Workspace through the same serialization chain as all registry writes.\n * @param id - Workspace registration to rename.\n * @param title - replacement display title.\n * @returns the renamed workspace.\n */"
          },
          {
            "kind": "method",
            "name": "insertBefore",
            "signature": "insertBefore(id: WorkspaceId, beforeId?: WorkspaceId): Promise<readonly WorkspaceId[]>",
            "summary": "Move one workspace within the durable display order, DOM-insertBefore-like.",
            "jsDoc": "/**\n * Move one workspace within the durable display order, DOM-insertBefore-like.\n * With an anchor it lands before that workspace; without one it appends.\n * @param id - Workspace to move.\n * @param beforeId - Workspace anchor; omitted appends.\n * @returns the complete committed workspace order.\n */"
          },
          {
            "kind": "getter",
            "name": "archivedSessionIds",
            "signature": "get archivedSessionIds(): readonly SessionId[]",
            "summary": "The registry-global archive set: sessions hidden from every grouping surface.",
            "jsDoc": "/**\n * The registry-global archive set: sessions hidden from every grouping\n * surface. Archiving never touches workspace accounting — an archived\n * session keeps its `sessionIds` slot so unarchiving restores its position.\n * @returns the archived session ids in archive order.\n */"
          },
          {
            "kind": "method",
            "name": "sessionAdmissionRevision",
            "signature": "sessionAdmissionRevision(sessionId: SessionId): number",
            "summary": "Capture the in-process permanent-deletion generation for publication fencing.",
            "jsDoc": "/**\n * Capture the in-process permanent-deletion generation for publication fencing.\n * @param sessionId - Session identity whose deletion generation is read.\n * @returns Current admission generation for the session.\n */"
          },
          {
            "kind": "method",
            "name": "assertSessionAdmission",
            "signature": "assertSessionAdmission(sessionId: SessionId, revision: number): void",
            "summary": "Revalidate a publication against archive membership and deletion races.",
            "jsDoc": "/**\n * Revalidate a publication against archive membership and deletion races.\n * @param sessionId - Session identity being published.\n * @param revision - Admission generation captured before the asynchronous work.\n */"
          },
          {
            "kind": "method",
            "name": "archiveSession",
            "signature": "archiveSession(sessionId: SessionId): Promise<void>",
            "summary": "Archive one session durably.",
            "jsDoc": "/**\n * Archive one session durably. The session must exist (live or in session\n * persistence); its workspace accounting — or lack of one — is irrelevant.\n * An already archived id resolves without writing.\n * @param sessionId - The session to archive.\n * @returns resolution after durability.\n */"
          },
          {
            "kind": "method",
            "name": "unarchiveSession",
            "signature": "unarchiveSession(sessionId: SessionId): Promise<void>",
            "summary": "Remove an existing session from the archive set without touching its log/account slot.",
            "jsDoc": "/**\n * Remove an existing session from the archive set without touching its log/account slot.\n * @param sessionId - Archived session identity to restore.\n * @returns Resolution after the archive mutation is durable.\n */"
          },
          {
            "kind": "method",
            "name": "deleteArchivedSession",
            "signature": "deleteArchivedSession( sessionId: SessionId, retireResident?: (residentSessionId: SessionId) => Promise<void>, ): Promise<void>",
            "summary": "Permanently delete one archived session and every retained descendant.",
            "jsDoc": "/**\n * Permanently delete one archived session and every retained descendant.\n * Logs commit descendant-first before workspace accounts and archive state;\n * a later failure leaves the root archive marker available for retry.\n * @param sessionId - Archived root session identity to delete.\n * @param retireResident - Callback that retires a live/resident session before log deletion.\n * @returns Resolution after all retained records and archive state are durable.\n */"
          },
          {
            "kind": "method",
            "name": "resolveByPath",
            "signature": "async resolveByPath(path: string): Promise<Workspace | undefined>",
            "summary": "Resolve by canonical directory path without creating or mutating a workspace.",
            "jsDoc": "/**\n * Resolve by canonical directory path without creating or mutating a\n * workspace. A missing path rejects during `realpath`; an existing unowned\n * directory returns `undefined`.\n * @param path - Existing directory path in any spelling.\n * @returns the workspace owning the canonical path, when one exists.\n */"
          }
        ],
        "types": [
          {
            "name": "Branded",
            "declaration": "export type Branded<B extends string> = string & { readonly [BRAND]: B; };"
          },
          {
            "name": "SessionId",
            "declaration": "export type SessionId = Branded<'SessionId'>;"
          },
          {
            "name": "Workspace",
            "declaration": "export interface Workspace {\n    readonly id: WorkspaceId;\n    readonly path: string;\n    readonly title: string;\n    readonly createdAt: string;\n    readonly updatedAt: string;\n    readonly sessionIds: readonly SessionId[];\n    setTitle(title: string): Promise<void>;\n    attachSession(sessionId: SessionId): Promise<void>;\n    insertSessionBefore(sessionId: SessionId, beforeSessionId?: SessionId): Promise<void>;\n    detachSession(sessionId: SessionId): Promise<void>;\n    status(): Promise<'ok' | 'missing-dir'>;\n}"
          },
          {
            "name": "WorkspaceId",
            "declaration": "export type WorkspaceId = WorkspaceIdBrand;"
          },
          {
            "name": "WorkspaceId",
            "declaration": "export type WorkspaceId = Branded<'WorkspaceId'>;"
          },
          {
            "name": "WorkspaceRemoteArchivedValue",
            "declaration": "export interface WorkspaceRemoteArchivedValue {\n    readonly archivedSessionIds: readonly SessionId[];\n}"
          },
          {
            "name": "WorkspaceRemoteArchiveRequest",
            "declaration": "export interface WorkspaceRemoteArchiveRequest {\n    readonly sessionId: SessionId;\n}"
          },
          {
            "name": "WorkspaceRemoteCreateRequest",
            "declaration": "export interface WorkspaceRemoteCreateRequest {\n    readonly path: string;\n}"
          },
          {
            "name": "WorkspaceRemoteCreateValue",
            "declaration": "export interface WorkspaceRemoteCreateValue {\n    readonly workspace: WorkspaceRemoteView;\n    readonly created: boolean;\n}"
          },
          {
            "name": "WorkspaceRemoteDeleteArchivedRequest",
            "declaration": "export interface WorkspaceRemoteDeleteArchivedRequest {\n    readonly sessionId: SessionId;\n}"
          },
          {
            "name": "WorkspaceRemoteDeleteArchivedValue",
            "declaration": "export interface WorkspaceRemoteDeleteArchivedValue {\n    readonly deleted: true;\n    readonly archivedSessionIds: readonly SessionId[];\n}"
          },
          {
            "name": "WorkspaceRemoteDeletedValue",
            "declaration": "export interface WorkspaceRemoteDeletedValue {\n    readonly deleted: true;\n}"
          },
          {
            "name": "WorkspaceRemoteDeleteRequest",
            "declaration": "export interface WorkspaceRemoteDeleteRequest {\n    readonly workspaceId: WorkspaceId;\n}"
          },
          {
            "name": "WorkspaceRemoteFailure",
            "declaration": "export interface WorkspaceRemoteFailure {\n    readonly ok: false;\n    readonly error: { readonly code: string; readonly message: string; readonly details: Record<string, string>; };\n}"
          },
          {
            "name": "WorkspaceRemoteInsertBeforeRequest",
            "declaration": "export interface WorkspaceRemoteInsertBeforeRequest {\n    readonly workspaceId: WorkspaceId;\n    readonly beforeWorkspaceId?: WorkspaceId;\n}"
          },
          {
            "name": "WorkspaceRemoteInsertSessionBeforeRequest",
            "declaration": "export interface WorkspaceRemoteInsertSessionBeforeRequest {\n    readonly workspaceId: WorkspaceId;\n    readonly sessionId: SessionId;\n    readonly beforeSessionId?: SessionId;\n}"
          },
          {
            "name": "WorkspaceRemoteListValue",
            "declaration": "export interface WorkspaceRemoteListValue {\n    readonly items: readonly WorkspaceRemoteView[];\n    readonly archivedSessionIds: readonly SessionId[];\n}"
          },
          {
            "name": "WorkspaceRemoteOrderValue",
            "declaration": "export interface WorkspaceRemoteOrderValue {\n    readonly workspaceIds: readonly WorkspaceId[];\n}"
          },
          {
            "name": "WorkspaceRemoteRenameRequest",
            "declaration": "export interface WorkspaceRemoteRenameRequest {\n    readonly workspaceId: WorkspaceId;\n    readonly title: string;\n}"
          },
          {
            "name": "WorkspaceRemoteResult",
            "declaration": "export type WorkspaceRemoteResult<Value> = WorkspaceRemoteSuccess<Value> | WorkspaceRemoteFailure;"
          },
          {
            "name": "WorkspaceRemoteSuccess",
            "declaration": "export interface WorkspaceRemoteSuccess<Value> {\n    readonly ok: true;\n    readonly value: Value;\n}"
          },
          {
            "name": "WorkspaceRemoteView",
            "declaration": "export interface WorkspaceRemoteView {\n    readonly workspaceId: WorkspaceId;\n    readonly path: string;\n    readonly title: string;\n    readonly sessionIds: readonly SessionId[];\n    readonly createdAt: string;\n    readonly updatedAt: string;\n}"
          },
          {
            "name": "WorkspaceRemoteWorkspaceValue",
            "declaration": "export interface WorkspaceRemoteWorkspaceValue {\n    readonly workspace: WorkspaceRemoteView;\n}"
          }
        ]
      }
    ],
    "events": [
      {
        "description": "Complete committed archive set after a non-delete mutation.",
        "summary": "Complete committed archive set after a non-delete mutation.",
        "tags": [
          {
            "name": "param",
            "argument": "archivedSessionIds",
            "comment": "- Current archived session identities in durable order.",
            "text": "@param archivedSessionIds - Current archived session identities in durable order.\n     *"
          },
          {
            "name": "mode",
            "comment": "emit",
            "text": "@mode emit"
          }
        ],
        "jsDoc": "/**\n * Complete committed archive set after a non-delete mutation.\n * @param archivedSessionIds - Current archived session identities in durable order.\n * @mode emit\n */",
        "name": "workspace/archived-sessions-changed",
        "mode": "emit",
        "signature": "'workspace/archived-sessions-changed'(archivedSessionIds: readonly SessionId[]): void"
      },
      {
        "description": "One permanently deleted identity after log/account/archive commits.",
        "summary": "One permanently deleted identity after log/account/archive commits.",
        "tags": [
          {
            "name": "param",
            "argument": "sessionId",
            "comment": "- Root session identity that was permanently deleted.",
            "text": "@param sessionId - Root session identity that was permanently deleted.\n     *"
          },
          {
            "name": "param",
            "argument": "archivedSessionIds",
            "comment": "- Remaining archived session identities in durable order.",
            "text": "@param archivedSessionIds - Remaining archived session identities in durable order.\n     *"
          },
          {
            "name": "mode",
            "comment": "emit",
            "text": "@mode emit"
          }
        ],
        "jsDoc": "/**\n * One permanently deleted identity after log/account/archive commits.\n * @param sessionId - Root session identity that was permanently deleted.\n * @param archivedSessionIds - Remaining archived session identities in durable order.\n * @mode emit\n */",
        "name": "workspace/session-deleted",
        "mode": "emit",
        "signature": "'workspace/session-deleted'(sessionId: SessionId, archivedSessionIds: readonly SessionId[]): void"
      }
    ],
    "objects": []
  },
}
