/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { RemoteCredentialsDescription } from '@deepseek-ai/dsh-credentials/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$63726564656e7469616c73 {
    describe: (refs: readonly string[]) => Promise<RemoteResult<RemoteCredentialsDescription>>
    set: (refName: string, value: string) => Promise<RemoteResult<Record<never, never>>>
    unset: (refName: string) => Promise<RemoteResult<Record<never, never>>>
  }
  interface TypertRemoteMap {
    'credentials/describe': (refs: readonly string[]) => Promise<RemoteResult<RemoteCredentialsDescription>>
    'credentials/set': (refName: string, value: string) => Promise<RemoteResult<Record<never, never>>>
    'credentials/unset': (refName: string) => Promise<RemoteResult<Record<never, never>>>
  }
  interface TypertRemoteNamespaceMap {
    'credentials': TypertRemoteNamespace$63726564656e7469616c73
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
