/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { CreateGoalRequest, CreateGoalResult, GoalRemoteClearResult, GoalRemoteEditRequest, GoalRemoteRefRequest } from '@deepseek-ai/dsh-goal/client'
import type { SessionId } from '@deepseek-ai/dsh-session/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteScopeMap {
    'agent:goal/clear': (request: GoalRemoteRefRequest) => Promise<RemoteResult<GoalRemoteClearResult>>
    'agent:goal/complete': (request: GoalRemoteRefRequest) => Promise<RemoteResult<CreateGoalResult>>
    'agent:goal/create': (request: CreateGoalRequest) => Promise<RemoteResult<CreateGoalResult>>
    'agent:goal/edit': (request: GoalRemoteEditRequest) => Promise<RemoteResult<CreateGoalResult>>
    'agent:goal/pause': (request: GoalRemoteRefRequest) => Promise<RemoteResult<CreateGoalResult>>
    'agent:goal/resume': (request: GoalRemoteRefRequest) => Promise<RemoteResult<CreateGoalResult>>
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
