/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const RemoteSettingsJsonValueRemoteCodec$schema = z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema)), z.record(z.string(), z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema))])
const RemoteSettingsJsonValueRemoteCodec$schema2 = z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema2)), z.record(z.string(), z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema2))])
const RemoteSettingsJsonValueRemoteCodec$schema3 = z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema3)), z.record(z.string(), z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema3))])
const _deepseek_ai_dsh_llm_llm_discoverModels_parameter_0$schema = z.object({
  'settingsNs': z.string().readonly(),
  'provider': z.string().readonly().optional(),
  'baseURL': z.string().readonly().optional(),
  'api': z.string().readonly().optional(),
  'apiKey': z.string().readonly().optional(),
})
const _deepseek_ai_dsh_llm_llm_discoverModels_result$schema = z.object({
  'models': z.array(z.object({
  'id': z.string().readonly(),
  'name': z.string().readonly().optional(),
  'contextWindow': z.number().readonly().optional(),
  'maxTokens': z.number().readonly().optional(),
})).readonly(),
})
const _deepseek_ai_dsh_llm_llm_models_result$schema = z.object({
  'groups': z.array(z.object({
  'id': z.string().readonly(),
  'name': z.string().readonly(),
  'models': z.array(z.object({
  'id': z.string().readonly(),
  'name': z.string().readonly(),
  'description': z.string().readonly().optional(),
  'defaultMaxTokens': z.number().readonly().optional(),
  'reasoning': z.object({
  'efforts': z.array(z.object({
  'id': z.string().readonly(),
  'name': z.string().readonly(),
  'description': z.string().readonly().optional(),
})).readonly(),
  'defaultEffort': z.string().readonly().optional(),
}).readonly().optional(),
})).readonly(),
})).readonly(),
  'failures': z.array(z.object({
  'id': z.string().readonly(),
  'name': z.string().readonly(),
  'message': z.string().readonly(),
})).readonly(),
})
const _deepseek_ai_dsh_llm_llm_mutateProvider_parameter_0$schema = z.object({
  'transactionId': z.string().readonly(),
  'provider': z.string().readonly(),
  'settingsNs': z.string().readonly(),
  'ops': z.array(z.union([z.object({
  'op': z.literal("set").readonly(),
  'path': z.array(z.string()).readonly(),
  'value': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema2)), z.record(z.string(), z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema2))]).readonly(),
}), z.object({
  'op': z.literal("unset").readonly(),
  'path': z.array(z.string()).readonly(),
})])).readonly(),
  'expectedRevision': z.number().readonly(),
  'credential': z.union([z.object({
  'op': z.literal("set").readonly(),
  'ref': z.string().readonly(),
  'value': z.string().readonly(),
}), z.object({
  'op': z.literal("unset").readonly(),
  'ref': z.string().readonly(),
})]).readonly().optional(),
})
const _deepseek_ai_dsh_llm_llm_mutateProvider_result$schema = z.object({
  'settings': z.object({
  'ns': z.string().readonly(),
  'schema': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema)), z.record(z.string(), z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema))]).readonly(),
  'value': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema)), z.record(z.string(), z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema))]).readonly(),
  'base': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema)), z.record(z.string(), z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema))]).readonly().optional(),
  'user': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema)), z.record(z.string(), z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema))]).readonly().optional(),
  'applies': z.union([z.literal("live"), z.literal("restart")]).readonly(),
  'secrets': z.array(z.object({
  'path': z.array(z.string()).readonly(),
  'set': z.boolean().readonly(),
})).readonly(),
  'revision': z.number().readonly(),
}).readonly(),
  'credential': z.object({
  'configured': z.boolean().readonly(),
  'source': z.string().readonly().optional(),
  'writable': z.boolean().readonly(),
}).readonly().optional(),
  'live': z.object({
  'accepted': z.literal(true).readonly(),
}).readonly().optional(),
})
const _deepseek_ai_dsh_llm_llm_providers_result$schema = z.object({
  'providers': z.array(z.object({
  'provider': z.string().readonly(),
  'displayName': z.string().readonly(),
  'settingsNs': z.string().readonly(),
  'settingsPath': z.array(z.string()).readonly(),
  'active': z.boolean().readonly(),
  'declared': z.boolean().readonly().optional(),
  'migrationRequired': z.object({
  'code': z.literal("credential-headers").readonly(),
  'fields': z.array(z.string()).readonly(),
}).readonly().optional(),
})).readonly(),
})
const _deepseek_ai_dsh_llm_llm_providerTransaction_parameter_0$schema = z.object({
  'provider': z.string().readonly(),
  'transactionId': z.string().readonly(),
})
const _deepseek_ai_dsh_llm_llm_providerTransaction_result$schema = z.object({
  'state': z.union([z.literal("absent"), z.literal("prepared"), z.literal("credential-staged"), z.literal("settings-applied"), z.literal("credential-applied"), z.literal("committed"), z.literal("rolled-back"), z.literal("committed-not-live")]).readonly(),
  'needsCredential': z.boolean().readonly(),
  'settingsNs': z.string().readonly().optional(),
  'live': z.boolean().readonly().optional(),
})
const _deepseek_ai_dsh_llm_llm_resumeProvider_parameter_0$schema = z.object({
  'provider': z.string().readonly(),
  'transactionId': z.string().readonly(),
  'credentialValue': z.string().readonly().optional(),
})
const _deepseek_ai_dsh_llm_llm_resumeProvider_result$schema = z.object({
  'settings': z.object({
  'ns': z.string().readonly(),
  'schema': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema3)), z.record(z.string(), z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema3))]).readonly(),
  'value': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema3)), z.record(z.string(), z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema3))]).readonly(),
  'base': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema3)), z.record(z.string(), z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema3))]).readonly().optional(),
  'user': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema3)), z.record(z.string(), z.lazy(() => RemoteSettingsJsonValueRemoteCodec$schema3))]).readonly().optional(),
  'applies': z.union([z.literal("live"), z.literal("restart")]).readonly(),
  'secrets': z.array(z.object({
  'path': z.array(z.string()).readonly(),
  'set': z.boolean().readonly(),
})).readonly(),
  'revision': z.number().readonly(),
}).readonly(),
  'credential': z.object({
  'configured': z.boolean().readonly(),
  'source': z.string().readonly().optional(),
  'writable': z.boolean().readonly(),
}).readonly().optional(),
  'live': z.object({
  'accepted': z.literal(true).readonly(),
}).readonly().optional(),
})
const _deepseek_ai_dsh_llm_llm_verifyProvider_parameter_0$schema = z.object({
  'provider': z.string().readonly(),
  'model': z.string().readonly(),
})
const _deepseek_ai_dsh_llm_llm_verifyProvider_result$schema = z.union([z.object({
  'provider': z.string().readonly(),
  'model': z.string().readonly(),
  'verified': z.literal(true).readonly(),
  'mode': z.union([z.literal("metadata-auth"), z.literal("minimal-generation")]).readonly(),
}), z.object({
  'provider': z.string().readonly(),
  'model': z.string().readonly(),
  'verified': z.literal(false).readonly(),
  'mode': z.literal("endpoint-catalog").readonly(),
  'classification': z.literal("reachability-only").readonly(),
})])

export const TYPERT = {
  package: '@deepseek-ai/dsh-llm',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-llm#llm/discoverModels',
      service: 'llm',
      namespace: 'llm',
      method: 'discoverModels',
      implementation: 'remoteDiscoverModels',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-llm/types#RemoteLlmDiscoverModelsRequest',
            schema: _deepseek_ai_dsh_llm_llm_discoverModels_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-llm/types#RemoteLlmDiscoveredModelsResult',
        schema: _deepseek_ai_dsh_llm_llm_discoverModels_result$schema,
      },
      sourceLocation: {"file":"packages/llm/llm/src/index.ts","line":214,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-llm#llm/models',
      service: 'llm',
      namespace: 'llm',
      method: 'models',
      implementation: 'remoteModels',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-llm/types#RemoteLlmModelsResult',
        schema: _deepseek_ai_dsh_llm_llm_models_result$schema,
      },
      sourceLocation: {"file":"packages/llm/llm/src/index.ts","line":203,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-llm#llm/mutateProvider',
      service: 'llm',
      namespace: 'llm',
      method: 'mutateProvider',
      implementation: 'remoteMutateProvider',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-llm/types#RemoteLlmProviderMutationRequest',
            schema: _deepseek_ai_dsh_llm_llm_mutateProvider_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-llm/types#RemoteLlmProviderMutationResult',
        schema: _deepseek_ai_dsh_llm_llm_mutateProvider_result$schema,
      },
      sourceLocation: {"file":"packages/llm/llm/src/index.ts","line":171,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-llm#llm/providers',
      service: 'llm',
      namespace: 'llm',
      method: 'providers',
      implementation: 'remoteProviders',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-llm/types#RemoteLlmProvidersResult',
        schema: _deepseek_ai_dsh_llm_llm_providers_result$schema,
      },
      sourceLocation: {"file":"packages/llm/llm/src/index.ts","line":160,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-llm#llm/providerTransaction',
      service: 'llm',
      namespace: 'llm',
      method: 'providerTransaction',
      implementation: 'remoteProviderTransaction',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-llm/types#RemoteLlmProviderTransactionRequest',
            schema: _deepseek_ai_dsh_llm_llm_providerTransaction_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-llm/types#RemoteLlmProviderTransactionResult',
        schema: _deepseek_ai_dsh_llm_llm_providerTransaction_result$schema,
      },
      sourceLocation: {"file":"packages/llm/llm/src/index.ts","line":181,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-llm#llm/resumeProvider',
      service: 'llm',
      namespace: 'llm',
      method: 'resumeProvider',
      implementation: 'remoteResumeProvider',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-llm/types#RemoteLlmProviderResumeRequest',
            schema: _deepseek_ai_dsh_llm_llm_resumeProvider_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-llm/types#RemoteLlmProviderMutationResult',
        schema: _deepseek_ai_dsh_llm_llm_resumeProvider_result$schema,
      },
      sourceLocation: {"file":"packages/llm/llm/src/index.ts","line":194,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-llm#llm/verifyProvider',
      service: 'llm',
      namespace: 'llm',
      method: 'verifyProvider',
      implementation: 'remoteVerifyProvider',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-llm/types#RemoteLlmProviderVerificationRequest',
            schema: _deepseek_ai_dsh_llm_llm_verifyProvider_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-llm/types#RemoteLlmProviderVerificationResult',
        schema: _deepseek_ai_dsh_llm_llm_verifyProvider_result$schema,
      },
      sourceLocation: {"file":"packages/llm/llm/src/index.ts","line":228,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "The abstract `llm` service: an adapter registry plus a streaming model-call API, interceptable via the `llm/stream` waterfall.",
        "summary": "The abstract `llm` service: an adapter registry plus a streaming model-call API, interceptable via the `llm/stream` waterfall.",
        "tags": [],
        "jsDoc": "/**\n * The abstract `llm` service: an adapter registry plus a streaming model-call\n * API, interceptable via the `llm/stream` waterfall.\n */",
        "key": "llm",
        "exportName": "LlmRuntime",
        "members": [
          {
            "kind": "method",
            "name": "remoteProviders",
            "signature": "@Remote('providers') remoteProviders(): RemoteLlmProvidersResult",
            "summary": "Read configurable providers through the domain-owned Native Remote.",
            "jsDoc": "/**\n * Read configurable providers through the domain-owned Native Remote.\n * @returns the redacted configurable-provider catalog.\n */"
          },
          {
            "kind": "method",
            "name": "remoteMutateProvider",
            "signature": "@Remote('mutateProvider') async remoteMutateProvider(request: RemoteLlmProviderMutationRequest, signal?: AbortSignal): Promise<RemoteLlmProviderMutationResult>",
            "summary": "Commit one idempotent provider settings/credential transaction.",
            "jsDoc": "/**\n * Commit one idempotent provider settings/credential transaction.\n * @param request - provider mutation and expected revision.\n * @param signal - Caller cancellation before durable claim; claimed commits retain ownership until settled.\n * @returns the committed provider mutation result.\n */"
          },
          {
            "kind": "method",
            "name": "remoteProviderTransaction",
            "signature": "@Remote('providerTransaction') async remoteProviderTransaction( request: RemoteLlmProviderTransactionRequest, ): Promise<RemoteLlmProviderTransactionResult>",
            "summary": "Read the durable, secret-free state of one provider mutation.",
            "jsDoc": "/**\n * Read the durable, secret-free state of one provider mutation.\n * @param request - Provider id and transaction UUID to inspect.\n * @returns Current durable phase and whether a staged credential is still required.\n */"
          },
          {
            "kind": "method",
            "name": "remoteResumeProvider",
            "signature": "@Remote('resumeProvider') async remoteResumeProvider(request: RemoteLlmProviderResumeRequest, signal?: AbortSignal): Promise<RemoteLlmProviderMutationResult>",
            "summary": "Continue one journaled provider mutation after Host or app restart.",
            "jsDoc": "/**\n * Continue one journaled provider mutation after Host or app restart.\n * @param request - Provider id, transaction UUID, and optional write-only credential replay.\n * @param signal - Caller cancellation before resuming a durable commit.\n * @returns Committed provider view or the transaction's durable terminal failure.\n */"
          },
          {
            "kind": "method",
            "name": "remoteModels",
            "signature": "@Remote('models') async remoteModels(): Promise<RemoteLlmModelsResult>",
            "summary": "Read the failure-isolated host-scoped model catalog.",
            "jsDoc": "/**\n * Read the failure-isolated host-scoped model catalog.\n * @returns the model catalog grouped by provider.\n */"
          },
          {
            "kind": "method",
            "name": "remoteDiscoverModels",
            "signature": "@Remote('discoverModels') async remoteDiscoverModels( request: RemoteLlmDiscoverModelsRequest, signal: AbortSignal, ): Promise<RemoteLlmDiscoveredModelsResult>",
            "summary": "Interrogate a draft endpoint with an optional write-only one-shot key.",
            "jsDoc": "/**\n * Interrogate a draft endpoint with an optional write-only one-shot key.\n * @param request - draft endpoint and discovery options.\n * @param signal - caller-owned cancellation signal.\n * @returns discovered models and provider diagnostics.\n */"
          },
          {
            "kind": "method",
            "name": "remoteVerifyProvider",
            "signature": "@Remote('verifyProvider') async remoteVerifyProvider( request: RemoteLlmProviderVerificationRequest, signal: AbortSignal, ): Promise<RemoteLlmProviderVerificationResult>",
            "summary": "Execute one bounded exact provider/model/auth probe.",
            "jsDoc": "/**\n * Execute one bounded exact provider/model/auth probe.\n * @param request - Exact provider and model route to verify.\n * @param signal - Caller cancellation combined with the Host verification deadline.\n * @returns Verification mode used by the adapter or fallback request.\n */"
          },
          {
            "kind": "method",
            "name": "registerAdapter",
            "signature": "registerAdapter(providers: string[], adapter: LlmAdapter): AdapterRegistrationHandle",
            "summary": "Register an adapter for the given provider routes.",
            "jsDoc": "/**\n * Register an adapter for the given provider routes. Throws `LlmError` with code\n * `DUPLICATE_ADAPTER` if any provider already has an adapter (all-or-nothing).\n * Disposed with the fiber.\n * @param providers - every provider route this adapter should serve.\n * @param adapter - the adapter that streams calls for those providers.\n * @returns the disposer, carrying {@link AdapterRegistrationHandle.replace}.\n */"
          },
          {
            "kind": "method",
            "name": "listProviders",
            "signature": "listProviders(): LlmProviderInfo[]",
            "summary": "Describe provider routes with a registered adapter.",
            "jsDoc": "/**\n * Describe provider routes with a registered adapter.\n * @returns detached provider metadata in registration order.\n */"
          },
          {
            "kind": "method",
            "name": "registerConfigurableProviders",
            "signature": "registerConfigurableProviders(entries: readonly LlmConfigurableProvider[]): DirectoryRegistrationHandle",
            "summary": "Declare provider routes an adapter plugin can activate through configuration.",
            "jsDoc": "/**\n * Declare provider routes an adapter plugin can activate through\n * configuration. Registration is all-or-nothing: an empty list, invalid\n * entry, or a provider already declared by any registration throws\n * `LlmError` without registering the rest. Disposed with the fiber.\n * @param entries - every configurable provider this plugin owns.\n * @returns a handle that withdraws all of them, and can atomically replace them.\n */"
          },
          {
            "kind": "method",
            "name": "listConfigurableProviders",
            "signature": "listConfigurableProviders(): LlmConfigurableProvider[]",
            "summary": "List every declared configurable provider, registered or dormant.",
            "jsDoc": "/**\n * List every declared configurable provider, registered or dormant.\n * @returns detached directory entries in declaration order.\n */"
          },
          {
            "kind": "method",
            "name": "registerModelDiscovery",
            "signature": "registerModelDiscovery( settingsNs: string, discover: (request: LlmModelDiscoveryRequest) => Promise<readonly LlmDiscoveredModel[]>, ): () => void",
            "summary": "Offer to interrogate provider endpoints on behalf of the settings namespace this plugin owns.",
            "jsDoc": "/**\n * Offer to interrogate provider endpoints on behalf of the settings\n * namespace this plugin owns. The namespace is the key because that is what\n * a configuration surface already holds from the configurable-provider\n * directory, and because a provider being *added* has no route to name yet.\n * Disposed with the fiber.\n * @param settingsNs - the namespace whose profiles this discovery serves.\n * @param discover - interrogates one endpoint; must honor `request.signal`.\n * @returns the disposer that withdraws the offer.\n */"
          },
          {
            "kind": "method",
            "name": "discoverModels",
            "signature": "async discoverModels( settingsNs: string, request: LlmModelDiscoveryRequest, ): Promise<LlmDiscoveredModel[]>",
            "summary": "Interrogate one provider endpoint for the models it advertises.",
            "jsDoc": "/**\n * Interrogate one provider endpoint for the models it advertises. The\n * request describes a draft, not a stored route, so nothing here reads or\n * writes settings or credentials — the caller owns both, and the reply is\n * candidate metadata a surface may offer for adoption.\n * @param settingsNs - namespace whose registered discovery serves this draft.\n * @param request - the endpoint, protocol, and one-shot credential to use.\n * @returns the advertised models, deduplicated in endpoint order.\n */"
          },
          {
            "kind": "method",
            "name": "providerRetryPolicy",
            "signature": "providerRetryPolicy(provider: string): ResolvedRetryPolicy",
            "summary": "Resolve the retry policy captured when one provider route was registered.",
            "jsDoc": "/**\n * Resolve the retry policy captured when one provider route was registered.\n * @param provider - registered provider route to inspect.\n * @returns the provider-owned policy, with normal defaults already resolved.\n */"
          },
          {
            "kind": "method",
            "name": "imageRequestPricing",
            "signature": "imageRequestPricing(provider: string, model: string): LlmImageRequestPricing | undefined",
            "summary": "Resolve route-owned request-image pricing without performing I/O.",
            "jsDoc": "/**\n * Resolve route-owned request-image pricing without performing I/O. Unknown\n * routes intentionally degrade to heuristic pricing for historical logs.\n * @param provider - provider route whose registered adapter owns pricing.\n * @param model - exact model id whose image occurrences will be priced.\n * @returns route-owned pricing, or `undefined` when the route supplies none.\n */"
          },
          {
            "kind": "method",
            "name": "listModels",
            "signature": "async listModels(provider: string): Promise<LlmModelInfo[]>",
            "summary": "Discover models advertised by one registered provider.",
            "jsDoc": "/**\n * Discover models advertised by one registered provider. Catalog membership\n * is advisory and never changes routing or request validation.\n * @param provider - registered provider route to inspect.\n * @returns detached model metadata in adapter-preferred order.\n */"
          },
          {
            "kind": "method",
            "name": "resolveModelInfo",
            "signature": "async resolveModelInfo( provider: string, model: string, signal?: AbortSignal, ): Promise<LlmResolvedModelInfo>",
            "summary": "Resolve and validate all metadata from the adapter that owns one exact route.",
            "jsDoc": "/**\n * Resolve and validate all metadata from the adapter that owns one exact\n * route. The result is detached from adapter-owned objects; catalog\n * membership remains advisory and does not control request routing.\n * @param provider - registered provider route to inspect.\n * @param model - exact model id passed to the adapter.\n * @param signal - optional cancellation for adapter-owned asynchronous lookup.\n * @returns exact model identity plus available context and reasoning metadata.\n */"
          },
          {
            "kind": "method",
            "name": "verifyModel",
            "signature": "async verifyModel(provider: string, model: string, signal: AbortSignal): Promise<LlmProviderVerificationMode>",
            "summary": "Prove an exact provider/model route can authenticate and complete a bounded request.",
            "jsDoc": "/**\n * Prove an exact provider/model route can authenticate and complete a bounded\n* request. The caller supplies the deadline signal; no output is retained or\n* returned to configuration surfaces.\n * @param provider - Registered provider route to authenticate.\n * @param model - Exact model id to probe.\n * @param signal - Caller-owned deadline and cancellation signal.\n * @returns Adapter-native or bounded fallback verification mode.\n */"
          },
          {
            "kind": "method",
            "name": "resolveCallConfig",
            "signature": "async resolveCallConfig(config: LlmCallConfig, signal?: AbortSignal): Promise<LlmCallConfig>",
            "summary": "Validate a conversation call config against its exact model capability and materialize adapter-configured defaults.",
            "jsDoc": "/**\n * Validate a conversation call config against its exact model capability and\n * materialize adapter-configured defaults. Unsupported explicit efforts\n * reject before provider I/O; no clamping or aliasing is performed. This\n * standalone query does not bind a later dispatch; use {@link prepareCall}\n * when logging and streaming must share one adapter registration.\n * @param config - provider/model route and optional request controls.\n * @param signal - optional cancellation for adapter-owned capability lookup.\n * @returns a detached config only when a default must be materialized.\n */"
          },
          {
            "kind": "method",
            "name": "prepareCall",
            "signature": "async prepareCall(config: LlmCallConfig, signal?: AbortSignal): Promise<PreparedLlmCall>",
            "summary": "Resolve one call under its current adapter registration.",
            "jsDoc": "/**\n * Resolve one call under its current adapter registration. The returned\n * one-shot handle keeps that registration across header logging and dispatch,\n * so HMR cannot combine one adapter's capability result with another adapter.\n * @param config - provider/model route and optional request controls.\n * @param signal - optional cancellation for adapter-owned capability lookup.\n * @returns a prepared config and its registration-bound stream entry point.\n */"
          },
          {
            "kind": "method",
            "name": "stream",
            "signature": "stream(options: GenerateOptions): AsyncIterable<StreamChunk>",
            "summary": "Stream one model call as raw chunks (token-level deltas).",
            "jsDoc": "/**\n * Stream one model call as raw chunks (token-level deltas). Replay state is\n * retained only when the same adapter instance owns its historical provider\n * and the target provider. Final adapter selection remains fixed through\n * asynchronous exact-model resolution and dispatch. Adapter selection,\n * dispatch, and iteration failures become terminal `error` or `aborted`\n * finish chunks; middleware, nested-call, and consumer failures remain\n * thrown. A downstream-close cleanup failure is logged so it cannot mask\n * the consumer's own completion or failure.\n * @param options - the full request; `options.provider` selects the adapter.\n * @returns the chunk stream, possibly wrapped by `llm/stream` listeners.\n */"
          }
        ],
        "types": [
          {
            "name": "AdapterRegistrationHandle",
            "declaration": "export interface AdapterRegistrationHandle {\n    (): void;\n    replace(providers: string[]): void;\n}"
          },
          {
            "name": "AssistantProvenance",
            "declaration": "export interface AssistantProvenance {\n    provider: string;\n    model: string;\n    replayState?: unknown;\n}"
          },
          {
            "name": "AttachmentId",
            "declaration": "export type AttachmentId = Branded<'AttachmentId'>;"
          },
          {
            "name": "Branded",
            "declaration": "export type Branded<B extends string> = string & { readonly [BRAND]: B; };"
          },
          {
            "name": "CallId",
            "declaration": "export type CallId = Branded<'CallId'>;"
          },
          {
            "name": "ContentBlock",
            "declaration": "export type ContentBlock = ContentBlockMap[ContentBlockType];"
          },
          {
            "name": "ContentBlockMap",
            "declaration": "export interface ContentBlockMap {\n    text: TextBlock;\n    reasoning: ReasoningBlock;\n    image: ImageBlock;\n    'tool-call': ToolCallBlock;\n    'tool-result': ToolResultBlock;\n}"
          },
          {
            "name": "ContentBlockType",
            "declaration": "export type ContentBlockType = keyof ContentBlockMap;"
          },
          {
            "name": "ContextFormed",
            "declaration": "export type ContextFormed = { readonly form?: never; } | { readonly form: 'instructions'; } | { readonly form: 'catalog'; } | { readonly form: 'snapshot'; readonly sections: readonly ContextSnapshotSection[]; } | { readonly form: 'notice'; readonly summary: string; } | { readonly form: 'relay'; } | { readonly form: 'recall'; };"
          },
          {
            "name": "ContextSnapshotSection",
            "declaration": "export interface ContextSnapshotSection {\n    readonly name: string;\n    readonly text: string;\n}"
          },
          {
            "name": "CoordinatorMessageSource",
            "declaration": "export interface CoordinatorMessageSource {\n    readonly kind: 'coordinator';\n    readonly form: 'relay';\n    readonly senderSessionId: SessionId;\n}"
          },
          {
            "name": "DirectoryRegistrationHandle",
            "declaration": "export interface DirectoryRegistrationHandle {\n    (): void;\n    replace(entries: readonly LlmConfigurableProvider[]): void;\n}"
          },
          {
            "name": "FinishReason",
            "declaration": "export type FinishReason = FinishReasonMap[keyof FinishReasonMap];"
          },
          {
            "name": "FinishReasonMap",
            "declaration": "export interface FinishReasonMap {\n    stop: { kind: 'stop'; };\n    'tool-calls': { kind: 'tool-calls'; };\n    'max-tokens': { kind: 'max-tokens'; };\n    aborted: { kind: 'aborted'; failure: LlmFailure; };\n    error: { kind: 'error'; failure: LlmFailure; };\n}"
          },
          {
            "name": "GenerateOptions",
            "declaration": "export interface GenerateOptions {\n    provider: string;\n    model: string;\n    reasoningEffort?: ReasoningEffortId;\n    messages: Message[];\n    system?: string;\n    tools?: ToolSchema[];\n    temperature?: number;\n    maxTokens?: number;\n    stop?: string[];\n    signal?: AbortSignal;\n    sessionId?: Branded<'SessionId'>;\n    purpose?: 'compaction' | 'session-title';\n}"
          },
          {
            "name": "GoalId",
            "declaration": "export type GoalId = Branded<'GoalId'>;"
          },
          {
            "name": "GoalMessageSource",
            "declaration": "export interface GoalMessageSource {\n    readonly kind: 'goal';\n    readonly goalId: GoalId;\n    readonly revision: number;\n    readonly round: number;\n}"
          },
          {
            "name": "ImageAttachmentRef",
            "declaration": "export interface ImageAttachmentRef {\n    attachmentId: AttachmentId;\n    mediaType: ImageMediaType;\n    bytes: number;\n    width: number;\n    height: number;\n    name?: string;\n    originalDimensions?: { width: number; height: number; };\n}"
          },
          {
            "name": "ImageBlock",
            "declaration": "export interface ImageBlock {\n    type: 'image';\n    attachment: ImageAttachmentRef;\n}"
          },
          {
            "name": "ImageMediaType",
            "declaration": "export type ImageMediaType = 'image/png' | 'image/jpeg' | 'image/webp' | 'image/gif';"
          },
          {
            "name": "LlmAdapter",
            "declaration": "export abstract class LlmAdapter {\n    providerInfo(provider: string): LlmProviderInfo;\n    providerRetryPolicy(_provider: string): ResolvedRetryPolicy | undefined;\n    imageRequestPricing(_provider: string, _model: string): LlmImageRequestPricing | undefined;\n    listModels(_provider: string): Promise<readonly LlmModelInfo[]>;\n    resolveModel(provider: string, model: string, _signal?: AbortSignal): Promise<LlmResolvedModelInfo>;\n    verifyProvider(_provider: string, _model: string, _signal: AbortSignal): Promise<LlmProviderVerificationMode | undefined>;\n    prepareCall(provider: string, model: string, signal?: AbortSignal): Promise<PreparedAdapterCall>;\n    abstract stream(options: GenerateOptions): AsyncIterable<StreamChunk>;\n}"
          },
          {
            "name": "LlmCallConfig",
            "declaration": "export interface LlmCallConfig {\n    provider: string;\n    model: string;\n    reasoningEffort?: ReasoningEffortId;\n    temperature?: number;\n    maxTokens?: number;\n    stop?: string[];\n}"
          },
          {
            "name": "LlmCallConfigAdapterDefaults",
            "declaration": "export interface LlmCallConfigAdapterDefaults {\n    reasoningEffort?: true;\n    maxTokens?: true;\n}"
          },
          {
            "name": "LlmConfigurableProvider",
            "declaration": "export interface LlmConfigurableProvider {\n    provider: string;\n    displayName: string;\n    settingsNs: string;\n    settingsPath: readonly string[];\n    declared?: boolean;\n    migrationRequired?: { readonly code: 'credential-headers'; readonly fields: readonly string[]; };\n}"
          },
          {
            "name": "LlmDiscoveredModel",
            "declaration": "export interface LlmDiscoveredModel {\n    id: string;\n    name?: string;\n    contextWindow?: number;\n    maxTokens?: number;\n}"
          },
          {
            "name": "LlmFailure",
            "declaration": "export interface LlmFailure {\n    readonly message: string;\n    readonly code: string;\n    readonly status?: number;\n    readonly providerRetryAfterMs?: number;\n    readonly requestId?: ProviderRequestId;\n}"
          },
          {
            "name": "LlmImageRequestPrice",
            "declaration": "export interface LlmImageRequestPrice {\n    visualTokens: number;\n    text: string;\n}"
          },
          {
            "name": "LlmImageRequestPricing",
            "declaration": "export interface LlmImageRequestPricing {\n    priceImages(images: readonly ImageAttachmentRef[]): readonly LlmImageRequestPrice[];\n}"
          },
          {
            "name": "LlmModelContext",
            "declaration": "export interface LlmModelContext {\n    contextWindow: number;\n}"
          },
          {
            "name": "LlmModelDiscoveryRequest",
            "declaration": "export interface LlmModelDiscoveryRequest {\n    provider?: string;\n    baseURL?: string;\n    api?: string;\n    apiKey?: string;\n    credentialEndpointFingerprint?: string;\n    signal?: AbortSignal;\n}"
          },
          {
            "name": "LlmModelInfo",
            "declaration": "export interface LlmModelInfo {\n    provider: string;\n    id: string;\n    name: string;\n    description?: string;\n    inputModalities?: readonly ModelModality[];\n}"
          },
          {
            "name": "LlmModelReasoningInfo",
            "declaration": "export interface LlmModelReasoningInfo {\n    efforts: readonly LlmReasoningEffortInfo[];\n    defaultEffort?: ReasoningEffortId;\n}"
          },
          {
            "name": "LlmProviderInfo",
            "declaration": "export interface LlmProviderInfo {\n    id: string;\n    name: string;\n}"
          },
          {
            "name": "LlmProviderVerificationMode",
            "declaration": "export type LlmProviderVerificationMode = 'metadata-auth' | 'endpoint-catalog' | 'minimal-generation';"
          },
          {
            "name": "LlmReasoningEffortInfo",
            "declaration": "export interface LlmReasoningEffortInfo {\n    id: ReasoningEffortId;\n    name: string;\n    description?: string;\n}"
          },
          {
            "name": "LlmResolvedModelInfo",
            "declaration": "export interface LlmResolvedModelInfo extends LlmModelInfo {\n    context?: LlmModelContext;\n    defaultMaxTokens?: number;\n    reasoning?: LlmModelReasoningInfo;\n}"
          },
          {
            "name": "Message",
            "declaration": "export interface Message {\n    readonly id: MessageId;\n    readonly role: 'system' | 'user' | 'assistant';\n    readonly content: ContentBlock[];\n    readonly source: MessageSource;\n}"
          },
          {
            "name": "MessageId",
            "declaration": "export type MessageId = Branded<'MessageId'>;"
          },
          {
            "name": "MessageSource",
            "declaration": "export type MessageSource = MessageSourceMap[keyof MessageSourceMap];"
          },
          {
            "name": "MessageSourceMap",
            "declaration": "export interface MessageSourceMap {\n    user: { kind: 'user'; };\n    plugin: { kind: 'plugin'; plugin: string; } & ContextFormed;\n    model: ModelMessageSource;\n    tool: ToolMessageSource;\n    goal: GoalMessageSource;\n    coordinator: CoordinatorMessageSource;\n    'subagent-prompt': SubagentPromptMessageSource;\n    'subagent-report': SubagentReportMessageSource;\n    'subagent-settled': SubagentSettledMessageSource;\n    'session-reference': SessionReferenceSource;\n    'skill-invocation': SkillInvocationSource;\n}"
          },
          {
            "name": "ModelMessageSource",
            "declaration": "export interface ModelMessageSource extends AssistantProvenance {\n    kind: 'model';\n}"
          },
          {
            "name": "ModelModality",
            "declaration": "export type ModelModality = ModelModalityMap[keyof ModelModalityMap];"
          },
          {
            "name": "ModelModalityMap",
            "declaration": "export interface ModelModalityMap {\n    text: 'text';\n    image: 'image';\n}"
          },
          {
            "name": "PreparedAdapterCall",
            "declaration": "export interface PreparedAdapterCall {\n    readonly model: LlmResolvedModelInfo;\n    stream(options: GenerateOptions): AsyncIterable<StreamChunk>;\n}"
          },
          {
            "name": "PreparedLlmCall",
            "declaration": "export interface PreparedLlmCall {\n    readonly config: LlmCallConfig;\n    readonly retryPolicy: ResolvedRetryPolicy;\n    readonly context?: LlmModelContext;\n    readonly inputModalities?: readonly ModelModality[];\n    readonly adapterDefaults: LlmCallConfigAdapterDefaults;\n    stream(options: GenerateOptions): AsyncIterable<StreamChunk>;\n}"
          },
          {
            "name": "ProviderRequestId",
            "declaration": "export type ProviderRequestId = Branded<'ProviderRequestId'>;"
          },
          {
            "name": "ReasoningBlock",
            "declaration": "export interface ReasoningBlock {\n    type: 'reasoning';\n    text: string;\n}"
          },
          {
            "name": "ReasoningEffortId",
            "declaration": "export type ReasoningEffortId = Branded<'ReasoningEffortId'>;"
          },
          {
            "name": "RemoteCredentialView",
            "declaration": "export interface RemoteCredentialView {\n    readonly configured: boolean;\n    readonly source?: string;\n    readonly writable: boolean;\n}"
          },
          {
            "name": "RemoteLlmCatalogFailure",
            "declaration": "export interface RemoteLlmCatalogFailure {\n    readonly id: string;\n    readonly name: string;\n    readonly message: string;\n}"
          },
          {
            "name": "RemoteLlmCredentialMutation",
            "declaration": "export type RemoteLlmCredentialMutation = { readonly op: 'set'; readonly ref: string; readonly value: string; } | { readonly op: 'unset'; readonly ref: string; };"
          },
          {
            "name": "RemoteLlmDiscoveredModel",
            "declaration": "export interface RemoteLlmDiscoveredModel {\n    readonly id: string;\n    readonly name?: string;\n    readonly contextWindow?: number;\n    readonly maxTokens?: number;\n}"
          },
          {
            "name": "RemoteLlmDiscoveredModelsResult",
            "declaration": "export interface RemoteLlmDiscoveredModelsResult {\n    readonly models: readonly RemoteLlmDiscoveredModel[];\n}"
          },
          {
            "name": "RemoteLlmDiscoverModelsRequest",
            "declaration": "export interface RemoteLlmDiscoverModelsRequest {\n    readonly settingsNs: string;\n    readonly provider?: string;\n    readonly baseURL?: string;\n    readonly api?: string;\n    readonly apiKey?: string;\n}"
          },
          {
            "name": "RemoteLlmModelGroup",
            "declaration": "export interface RemoteLlmModelGroup {\n    readonly id: string;\n    readonly name: string;\n    readonly models: readonly RemoteLlmModelView[];\n}"
          },
          {
            "name": "RemoteLlmModelsResult",
            "declaration": "export interface RemoteLlmModelsResult {\n    readonly groups: readonly RemoteLlmModelGroup[];\n    readonly failures: readonly RemoteLlmCatalogFailure[];\n}"
          },
          {
            "name": "RemoteLlmModelView",
            "declaration": "export interface RemoteLlmModelView {\n    readonly id: string;\n    readonly name: string;\n    readonly description?: string;\n    readonly defaultMaxTokens?: number;\n    readonly reasoning?: RemoteLlmReasoning;\n}"
          },
          {
            "name": "RemoteLlmProviderMutationRequest",
            "declaration": "export interface RemoteLlmProviderMutationRequest {\n    readonly transactionId: string;\n    readonly provider: string;\n    readonly settingsNs: string;\n    readonly ops: readonly RemoteSettingsPathOp[];\n    readonly expectedRevision: number;\n    readonly credential?: RemoteLlmCredentialMutation;\n}"
          },
          {
            "name": "RemoteLlmProviderMutationResult",
            "declaration": "export interface RemoteLlmProviderMutationResult {\n    readonly settings: RemoteSettingsNamespaceView;\n    readonly credential?: RemoteCredentialView;\n    readonly live?: { readonly accepted: true; };\n}"
          },
          {
            "name": "RemoteLlmProviderResumeRequest",
            "declaration": "export interface RemoteLlmProviderResumeRequest {\n    readonly provider: string;\n    readonly transactionId: string;\n    readonly credentialValue?: string;\n}"
          },
          {
            "name": "RemoteLlmProvidersResult",
            "declaration": "export interface RemoteLlmProvidersResult {\n    readonly providers: readonly RemoteLlmProviderView[];\n}"
          },
          {
            "name": "RemoteLlmProviderTransactionRequest",
            "declaration": "export interface RemoteLlmProviderTransactionRequest {\n    readonly provider: string;\n    readonly transactionId: string;\n}"
          },
          {
            "name": "RemoteLlmProviderTransactionResult",
            "declaration": "export interface RemoteLlmProviderTransactionResult {\n    readonly state: 'absent' | 'prepared' | 'credential-staged' | 'settings-applied' | 'credential-applied' | 'committed' | 'rolled-back' | 'committed-not-live';\n    readonly needsCredential: boolean;\n    readonly settingsNs?: string;\n    readonly live?: boolean;\n}"
          },
          {
            "name": "RemoteLlmProviderVerificationRequest",
            "declaration": "export interface RemoteLlmProviderVerificationRequest {\n    readonly provider: string;\n    readonly model: string;\n}"
          },
          {
            "name": "RemoteLlmProviderVerificationResult",
            "declaration": "export type RemoteLlmProviderVerificationResult = { readonly provider: string; readonly model: string; readonly verified: true; readonly mode: Exclude<LlmProviderVerificationMode, 'endpoint-catalog'>; } | { readonly provider: string; readonly model: string; readonly verified: false; readonly mode: 'endpoint-catalog'; readonly classification: 'reachability-only'; };"
          },
          {
            "name": "RemoteLlmProviderView",
            "declaration": "export interface RemoteLlmProviderView {\n    readonly provider: string;\n    readonly displayName: string;\n    readonly settingsNs: string;\n    readonly settingsPath: readonly string[];\n    readonly active: boolean;\n    readonly declared?: boolean;\n    readonly migrationRequired?: { readonly code: 'credential-headers'; readonly fields: readonly string[]; };\n}"
          },
          {
            "name": "RemoteLlmReasoning",
            "declaration": "export interface RemoteLlmReasoning {\n    readonly efforts: readonly RemoteLlmReasoningEffort[];\n    readonly defaultEffort?: string;\n}"
          },
          {
            "name": "RemoteLlmReasoningEffort",
            "declaration": "export interface RemoteLlmReasoningEffort {\n    readonly id: string;\n    readonly name: string;\n    readonly description?: string;\n}"
          },
          {
            "name": "RemoteSettingsJsonValue",
            "declaration": "export type RemoteSettingsJsonValue = null | boolean | number | string | RemoteSettingsJsonValue[] | { [key: string]: RemoteSettingsJsonValue; };"
          },
          {
            "name": "RemoteSettingsNamespaceView",
            "declaration": "export interface RemoteSettingsNamespaceView {\n    readonly ns: string;\n    readonly schema: RemoteSettingsJsonValue;\n    readonly value: RemoteSettingsJsonValue;\n    readonly base?: RemoteSettingsJsonValue;\n    readonly user?: RemoteSettingsJsonValue;\n    readonly applies: 'live' | 'restart';\n    readonly secrets: readonly RemoteSettingsSecretView[];\n    readonly revision: number;\n}"
          },
          {
            "name": "RemoteSettingsPathOp",
            "declaration": "export type RemoteSettingsPathOp = { readonly op: 'set'; readonly path: readonly string[]; readonly value: RemoteSettingsJsonValue; } | { readonly op: 'unset'; readonly path: readonly string[]; };"
          },
          {
            "name": "RemoteSettingsSecretView",
            "declaration": "export interface RemoteSettingsSecretView {\n    readonly path: readonly string[];\n    readonly set: boolean;\n}"
          },
          {
            "name": "ReplayEnvelope",
            "declaration": "export interface ReplayEnvelope {\n    response: unknown;\n    blocks?: readonly unknown[];\n}"
          },
          {
            "name": "ResolvedAlwaysRetryPolicy",
            "declaration": "export interface ResolvedAlwaysRetryPolicy extends ResolvedRetryBackoff {\n    readonly mode: 'always';\n}"
          },
          {
            "name": "ResolvedNormalRetryPolicy",
            "declaration": "export interface ResolvedNormalRetryPolicy extends ResolvedRetryBackoff {\n    readonly mode: 'normal';\n    readonly maxRetries: number;\n    readonly retryableCodes: readonly string[];\n}"
          },
          {
            "name": "ResolvedRetryBackoff",
            "declaration": "export interface ResolvedRetryBackoff {\n    readonly initialDelayMs: number;\n    readonly maxDelayMs: number;\n    readonly jitterRatio: number;\n}"
          },
          {
            "name": "ResolvedRetryPolicy",
            "declaration": "export type ResolvedRetryPolicy = ResolvedNormalRetryPolicy | ResolvedAlwaysRetryPolicy;"
          },
          {
            "name": "SessionId",
            "declaration": "export type SessionId = Branded<'SessionId'>;"
          },
          {
            "name": "SessionReferenceSource",
            "declaration": "export interface SessionReferenceSource {\n    kind: 'session-reference';\n    form: 'recall';\n    version: 1;\n    references: { sessionId: string; label: string; capturedThroughSeq: number | null; compacted: boolean; originalMessages: number; retainedMessages: number; omittedMessages: number; omittedBytes: number; truncated: boolean; inputIndex: number; }[];\n}"
          },
          {
            "name": "SkillInvocationSource",
            "declaration": "export interface SkillInvocationSource {\n    readonly kind: 'skill-invocation';\n    readonly name: string;\n    readonly form: 'instructions';\n}"
          },
          {
            "name": "StreamChunk",
            "declaration": "export type StreamChunk = { type: 'block-start'; index: number; blockType: ContentBlockType; } | { type: 'text-delta'; index: number; text: string; } | { type: 'reasoning-delta'; index: number; text: string; } | { type: 'tool-call-delta'; index: number; id: CallId; name?: string; argumentsDelta: string; } | { type: 'block-end'; index: number; block: ContentBlock; } | { type: 'usage'; usage: TokenUsage; } | { type: 'finish'; reason: FinishReason; replayState?: ReplayEnvelope; };"
          },
          {
            "name": "SubagentPromptMessageSource",
            "declaration": "export interface SubagentPromptMessageSource {\n    readonly kind: 'subagent-prompt';\n    readonly form: 'relay';\n    readonly senderSessionId: SessionId;\n    readonly invocationId: string;\n}"
          },
          {
            "name": "SubagentReportMessageSource",
            "declaration": "export interface SubagentReportMessageSource {\n    readonly kind: 'subagent-report';\n    readonly form: 'relay';\n    readonly senderSessionId: SessionId;\n}"
          },
          {
            "name": "SubagentSettledMessageSource",
            "declaration": "export interface SubagentSettledMessageSource {\n    readonly kind: 'subagent-settled';\n    readonly form: 'notice';\n    readonly summary: string;\n    readonly senderSessionId: SessionId;\n    readonly settlementId: string;\n}"
          },
          {
            "name": "TextBlock",
            "declaration": "export interface TextBlock {\n    type: 'text';\n    text: string;\n}"
          },
          {
            "name": "TokenUsage",
            "declaration": "export interface TokenUsage {\n    inputTokens: number;\n    outputTokens: number;\n    totalTokens?: number;\n    cacheReadTokens?: number;\n    cacheWriteTokens?: number;\n    reasoningTokens?: number;\n}"
          },
          {
            "name": "ToolCallBlock",
            "declaration": "export interface ToolCallBlock {\n    type: 'tool-call';\n    id: CallId;\n    name: string;\n    arguments: string;\n}"
          },
          {
            "name": "ToolMessageSource",
            "declaration": "export interface ToolMessageSource {\n    kind: 'tool';\n    callId: CallId;\n}"
          },
          {
            "name": "ToolResultBlock",
            "declaration": "export interface ToolResultBlock {\n    type: 'tool-result';\n    toolCallId: CallId;\n    content: ContentBlock[];\n    isError?: boolean;\n}"
          },
          {
            "name": "ToolSchema",
            "declaration": "export interface ToolSchema {\n    name: string;\n    description: string;\n    parameters: Record<string, unknown>;\n}"
          }
        ]
      }
    ],
    "events": [
      {
        "description": "The provider topology changed: an adapter registered or unregistered routes, or the configurable-provider directory gained or lost entries. This payload-free registry notification fires at each commit point (including registration disposal); consumers re-read `listProviders()`, `listModels()`, or `listConfigurableProviders()` for the new state. Observer failures are contained and cannot veto the registry mutation.",
        "summary": "The provider topology changed: an adapter registered or unregistered routes, or the configurable-provider directory gained or lost entries.",
        "tags": [
          {
            "name": "mode",
            "comment": "emit",
            "text": "@mode emit"
          }
        ],
        "jsDoc": "/**\n * The provider topology changed: an adapter registered or unregistered\n * routes, or the configurable-provider directory gained or lost entries.\n * This payload-free registry notification fires at each commit point\n * (including registration disposal); consumers re-read `listProviders()`,\n * `listModels()`, or `listConfigurableProviders()` for the new state.\n * Observer failures are contained and cannot veto the registry mutation.\n * @mode emit\n */",
        "name": "llm/adapters-updated",
        "mode": "emit",
        "signature": "'llm/adapters-updated'(): void"
      },
      {
        "description": "Waterfall around every streaming model call (retry, replay, routing). Bound to the {@link LlmRuntime}; call `next()` to reach the resolved adapter's stream, or yield your own chunks to short-circuit.",
        "summary": "Waterfall around every streaming model call (retry, replay, routing).",
        "tags": [
          {
            "name": "param",
            "argument": "options",
            "comment": "- the full request. A LOOP-built request carries the process-local {@link markAgentLoopRequest} identity and arrives deep-frozen (mutation throws): its content is a pure function of the session log (the reconstructability Agent Note), so listeners read it, never rewrite it. Hand-built calls do not carry that marker; their messages already obey the immutable creation contract.",
            "text": "@param options - the full request. A LOOP-built request carries the\n     *   process-local {@link markAgentLoopRequest} identity and arrives deep-frozen\n     *   (mutation throws): its content is a pure function of the session log (the\n     *   reconstructability Agent Note), so listeners read it, never rewrite it.\n     *   Hand-built calls do not carry that marker; their messages already obey\n     *   the immutable creation contract.\n     *"
          },
          {
            "name": "mode",
            "comment": "waterfall",
            "text": "@mode waterfall"
          }
        ],
        "jsDoc": "/**\n * Waterfall around every streaming model call (retry, replay, routing).\n * Bound to the {@link LlmRuntime}; call `next()` to reach the resolved\n * adapter's stream, or yield your own chunks to short-circuit.\n * @param options - the full request. A LOOP-built request carries the\n *   process-local {@link markAgentLoopRequest} identity and arrives deep-frozen\n *   (mutation throws): its content is a pure function of the session log (the\n *   reconstructability Agent Note), so listeners read it, never rewrite it.\n *   Hand-built calls do not carry that marker; their messages already obey\n *   the immutable creation contract.\n * @mode waterfall\n */",
        "name": "llm/stream",
        "mode": "waterfall",
        "signature": "'llm/stream'(this: LlmRuntime, options: GenerateOptions, next: () => AsyncIterable<StreamChunk>): AsyncIterable<StreamChunk>"
      }
    ],
    "objects": []
  },
}
