/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { LlmConfigurableProvider, LlmProviderInfo, RemoteLlmDiscoveredModelsResult, RemoteLlmDiscoverModelsRequest, RemoteLlmModelsResult, RemoteLlmProviderMutationRequest, RemoteLlmProviderMutationResult, RemoteLlmProviderResumeRequest, RemoteLlmProvidersResult, RemoteLlmProviderTransactionRequest, RemoteLlmProviderTransactionResult, RemoteLlmProviderVerificationRequest, RemoteLlmProviderVerificationResult } from '@deepseek-ai/dsh-llm/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6c6c6d {
    discoverModels: (request: RemoteLlmDiscoverModelsRequest, signal?: AbortSignal) => Promise<RemoteResult<RemoteLlmDiscoveredModelsResult>>
    listConfigurableProviders: () => Promise<RemoteResult<LlmConfigurableProvider[]>>
    listProviders: () => Promise<RemoteResult<LlmProviderInfo[]>>
    models: () => Promise<RemoteResult<RemoteLlmModelsResult>>
    mutateProvider: (request: RemoteLlmProviderMutationRequest, signal?: AbortSignal) => Promise<RemoteResult<RemoteLlmProviderMutationResult>>
    providers: () => Promise<RemoteResult<RemoteLlmProvidersResult>>
    providerTransaction: (request: RemoteLlmProviderTransactionRequest) => Promise<RemoteResult<RemoteLlmProviderTransactionResult>>
    resumeProvider: (request: RemoteLlmProviderResumeRequest, signal?: AbortSignal) => Promise<RemoteResult<RemoteLlmProviderMutationResult>>
    verifyProvider: (request: RemoteLlmProviderVerificationRequest, signal?: AbortSignal) => Promise<RemoteResult<RemoteLlmProviderVerificationResult>>
  }
  interface TypertRemoteMap {
    'llm/discoverModels': (request: RemoteLlmDiscoverModelsRequest, signal?: AbortSignal) => Promise<RemoteResult<RemoteLlmDiscoveredModelsResult>>
    'llm/listConfigurableProviders': () => Promise<RemoteResult<LlmConfigurableProvider[]>>
    'llm/listProviders': () => Promise<RemoteResult<LlmProviderInfo[]>>
    'llm/models': () => Promise<RemoteResult<RemoteLlmModelsResult>>
    'llm/mutateProvider': (request: RemoteLlmProviderMutationRequest, signal?: AbortSignal) => Promise<RemoteResult<RemoteLlmProviderMutationResult>>
    'llm/providers': () => Promise<RemoteResult<RemoteLlmProvidersResult>>
    'llm/providerTransaction': (request: RemoteLlmProviderTransactionRequest) => Promise<RemoteResult<RemoteLlmProviderTransactionResult>>
    'llm/resumeProvider': (request: RemoteLlmProviderResumeRequest, signal?: AbortSignal) => Promise<RemoteResult<RemoteLlmProviderMutationResult>>
    'llm/verifyProvider': (request: RemoteLlmProviderVerificationRequest, signal?: AbortSignal) => Promise<RemoteResult<RemoteLlmProviderVerificationResult>>
  }
  interface TypertRemoteNamespaceMap {
    'llm': TypertRemoteNamespace$6c6c6d
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
