/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { ModelCatalog, SessionControlFrame, SessionFollowFrame, SessionFollowRequest, SessionOpenWorkspacePathRequest, SessionOpenWorkspacePathValue, SessionPage, SessionPageRequest, SkillListRequest, SkillListValue } from '@deepseek-ai/dsh-api-session-controller/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$73657373696f6e {
    canOpenWorkspacePath: () => Promise<RemoteResult<boolean>>
    control: (signal?: AbortSignal) => AsyncIterable<SessionControlFrame>
    follow: (request: SessionFollowRequest, signal?: AbortSignal) => AsyncIterable<SessionFollowFrame>
    modelCatalog: () => Promise<RemoteResult<ModelCatalog>>
    openWorkspacePath: (request: SessionOpenWorkspacePathRequest, signal?: AbortSignal) => Promise<RemoteResult<SessionOpenWorkspacePathValue>>
    page: (request: SessionPageRequest, signal?: AbortSignal) => Promise<RemoteResult<SessionPage>>
  }
  interface TypertRemoteNamespace$736b696c6c73 {
    list: (request: SkillListRequest, signal?: AbortSignal) => Promise<RemoteResult<SkillListValue>>
  }
  interface TypertRemoteMap {
    'session/canOpenWorkspacePath': () => Promise<RemoteResult<boolean>>
    'session/control': (signal?: AbortSignal) => AsyncIterable<SessionControlFrame>
    'session/follow': (request: SessionFollowRequest, signal?: AbortSignal) => AsyncIterable<SessionFollowFrame>
    'session/modelCatalog': () => Promise<RemoteResult<ModelCatalog>>
    'session/openWorkspacePath': (request: SessionOpenWorkspacePathRequest, signal?: AbortSignal) => Promise<RemoteResult<SessionOpenWorkspacePathValue>>
    'session/page': (request: SessionPageRequest, signal?: AbortSignal) => Promise<RemoteResult<SessionPage>>
    'skills/list': (request: SkillListRequest, signal?: AbortSignal) => Promise<RemoteResult<SkillListValue>>
  }
  interface TypertRemoteNamespaceMap {
    'session': TypertRemoteNamespace$73657373696f6e
    'skills': TypertRemoteNamespace$736b696c6c73
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
