/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { WorkspaceFollowFrame } from '@deepseek-ai/dsh-api-workspace-controller/types'
import type { DirectoryListing } from '@deepseek-ai/dsh-host-directory-picker/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6469726563746f72795069636b6572 {
    createDirectory: (path: string, name: string) => Promise<RemoteResult<string>>
    list: (path: string | undefined, signal?: AbortSignal) => Promise<RemoteResult<DirectoryListing>>
    pick: (signal?: AbortSignal) => Promise<RemoteResult<string | null>>
  }
  interface TypertRemoteNamespace$776f726b7370616365 {
    follow: (signal?: AbortSignal) => AsyncIterable<WorkspaceFollowFrame>
  }
  interface TypertRemoteMap {
    'directoryPicker/createDirectory': (path: string, name: string) => Promise<RemoteResult<string>>
    'directoryPicker/list': (path: string | undefined, signal?: AbortSignal) => Promise<RemoteResult<DirectoryListing>>
    'directoryPicker/pick': (signal?: AbortSignal) => Promise<RemoteResult<string | null>>
    'workspace/follow': (signal?: AbortSignal) => AsyncIterable<WorkspaceFollowFrame>
  }
  interface TypertRemoteNamespaceMap {
    'directoryPicker': TypertRemoteNamespace$6469726563746f72795069636b6572
    'workspace': TypertRemoteNamespace$776f726b7370616365
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
