/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_api_workspace_controller_directoryPicker_createDirectory_parameter_0$schema = z.string()
const _deepseek_ai_dsh_api_workspace_controller_directoryPicker_createDirectory_parameter_1$schema = z.string()
const _deepseek_ai_dsh_api_workspace_controller_directoryPicker_createDirectory_result$schema = z.string()
const _deepseek_ai_dsh_api_workspace_controller_directoryPicker_list_parameter_0$schema = z.union([z.undefined(), z.string()])
const _deepseek_ai_dsh_api_workspace_controller_directoryPicker_list_result$schema = z.object({
  'path': z.string(),
  'home': z.string(),
  'crumbs': z.array(z.object({
  'name': z.string(),
  'path': z.string(),
  'hidden': z.boolean(),
})),
  'entries': z.array(z.object({
  'name': z.string(),
  'path': z.string(),
  'hidden': z.boolean(),
})),
  'truncated': z.boolean(),
})
const _deepseek_ai_dsh_api_workspace_controller_directoryPicker_pick_result$schema = z.union([z.literal(null), z.string()])
const _deepseek_ai_dsh_api_workspace_controller_workspace_follow_result$schema = z.union([z.object({
  'type': z.literal("baseline").readonly(),
  'value': z.object({
  'items': z.array(z.object({
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
  'path': z.string().readonly(),
  'title': z.string().readonly(),
  'sessionIds': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
})).readonly(),
  'archivedSessionIds': z.array(z.intersection(z.string(), z.unknown())).readonly(),
}).readonly(),
}), z.object({
  'type': z.literal("upsert").readonly(),
  'workspace': z.object({
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
  'path': z.string().readonly(),
  'title': z.string().readonly(),
  'sessionIds': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
}).readonly(),
}), z.object({
  'type': z.literal("remove").readonly(),
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'type': z.literal("order").readonly(),
  'workspaceIds': z.array(z.intersection(z.string(), z.unknown())).readonly(),
}), z.object({
  'type': z.literal("archived").readonly(),
  'archivedSessionIds': z.array(z.intersection(z.string(), z.unknown())).readonly(),
})])

export const TYPERT = {
  package: '@deepseek-ai/dsh-api-workspace-controller',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-api-workspace-controller#directoryPicker/createDirectory',
      service: 'directoryPickerController',
      namespace: 'directoryPicker',
      method: 'createDirectory',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'path',
          wire: 'path',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-api-workspace-controller#directoryPicker/createDirectory:path',
            schema: _deepseek_ai_dsh_api_workspace_controller_directoryPicker_createDirectory_parameter_0$schema,
          },
        },
        {
          name: 'name',
          wire: 'name',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-api-workspace-controller#directoryPicker/createDirectory:name',
            schema: _deepseek_ai_dsh_api_workspace_controller_directoryPicker_createDirectory_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-api-workspace-controller#directoryPicker/createDirectory:result',
        schema: _deepseek_ai_dsh_api_workspace_controller_directoryPicker_createDirectory_result$schema,
      },
      sourceLocation: {"file":"packages/api/workspace-controller/src/directory-picker.ts","line":86,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-api-workspace-controller#directoryPicker/list',
      service: 'directoryPickerController',
      namespace: 'directoryPicker',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'path',
          wire: 'path',
          source: 'json',
          acceptsUndefined: true,
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-api-workspace-controller#directoryPicker/list:path',
            schema: _deepseek_ai_dsh_api_workspace_controller_directoryPicker_list_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-host-directory-picker/types#DirectoryListing',
        schema: _deepseek_ai_dsh_api_workspace_controller_directoryPicker_list_result$schema,
      },
      sourceLocation: {"file":"packages/api/workspace-controller/src/directory-picker.ts","line":70,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-api-workspace-controller#directoryPicker/pick',
      service: 'directoryPickerController',
      namespace: 'directoryPicker',
      method: 'pick',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-api-workspace-controller#directoryPicker/pick:result',
        schema: _deepseek_ai_dsh_api_workspace_controller_directoryPicker_pick_result$schema,
      },
      sourceLocation: {"file":"packages/api/workspace-controller/src/directory-picker.ts","line":53,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-api-workspace-controller#workspace/follow',
      service: 'workspaceController',
      namespace: 'workspace',
      method: 'follow',
      mode: 'stream',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-api-workspace-controller/types#WorkspaceFollowFrame',
        schema: _deepseek_ai_dsh_api_workspace_controller_workspace_follow_result$schema,
      },
      sourceLocation: {"file":"packages/api/workspace-controller/src/index.ts","line":42,"column":3},
    },
  ],
  model: {
    "services": [
      {
        "description": "Host service backing the generated `ctx.remote.directoryPicker` namespace. The seam it exports is abstract and therefore never a Loader entry of its own, so this controller carries the wire verbs: one composed backend serves either the native chooser or the browse primitives, and a verb the composition cannot serve is refused rather than approximated.",
        "summary": "Host service backing the generated `ctx.remote.directoryPicker` namespace.",
        "tags": [],
        "jsDoc": "/**\n * Host service backing the generated `ctx.remote.directoryPicker` namespace. The\n * seam it exports is abstract and therefore never a Loader entry of its own, so\n * this controller carries the wire verbs: one composed backend serves either the\n * native chooser or the browse primitives, and a verb the composition cannot\n * serve is refused rather than approximated.\n */",
        "key": "directoryPickerController",
        "exportName": "DirectoryPickerController",
        "members": [
          {
            "kind": "method",
            "name": "pick",
            "signature": "@Remote('pick') async pick(signal: AbortSignal): Promise<string | null>",
            "summary": "Open the host's OS chooser for a Remote caller.",
            "jsDoc": "/**\n * Open the host's OS chooser for a Remote caller.\n * @param signal - caller lifetime; abort terminates the chooser.\n * @returns the chosen absolute path, or null when the operator cancels.\n */"
          },
          {
            "kind": "method",
            "name": "list",
            "signature": "@Remote('list') async list(path: string | undefined, signal: AbortSignal): Promise<DirectoryListing>",
            "summary": "List one directory level for a Remote caller's in-app browser.",
            "jsDoc": "/**\n * List one directory level for a Remote caller's in-app browser.\n * @param path - absolute directory to list; absent lists the home directory.\n * @param signal - caller lifetime; abort stops the backend's scan instead of\n *   letting it outlive a disconnected caller.\n * @returns the level's listing with its ancestry.\n */"
          },
          {
            "kind": "method",
            "name": "createDirectory",
            "signature": "@Remote('createDirectory') async createDirectory(path: string, name: string): Promise<string>",
            "summary": "Create one child directory for a Remote caller's in-app browser.",
            "jsDoc": "/**\n * Create one child directory for a Remote caller's in-app browser.\n * @param path - absolute existing parent directory.\n * @param name - single non-blank path segment.\n * @returns the created directory's absolute path.\n */"
          }
        ],
        "types": [
          {
            "name": "DirectoryEntry",
            "declaration": "export interface DirectoryEntry {\n    name: string;\n    path: string;\n    hidden: boolean;\n}"
          },
          {
            "name": "DirectoryListing",
            "declaration": "export interface DirectoryListing {\n    path: string;\n    home: string;\n    crumbs: DirectoryEntry[];\n    entries: DirectoryEntry[];\n    truncated: boolean;\n}"
          }
        ]
      },
      {
        "description": "Host service backing the generated `ctx.remote.workspace` namespace.",
        "summary": "Host service backing the generated `ctx.remote.workspace` namespace.",
        "tags": [],
        "jsDoc": "/** Host service backing the generated `ctx.remote.workspace` namespace. */",
        "key": "workspaceController",
        "exportName": "WorkspaceController",
        "members": [
          {
            "kind": "method",
            "name": "follow",
            "signature": "@Remote({ mode: 'stream' }) follow(signal: AbortSignal): AsyncIterable<WorkspaceFollowFrame>",
            "summary": "Stream a complete Workspace baseline followed by ordered increments.",
            "jsDoc": "/**\n * Stream a complete Workspace baseline followed by ordered increments.\n * @param signal - generation cancellation.\n * @returns baseline followed by ordered Workspace increments.\n */"
          }
        ],
        "types": [
          {
            "name": "Branded",
            "declaration": "export type Branded<B extends string> = string & { readonly [BRAND]: B; };"
          },
          {
            "name": "SessionId",
            "declaration": "export type SessionId = Branded<'SessionId'>;"
          },
          {
            "name": "WorkspaceBaseline",
            "declaration": "export interface WorkspaceBaseline {\n    readonly items: readonly WorkspaceView[];\n    readonly archivedSessionIds: readonly SessionId[];\n}"
          },
          {
            "name": "WorkspaceFollowFrame",
            "declaration": "export type WorkspaceFollowFrame = { readonly type: 'baseline'; readonly value: WorkspaceBaseline; } | WorkspaceFollowIncrement;"
          },
          {
            "name": "WorkspaceFollowIncrement",
            "declaration": "export type WorkspaceFollowIncrement = { readonly type: 'upsert'; readonly workspace: WorkspaceView; } | { readonly type: 'remove'; readonly workspaceId: WorkspaceId; } | { readonly type: 'order'; readonly workspaceIds: readonly WorkspaceId[]; } | { readonly type: 'archived'; readonly archivedSessionIds: readonly SessionId[]; };"
          },
          {
            "name": "WorkspaceId",
            "declaration": "export type WorkspaceId = Branded<'WorkspaceId'>;"
          },
          {
            "name": "WorkspaceRemoteView",
            "declaration": "export interface WorkspaceRemoteView {\n    readonly workspaceId: WorkspaceId;\n    readonly path: string;\n    readonly title: string;\n    readonly sessionIds: readonly SessionId[];\n    readonly createdAt: string;\n    readonly updatedAt: string;\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
