/**
 * Generate the English and Chinese `docs/module-graph` pair from in-repo `peerDependencies`, the canonical
 * runtime edges. The deterministic output groups packages by directory and
 * renders both Mermaid and a dependency table; `--check` verifies freshness.
 */

import { resolve } from 'node:path'
import { readFileSync, writeFileSync } from 'node:fs'
import {
  collectPackageGraph,
  escapeMermaidLabel as escLabel,
  graphNodeId as nodeId,
  type PackageGraphNode,
} from './package-graph.ts'

const root = resolve(import.meta.dirname, '..')
const OUTPUTS = ['docs/module-graph.md', 'docs/module-graph.zh.md'] as const
type Pkg = PackageGraphNode

const GROUP_ORDER = [
  'util',
  'llm',
  'core',
  'goal',
  'bash',
  'fs',
  'skill',
  'compact',
  'subagent',
  'web',
  'spill',
  'timeout',
  'todo',
  'plan',
  'cordis',
  'hooks',
  'session-persistence',
  'session-query',
  'session-title',
  'support',
  'acp',
  'ui',
]

function packageLink(pkg: Pkg): string {
  return `[\`${pkg.short}\`](../${pkg.rel})`
}

/**
 * Render both language documents from one package graph and one set of rows.
 * @param pkgs - Dependency-ordered nodes from the canonical package graph collector.
 * @returns English and Chinese documents keyed by their repository-relative paths.
 */
export function renderModuleGraphs(pkgs: Pkg[]): Record<(typeof OUTPUTS)[number], string> {
  const edges: string[] = []
  for (const p of pkgs) {
    for (const d of p.deps) edges.push(`  ${nodeId('pkg', p.short)} --> ${nodeId('pkg', d)}`)
  }
  const byShort = new Map(pkgs.map(pkg => [pkg.short, pkg]))
  const groups = [...new Set(pkgs.map(pkg => pkg.group))].sort((a, b) => {
    const ia = GROUP_ORDER.indexOf(a)
    const ib = GROUP_ORDER.indexOf(b)
    const na = ia === -1 ? Number.MAX_SAFE_INTEGER : ia
    const nb = ib === -1 ? Number.MAX_SAFE_INTEGER : ib
    return na - nb || a.localeCompare(b)
  })
  const groupBlocks: string[] = []
  for (const group of groups) {
    groupBlocks.push(`  subgraph ${nodeId('group', group)}["packages/${escLabel(group)}"]`)
    for (const pkg of pkgs.filter(p => p.group === group).sort((a, b) => a.short.localeCompare(b.short))) {
      groupBlocks.push(`    ${nodeId('pkg', pkg.short)}["${escLabel(pkg.short)}"]`)
    }
    groupBlocks.push('  end')
  }
  const rows = pkgs.map((p) => {
    const deps = p.deps.length ? p.deps.map((d) => {
      const dep = byShort.get(d)
      return dep ? packageLink(dep) : `\`${d}\``
    }).join(', ') : '—'
    return `| ${packageLink(p)} | \`${p.group}\` | ${deps} |`
  })
  const prose = {
    en: {
      banner: '<!-- Generated by scripts/gen-module-graph.ts — do not edit by hand.\n     Run `pnpm run gen-module-graph` to regenerate. -->',
      title: '# Module dependency graph',
      switcher: 'English | [中文](module-graph.zh.md)',
      introduction: 'Inter-package dependencies among the `@deepseek-ai/dsh-*` harness packages, derived from each package\'s `peerDependencies` (the canonical runtime-dependency signal) and grouped by the `packages/<group>/<pkg>` hierarchy. An edge `a --> b` means package `a` depends on package `b`. Names have the `@deepseek-ai/dsh-` prefix stripped.',
      table: '| Package | Group | Depends on |',
    },
    zh: {
      banner: '<!-- 由 scripts/gen-module-graph.ts 生成，请勿手工编辑。\n     运行 `pnpm run gen-module-graph` 重新生成。 -->',
      title: '# 模块依赖关系图',
      switcher: '[English](module-graph.md) | 中文',
      introduction: '`@deepseek-ai/dsh-*` harness 包之间的依赖关系。该关系图根据各包的 `peerDependencies`（规范的运行时依赖信号）生成，并按 `packages/<group>/<pkg>` 层级分组。边 `a --> b` 表示包 `a` 依赖包 `b`。名称中的 `@deepseek-ai/dsh-` 前缀已移除。',
      table: '| 包 | 分组 | 依赖 |',
    },
  }
  function document(language: keyof typeof prose): string {
    const labels = prose[language]
    return [
      labels.banner, '', labels.title, '', labels.switcher, '', labels.introduction, '',
      '```mermaid', 'flowchart TD', ...groupBlocks, ...edges, '```', '',
      labels.table, '| --- | --- | --- |', ...rows, '',
    ].join('\n')
  }
  return { 'docs/module-graph.md': document('en'), 'docs/module-graph.zh.md': document('zh') }
}

/**
 * Generate or freshness-check both languages without changing pairing confirmations.
 * @param repositoryRoot - Repository containing package manifests and the docs directory.
 * @param check - Compare only; a stale or missing document is never rewritten.
 * @returns Paths of stale documents in check mode, or an empty list after generation.
 */
export function generateModuleGraphs(repositoryRoot: string, check: boolean): string[] {
  const contents = renderModuleGraphs(collectPackageGraph(repositoryRoot, GROUP_ORDER, 'gen-module-graph'))
  const stale: string[] = []
  for (const path of OUTPUTS) {
    if (!check) {
      writeFileSync(resolve(repositoryRoot, path), contents[path])
      continue
    }
    let committed: string | null = null
    try {
      committed = readFileSync(resolve(repositoryRoot, path), 'utf8')
    } catch {
      // A missing or unreadable artifact cannot satisfy the freshness check.
      committed = null
    }
    if (committed !== contents[path]) stale.push(path)
  }
  return stale
}

function main(): void {
  const check = process.argv.includes('--check')
  const stale = generateModuleGraphs(root, check)
  if (stale.length > 0) {
    for (const path of stale) {
      console.error(`gen-module-graph: ${path} is stale. Run \`pnpm run gen-module-graph\` and re-record the reviewed bilingual pair.`)
    }
    process.exitCode = 1
    return
  }
  console.log(`gen-module-graph: ${OUTPUTS.join(' and ')} ${check ? 'are up to date' : 'written'}.`)
}

if (process.argv[1] && import.meta.filename === resolve(process.argv[1])) main()
