/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { SessionId } from '@deepseek-ai/dsh-session/types'
import type { RemoteSkillCatalog } from '@deepseek-ai/dsh-skill/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$736b696c6c {
    list: (agentId: SessionId, signal?: AbortSignal) => Promise<RemoteResult<RemoteSkillCatalog>>
  }
  interface TypertRemoteMap {
    'skill/list': (agentId: SessionId, signal?: AbortSignal) => Promise<RemoteResult<RemoteSkillCatalog>>
  }
  interface TypertRemoteNamespaceMap {
    'skill': TypertRemoteNamespace$736b696c6c
  }
  interface TypertRemoteScopeMap {
    'agent:skill/list': (signal?: AbortSignal) => Promise<RemoteResult<RemoteSkillCatalog>>
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
