/**
 * Native Swift consumer coverage for generated Typert Remote descriptors.
 *
 * Gateway ownership is dynamic: every live strict descriptor can be claimed.
 * This list records the routes currently consumed by Ark so build checks can
 * reject a missing descriptor without constraining future Host plugins.
 */
export const NATIVE_TYPERT_REMOTE_ENDPOINTS = [
  'agentPreset/copy',
  'agentPreset/list',
  'agentPreset/openDocument',
  'agentPreset/read',
  'agentPreset/remove',
  'agentPreset/select',
  'commands/execute',
  'commands/list',
  'credentials/describe',
  'credentials/set',
  'credentials/unset',
  'fileReferences/list',
  'goal/clear',
  'goal/edit',
  'goal/pause',
  'goal/resume',
  'knowledgeWiki/createPage',
  'knowledgeWiki/createProject',
  'knowledgeWiki/deepResearch',
  'knowledgeWiki/graph',
  'knowledgeWiki/ingestQueueAdd',
  'knowledgeWiki/ingestQueueCancel',
  'knowledgeWiki/ingestQueueStatus',
  'knowledgeWiki/list',
  'knowledgeWiki/listProjects',
  'knowledgeWiki/pageContent',
  'knowledgeWiki/removeProject',
  'knowledgeWiki/resolveReview',
  'knowledgeWiki/resolveReviews',
  'knowledgeWiki/reviews',
  'knowledgeWiki/search',
  'knowledgeWiki/setProject',
  'knowledgeWiki/writePage',
  'llm/discoverModels',
  'llm/models',
  'llm/mutateProvider',
  'llm/providerTransaction',
  'llm/providers',
  'llm/resumeProvider',
  'messageFeedback/delete',
  'messageFeedback/list',
  'messageFeedback/put',
  'pluginInventory/list',
  'session/attachment',
  'session/cancel',
  'session/create',
  'session/fork',
  'session/history',
  'session/list',
  'session/models',
  'session/prompt',
  'session/rename',
  'session/search',
  'session/selectModel',
  'session/updateQueue',
  'sessionReferenceResolver/candidates',
  'settings/describe',
  'settings/openDocument',
  'settings/mutate',
  'skill/list',
  'subagent/history',
  'subagent/interrupt',
  'subagent/list',
  'subagent/prompt',
  'workbench/webRead',
  'workspace/archiveSession',
  'workspace/create',
  'workspace/delete',
  'workspace/deleteArchivedSession',
  'workspace/insertBefore',
  'workspace/insertSessionBefore',
  'workspace/list',
  'workspace/rename',
  'workspace/unarchiveSession',
] as const

/**
 * Deliberate API-only legacy calls still consumed by Native Ark. Kept as an
 * explicit empty fail-closed list so a future dot route cannot silently bypass
 * strict Remote.
 */
export const NATIVE_LEGACY_API_ENDPOINTS = [] as const

/** Native-consumed Typert Remote endpoint. */
export type NativeTypertRemoteEndpoint = typeof NATIVE_TYPERT_REMOTE_ENDPOINTS[number]

/** Exact Typert service owner expected for each current Native endpoint. */
export const NATIVE_TYPERT_REMOTE_OWNERS: Readonly<Record<NativeTypertRemoteEndpoint, string>> = {
  'agentPreset/copy': 'agentPresets',
  'agentPreset/list': 'agentPresets',
  'agentPreset/openDocument': 'agentPresets',
  'agentPreset/read': 'agentPresets',
  'agentPreset/remove': 'agentPresets',
  'agentPreset/select': 'agentPresets',
  'commands/execute': 'commands',
  'commands/list': 'commands',
  'credentials/describe': 'credentials',
  'credentials/set': 'credentials',
  'credentials/unset': 'credentials',
  'fileReferences/list': 'fileReferences',
  'goal/clear': 'goals',
  'goal/edit': 'goals',
  'goal/pause': 'goals',
  'goal/resume': 'goals',
  'knowledgeWiki/createPage': 'knowledgeWiki',
  'knowledgeWiki/createProject': 'knowledgeWiki',
  'knowledgeWiki/deepResearch': 'knowledgeWiki',
  'knowledgeWiki/graph': 'knowledgeWiki',
  'knowledgeWiki/ingestQueueAdd': 'knowledgeWiki',
  'knowledgeWiki/ingestQueueCancel': 'knowledgeWiki',
  'knowledgeWiki/ingestQueueStatus': 'knowledgeWiki',
  'knowledgeWiki/list': 'knowledgeWiki',
  'knowledgeWiki/listProjects': 'knowledgeWiki',
  'knowledgeWiki/pageContent': 'knowledgeWiki',
  'knowledgeWiki/removeProject': 'knowledgeWiki',
  'knowledgeWiki/resolveReview': 'knowledgeWiki',
  'knowledgeWiki/resolveReviews': 'knowledgeWiki',
  'knowledgeWiki/reviews': 'knowledgeWiki',
  'knowledgeWiki/search': 'knowledgeWiki',
  'knowledgeWiki/setProject': 'knowledgeWiki',
  'knowledgeWiki/writePage': 'knowledgeWiki',
  'llm/discoverModels': 'llm',
  'llm/models': 'llm',
  'llm/mutateProvider': 'llm',
  'llm/providerTransaction': 'llm',
  'llm/providers': 'llm',
  'llm/resumeProvider': 'llm',
  'messageFeedback/delete': 'messageFeedback',
  'messageFeedback/list': 'messageFeedback',
  'messageFeedback/put': 'messageFeedback',
  'pluginInventory/list': 'pluginInventory',
  'session/attachment': 'sessions',
  'session/cancel': 'sessions',
  'session/create': 'sessions',
  'session/fork': 'sessions',
  'session/history': 'sessions',
  'session/list': 'sessions',
  'session/models': 'sessions',
  'session/prompt': 'sessions',
  'session/rename': 'sessions',
  'session/search': 'sessions',
  'session/selectModel': 'sessions',
  'session/updateQueue': 'sessions',
  'sessionReferenceResolver/candidates': 'sessionReferenceResolver',
  'settings/describe': 'settings',
  'settings/openDocument': 'settings',
  'settings/mutate': 'settings',
  'skill/list': 'skills',
  'subagent/history': 'subagents',
  'subagent/interrupt': 'subagents',
  'subagent/list': 'subagents',
  'subagent/prompt': 'subagents',
  'workbench/webRead': 'workbench',
  'workspace/archiveSession': 'workspaceRegistry',
  'workspace/create': 'workspaceRegistry',
  'workspace/delete': 'workspaceRegistry',
  'workspace/deleteArchivedSession': 'workspaceRegistry',
  'workspace/insertBefore': 'workspaceRegistry',
  'workspace/insertSessionBefore': 'workspaceRegistry',
  'workspace/list': 'workspaceRegistry',
  'workspace/rename': 'workspaceRegistry',
  'workspace/unarchiveSession': 'workspaceRegistry',
}
