/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { ContentBlock } from '@deepseek-ai/dsh-llm/types'
import type { SessionId } from '@deepseek-ai/dsh-session/types'
import type { RemoteSubagentCatalog, RemoteSubagentHistory, RemoteSubagentInterruptReceipt, RemoteSubagentPromptReceipt } from '@deepseek-ai/dsh-subagent/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$7375626167656e74 {
    history: (parentSessionId: string, childSessionId: string, mode: 'one-shot' | 'continuable', beforeSeq: number | undefined, maxMessages: number | undefined, signal?: AbortSignal) => Promise<RemoteResult<RemoteSubagentHistory>>
    interrupt: (parentSessionId: string, childSessionId: string) => Promise<RemoteResult<RemoteSubagentInterruptReceipt>>
    list: (parentSessionId: string, signal?: AbortSignal) => Promise<RemoteResult<RemoteSubagentCatalog>>
    prompt: (agentId: SessionId, childSessionId: string, content: ContentBlock[], invocationId: string, signal?: AbortSignal) => Promise<RemoteResult<RemoteSubagentPromptReceipt>>
  }
  interface TypertRemoteMap {
    'subagent/history': (parentSessionId: string, childSessionId: string, mode: 'one-shot' | 'continuable', beforeSeq: number | undefined, maxMessages: number | undefined, signal?: AbortSignal) => Promise<RemoteResult<RemoteSubagentHistory>>
    'subagent/interrupt': (parentSessionId: string, childSessionId: string) => Promise<RemoteResult<RemoteSubagentInterruptReceipt>>
    'subagent/list': (parentSessionId: string, signal?: AbortSignal) => Promise<RemoteResult<RemoteSubagentCatalog>>
    'subagent/prompt': (agentId: SessionId, childSessionId: string, content: ContentBlock[], invocationId: string, signal?: AbortSignal) => Promise<RemoteResult<RemoteSubagentPromptReceipt>>
  }
  interface TypertRemoteNamespaceMap {
    'subagent': TypertRemoteNamespace$7375626167656e74
  }
  interface TypertRemoteScopeMap {
    'agent:subagent/prompt': (childSessionId: string, content: ContentBlock[], invocationId: string, signal?: AbortSignal) => Promise<RemoteResult<RemoteSubagentPromptReceipt>>
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
